<?php
$this->headLink()->appendStylesheet('/css/chosen.min.css');

$this->headScript()->appendFile(
'/js/chosen.jquery.min.js?v=1',
'text/javascript'
);
?>
<script>
    <?php $this->headScript()->captureStart() ?>
    $(function() {
        $('#college').chosen({search_contains: true})
    })
    <?php $this->headScript()->captureEnd() ?>
</script>

<h1>Add a Peer</h1>

<?= $this->ztbForm($this->form->prepare()) ?>
