<script type="text/javascript" src="/ckeditor/ckeditor.js"></script>
<script type="text/javascript">
    <?php $this->headScript()->captureStart() ?>
    $(function() {
        CKEDITOR.replace(
            'wysiwygContent',
            {
                allowedContent: true,
                'contentCss': '/css/index.css'
            }
        )
    })
    <?php $this->headScript()->captureEnd() ?>
</script>


<h2>Edit Page</h2>

<?php

$form = $this->form;
$form->setAttribute('class', 'form-horizontal');
$form->setAttribute('action', '/pages/edit');
$form->setAttribute('method', 'post');
$form->prepare();

?>

<?= $this->ztbForm($form) ?>
