<?php

// Data Tables
$this->headScript()->appendFile(
'/js/jquery.dataTables.min.js',
'text/javascript'
);
$this->headLink()->appendStylesheet('/css/jquery.dataTables.min.css');
?>

<script>
    $(document).ready(function() {

        // Data table
        var dataTable = $('#pages').dataTable({
            // show X entries options
            "aLengthMenu": [[25, 50, 100, -1], [25, 50, 100, "All"]],
            'iDisplayLength': 25
        });
    })
</script>

        <?php /** @var \Mrss\Entity\Page[] $pages */ ?>

<h2>Pages</h2>

<p>
    <a href="/pages/edit" class="btn" id="addPageBtn">
        <i class="icon-black icon-plus-sign"></i>
        Add a page
    </a>
</p>

<table class="table table-striped table-bordered" id="pages">
    <thead>
        <tr>
            <th>Title</th>
            <th>Study</th>
            <th>Route</th>
            <th>Status</th>
            <th>Actions</th>
        </tr>
    </thead>

    <tbody>
    <?php foreach ($pages as $page): ?>
        <tr>
            <td>
                <?php echo $this->escapeHtml($page->getTitle()) ?>
            </td>

            <td>
                <?php $studies = array(); ?>
                <?php foreach ($page->getStudies() as $study): ?>
                    <?php $studies[] = $study->getName() ?>
                <?php endforeach ?>
                <?= implode('<br>', $studies) ?>
            </td>

            <td>
                <a href="/<?php echo $this->escapeHtml($page->getRoute()) ?>">
                    <?php echo $this->escapeHtml($page->getRoute()) ?>
                </a>
            </td>

            <td>
                <?php echo $page->getStatus() ?>
            </td>

            <td>
                <a href="/pages/edit/<?php echo $page->getId() ?>">
                    Edit
                </a>
            </td>

        </tr>
    <?php endforeach ?>

    </tbody>
</table>
