<?php
$this->headScript()->appendFile(
    '/js/page.js?v=1',
    'text/javascript'
); ?>

<?php if ($this->isAllowed('adminMenu', 'view')): ?>
    <a href="<?= $this->url(
        'pages',
        array(
            'action' => 'edit',
            'id' => $page->getId()
        )
    ) ?>">
        Edit
    </a>
<?php endif ?>

<?php if ($page->getShowTitle()): ?>
    <?php $this->headTitle()->prepend($page->getTitle()) ?>
    <div class="page-header">
        <h2><?php echo $page->getTitle() ?></h2>

    </div>
<?php endif ?>

<?php if ($pageFromFile): ?>
    <?= $pageFromFile ?>
<?php else: ?>
    <?php if ($page->getShowWrapper()): ?>
        <div class="row cmsPage" id="page-<?= $wrapperId ?>">
            <div class="span12" id="cmsPageContent">
                <?= $page->getContent() ?>
            </div>
        </div>
    <?php else: ?>
        <?= $page->getContent() ?>
    <?php endif ?>
<?php endif ?>

