<?php if ($page->getShowTitle()): ?>
    <div class="page-header">
        <h2><?php echo $page->getTitle() ?></h2>

    </div>
<?php endif ?>

<?php if ($this->isAllowed('adminMenu', 'view')): ?>
    <a href="<?= $this->url(
        'pages',
        array(
            'action' => 'edit',
            'id' => $page->getId()
        )
    ) ?>">
        Edit
    </a>
<?php endif ?>


<?php if ($page->getShowWrapper()): ?>
    <div class="row cmsPage">
        <div class="span12" id="cmsPageContent">
            <?= $page->getContent() ?>
        </div>
    </div>
<?php else: ?>
    <?= $page->getContent() ?>
<?php endif ?>

