<?php /** @var \Mrss\Entity\Issue[] $issues */ ?>
<?php /** @var \Mrss\Form\IssueUserNote[] $forms */ ?>


<script>
    <?php $this->headScript()->captureStart() ?>

    var requireNote = <?= ($this->studyConfig()->validation_require_note) ? '1' : '0' ?>;

    $(function() {
        $('a.confirmData').click(function() {
            var issue = $(this).parents('.issue');

            //console.log(issue);

            if (requireNote) {
                // Hide the buttons
                issue.find('.issueButtons').hide();

                // Show the form
                issue.find('.userNote').show();
            } else {
                issue.find('form').submit();
            }

            return false;
        });

        // Cancel button
        $('.userNote .btn-danger').click(function() {
            var issue = $(this).parents('.issue');

            // Hide the form
            issue.find('.userNote').hide();

            // Show the buttons again
            issue.find('.issueButtons').show();

            return false;
        });
    })
    <?php $this->headScript()->captureEnd() ?>
</script>


<h1>Data Issues</h1>

<?php foreach ($issues as $issue): ?>
    <?php $form = $forms[$issue->getId()]; ?>
    <?php $form->setAttribute('action', '/issues/note'); ?>

    <div class="issue row">
        <div class="col-md-8 issue-message">
            <?= $issue->getMessage() ?>
        </div>

        <div class="col-md-4">
            <div class="issueButtons">
                <a href="/data-entry/<?= $issue->getFormUrl() ?>" class="btn btn-default">
                    <span class="icon-edit glyphicon glyphicon-edit"></span>
                    Go to Form <?= $issue->getFormUrl() ?>
                </a>

                <a href="#" class="btn btn-default confirmData">
                    <span class="icon-edit glyphicon glyphicon-ok"></span>
                    Confirm Data As Is
                </a>

            </div>

            <div class="userNote">
                <p>
                    Let us know why you're sure the data is correct.
                </p>

                <?= $this->ztbForm($form->prepare()) ?>
            </div>
        </div>

    </div>
<?php endforeach ?>

<?php if (empty($issues)): ?>
    <p>We have not found any issues with your data.  Great work!</p>
<?php endif ?>
