<?php /** @var \Mrss\Entity\Issue[] $issues */ ?>

<h1>Data Issues</h1>

<?php foreach ($issues as $issue): ?>
    <div class="issue row">
        <div class="col-md-9 issue-message">
            <?= $issue->getMessage() ?>
        </div>

        <div class="col-md-3">
            <a href="/data-entry/<?= $issue->getFormUrl() ?>" class="btn btn-default">
                <span class="icon-edit glyphicon glyphicon-edit"></span>
                Go to Form <?= $issue->getFormUrl() ?>
            </a>
        </div>

    </div>
<?php endforeach ?>

<?php if (empty($issues)): ?>
    <p>We haven't found any issues in your data. Great work!</p>
<?php endif ?>
