<h1>Academic Support Activities</h1>

<table class="table table-striped">
    <thead>
    <tr>
        <td></td>
        <th>Cost per FTE Student</th>
        <th>Cost per Student Contact</th>
        <th>FTE Students per Employee</th>
    </tr>
    </thead>
    <tbody>
        <?php foreach ($reportData as $row): ?>
            <tr>
                <th><?= $row['name'] ?></th>
                <?php foreach ($row['data'] as $value): ?>
                    <td><?= $value ?></td>
                <?php endforeach ?>
            </tr>
        <?php endforeach ?>
    </tbody>

</table>
