<?php
// Data Tables
$this->headScript()->appendFile(
    '/js/jquery.dataTables.min.js',
    'text/javascript'
);
$this->headLink()->appendStylesheet('/css/jquery.dataTables.min.css');

$this->headScript()->appendFile(
    '/js/report.js?v=4',
    'text/javascript'
); ?>


<h1>Academic Support Activities</h1>

<table class="table table-striped sortable">
    <thead>
    <tr>
        <td></td>
        <th class="numberCell">Cost per FTE Student</th>
        <th class="numberCell">Cost per Student Contact</th>
        <th class="numberCell">FTE Students per Employee</th>
    </tr>
    </thead>
    <tbody>
        <?php foreach ($reportData as $row): ?>
            <tr>
                <th><?= $row['name'] ?></th>
                <?php foreach ($row['data'] as $value): ?>
                    <td class="numberCell"><?= $value ?></td>
                <?php endforeach ?>
            </tr>
        <?php endforeach ?>
    </tbody>

</table>


<?php foreach ($charts as $chart): ?>
    <div class="internalChart">
        <?= $this->chart($chart) ?>
    </div>
<?php endforeach ?>
