<style>
    h2 {
        margin-top: 30px;
    }
</style>

<h1>Admin Outlier Report</h1>



<?php foreach ($report as $collegeInfo): ?>
    <?php
        /** @var \Mrss\Entity\College $college */
        $college = $collegeInfo['college'];

        /** @var \Mrss\Entity\Outlier[] $outliers */
        $outliers = $collegeInfo['outliers']
    ?>

    <h2><?= $college->getName() ?></h2>

    <?= $this->partial(
        'mrss/report/outliers.partial.phtml',
        array(
            'outliers' => $outliers,
            'admin' => true
        )
    ) ?>

<?php endforeach ?>
