
<h2>Admin Outlier Report</h2>

<? //pr($report) ?>

<?php foreach ($report as $collegeInfo): ?>
    <?php
        /** @var \Mrss\Entity\College $college */
        $college = $collegeInfo['college'];

        /** @var \Mrss\Entity\Outlier[] $outliers */
        $outliers = $collegeInfo['outliers']
    ?>

    <h3><?= $college->getName() ?></h3>

    <?= $this->partial(
        'mrss/report/outliers.partial.phtml',
        array(
            'outliers' => $outliers,
            'admin' => true
        )
    ) ?>

<?php endforeach ?>
