<?= $this->headLink()->appendStylesheet('/css/best-performers.css?v=3') ?>

<script type="text/javascript">
    <?php $this->headScript()->captureStart() ?>
    $(function() {

        // Show all
        $('#showAllBestPerformers').click(function() {
            showAllBestPerformers()
            return false;
        })

        // Show/hide benchmarks
        $('a.best-performers-form').click(function() {
            $(this).find('.glyphicon-plus').toggle()
            $(this).find('.glyphicon-minus').toggle()
            $(this).next().slideToggle()
            return false
        })

        // Fetch and show colleges
        $('.show-results').click(function() {
            var resultDiv = $(this).parent().parent().find('.results')

            // If the results are already loaded, hide them
            if (resultDiv.html().length) {
                resultDiv.html('')
            } else {
                var url = $(this).attr('href')

                resultDiv.html('Loading...')

                $.get(url, {}, function(data) {
                    resultDiv.html(data.colleges)
                })
            }



            return false
        })
    })

    function showAllBestPerformers()
    {
        $('a.best-performers-form').click()
        $('.show-results').click()

    }
    <?php $this->headScript()->captureEnd() ?>
</script>


<h1>Best Performers Report</h1>

<ul class="nav nav-pills report-nav">
    <?php foreach ($subscriptions as $subscription): ?>
        <?php if ($subscription->getYear() == $this->currentStudy()->getCurrentYear() && !$this->currentStudy()->getReportsOpen()) continue; ?>
        <li<? if ($subscription->getYear() == $year) echo ' class="active"' ?>>
            <a href="<?= $this->url('reports/best-performers', array('year' => $subscription->getYear())) ?>"><?= $subscription->getYear() ?></a>
        </li>
    <?php endforeach ?>
</ul>


<p><em>Best performers are institutions reporting data above 90th percentile (or below the 10th percentile for benchmarks like cost where lower values are better). Click a form name below to see its benchmarks, then click a benchmark to display the best performers. The institutions are presented in a alphabetical order.</em></p>

<div style="text-align: right">
    <a href="#" id="showAllBestPerformers">Show all</a>
</div>

<div id="best-performers">
    <?php foreach ($reportData as $benchmarkGroup): ?>
        <?php if (empty($benchmarkGroup['benchmarks'])) continue // Skip empty forms ?>


        <a href="#" class="best-performers-form">
            <span class="icon-plus-sign glyphicon glyphicon-plus"></span>
            <span class="icon-plus-sign glyphicon glyphicon-minus" style="display:none"></span>
            <h1><?= $benchmarkGroup['name'] ?></h1>
        </a>


        <div class="best-performers-benchmark-group">
        <?php foreach ($benchmarkGroup['benchmarks'] as $benchmarkId => $benchmarkLabel): ?>
            <div class="best-performers-benchmark">
                <h4>
                    <a href="/reports/best-performers-result/<?= $year ?>/<?= $benchmarkId ?>" class="show-results">
                        <?= $benchmarkLabel ?>
                    </a>
                </h4>

                <div class="results"></div>

            </div>
        <?php endforeach ?>
        </div>


    <?php endforeach ?>
    <br style="clear:both">
</div>

