<?php
$this->headScript()->appendFile(
    '/js/report-calculation.js?v=8',
    'text/javascript'
); ?>

<?php /** @var \Mrss\Entity\Study $study */ ?>
<script>
    <?php $this->headScript()->captureStart() ?>
    var benchmarks = {};

    <?php foreach ($years as $year => $calculationDates) {
        $benchmarkIdsForYear = array();
        /*foreach ($study->getBenchmarksForYear($year) as $benchmark) {
            $benchmarkIdsForYear[] = $benchmark->getId();
        }*/

        $benchmarkIdsForYear = $benchmarkIds[$year];


    ?>
        benchmarks[<?= $year ?>] = <?= json_encode($benchmarkIdsForYear) ?>;

    <?php } ?>

    var observations = <?= json_encode($observationIds) ?>;

    var systemIds = <?= json_encode($systemIds) ?>;


    // Show first tab
    $(document).ready(function(){
        $('.nav-tabs li a:first').tab('show');
    });
    <?php $this->headScript()->captureEnd() ?>
</script>
<style>
    h3 {
       margin-top: 25px;
    }
    .calculation-progress, .system-progress, .calculate-changes-progress, .calculate-changes-percentiles-progress {
        display: none;
    }
</style>

<h1>Calculate Reports</h1>

<ul class="nav nav-tabs" role="tablist">
    <?php foreach ($years as $year => $calculationDates): ?>
    <li role="presentation" class=""><a href="#tab<?= $year ?>" aria-controls="home" role="tab" data-toggle="tab"><?= $year ?></a></li>
    <?php endforeach ?>
</ul>


<div class="tab-content">

<?php foreach ($years as $year => $calculationDates): ?>
    <div role="tabpanel" class="tab-pane fade in" id="tab<?= $year ?>">
    <h2><?= $year ?></h2>

    <h3>Outlier Report</h3>
    <div class="row-fluid row">
        <div class="span6 col-md-4">
            <p>
                Calculate outlier and missing data.
            </p>

            <p>
                <a href="/admin/outliers">View Admin Outlier Report</a>
            </p>
        </div>

        <div class="span6 col-md-5" id="outlier-progress-<?= $year ?>">
            <div class="progress calculation-progress">
                <div class="bar progress-bar"
                     role="progressbar"
                     aria-valuenow="0"
                     aria-valuemin="0"
                     aria-valuemax="100"
                     style="width: 0%;"></div>
            </div>

        </div>

        <div class="col-md-1">
            <span class="progress-label"></span>
        </div>

        <div class="span6 col-md-2">
            <?php if (false): ?>
                <a class="btn btn-default" href="/reports/calculateOutliers/year/<?= $year ?>">Prepare Outlier Report</a>
            <?php else: ?>
                <a class="btn btn-default calculate-outliers" id="outlier-<?= $year ?>" href="#">Prepare Outlier Report</a>
            <?php endif ?>

            <br>
            <?php if (!empty($calculationDates['outliers'])): ?>
                Prepared on <?= $calculationDates['outliers'] ?>
                <br>
                <br>
                <a class="btn btn-default" href="/reports/emailOutliers/preview" >Preview Outlier Emails</a>
                <a class="btn btn-default" href="/reports/emailOutliers" onclick="return confirm('Are you sure you want to send outlier report emails to all member institutions?')">Send Outlier Emails</a>
            <?php else: ?>
                Not yet prepared.
            <?php endif ?>

        </div>
    </div>

    <h3>Compute Benchmarks</h3>
    <div class="row-fluid row">
        <div class="span6 col-md-4">
            <p>
                Run equations for computed benchmarks and store results.
            </p>

        </div>

        <div class="span6 col-md-5" id="compute-progress-<?= $year ?>">
            <div class="progress calculation-progress">
                <div class="bar progress-bar"
                     role="progressbar"
                     aria-valuenow="0"
                     aria-valuemin="0"
                     aria-valuemax="100"
                     style="width: 0%;"></div>
            </div>

        </div>

        <div class="col-md-1">
            <span class="progress-label"></span>
        </div>

        <div class="span6 col-md-2">
            <a class="btn btn-default calculate-compute" id="compute-<?= $year ?>" href="#">Compute Benchmarks</a>
            <br>
            <?php /* if (!empty($calculationDates['report'])): ?>
                Prepared on <?= $calculationDates['report'] ?>
            <?php else: ?>
                Not yet prepared.
            <?php endif */ ?>

        </div>
    </div>


    <h3>National Report</h3>
    <div class="row-fluid row">
        <div class="span4 col-md-4">
            <p>
                Calculate percentiles for National Report.
            </p>

            <p>
                <a href="/reports/national">View National Report</a>
            </p>
        </div>

        <div class="span5 col-md-5" id="percentile-progress-<?= $year ?>">
            <div class="progress calculation-progress">
                <div class="bar progress-bar"
                     role="progressbar"
                     aria-valuenow="0"
                     aria-valuemin="0"
                     aria-valuemax="100"
                     style="width: 0%;"></div>
            </div>

        </div>

        <div class="span1 col-md-1">
            <span class="progress-label"></span>
        </div>



        <div class="span6 col-md-2">
            <?php if (false): ?>
                <a class="btn btn-default" href="/reports/calculate/year/<?= $year ?>">Prepare National Report</a>
            <?php else: ?>
                <a class="btn btn-default calculate-percentile" href="#" id="calculate-percentile-<?= $year ?>">Prepare National Report</a>
            <?php endif ?>
            <br>
            <?php if (!empty($calculationDates['report'])): ?>
                Prepared on <?= $calculationDates['report'] ?>
            <?php else: ?>
                Not yet prepared.
            <?php endif ?>

        </div>
    </div>

    <h3>System Reports</h3>
    <div class="row-fluid row">
        <div class="span6 col-md-4">
            <p>
                Calculate percentiles for System Reports.
            </p>

        </div>

        <div class="span6 col-md-5" id="system-progress-<?= $year ?>">
            <div class="progress system-progress">
                <div class="bar progress-bar"
                     role="progressbar"
                     aria-valuenow="0"
                     aria-valuemin="0"
                     aria-valuemax="100"
                     style="width: 0%;"></div>
            </div>

        </div>

        <div class="col-md-1">
            <span class="progress-label"></span>
        </div>



        <div class="span6 col-md-2">
            <a class="btn btn-default calculate-systems" id="calculate-systems-<?= $year ?>" href="#<?php /*/reports/calculateSystems/year/<?= $year ?> */ ?>">Prepare System Reports</a>
            <br>
            <?php if (!empty($calculationDates['system'])): ?>
                Prepared on <?= $calculationDates['system'] ?>
            <?php else: ?>
                Not yet prepared.
            <?php endif ?>

        </div>
    </div>


    <h3>Percent Changes</h3>
    <div class="row-fluid row">
        <div class="span4 col-md-4">
            <p>
                For institutions that submitted data this year and last year, calculate the percent change for each benchmark.
            </p>

            <p>
                <a href="/reports/percent-changes/<?= $year ?>">View Percent Change Report</a>
            </p>

        </div>

        <div class="span5 col-md-5">
            <div class="progress calculate-changes-progress" id="calculate-changes-<?= $year ?>">
                <div class="bar progress-bar"
                     role="progressbar"
                     aria-valuenow="0"
                     aria-valuemin="0"
                     aria-valuemax="100"
                     style="width: 0%;"></div>
            </div>

        </div>

        <div class="span1 col-md-1">
            <span class="progress-label"></span>
        </div>

        <div class="span1 col-md-2">
            <a class="btn btn-default calculate-changes" href="#" id="calculate-changes-<?= $year ?>">Prepare Percent Changes</a>
        </div>
    </div>


    <h3>Percent Change Percentiles</h3>
    <div class="row-fluid row">
        <div class="span4 col-md-4">
            <p>
                Do percentile comparisons for all percent changes calculated in previous step. This will look like the national report, but be based on rates of change rather than raw data.
            </p>

        </div>

        <div class="span5 col-md-5">
            <div class="progress calculate-changes-percentiles-progress" id="calculate-changes-percentile-progress-<?= $year ?>">
                <div class="bar progress-bar"
                     role="progressbar"
                     aria-valuenow="0"
                     aria-valuemin="0"
                     aria-valuemax="100"
                     style="width: 0%;"></div>
            </div>

        </div>

        <div class="col-md-1">
            <span class="progress-label"></span>
        </div>

        <div class="span1 col-md-2">
            <a class="btn btn-default calculate-changes-percentiles" href="#" id="calculate-changes-percentiles-<?= $year ?>">Prepare Percent Change Percentiles</a>
        </div>
    </div>


        <hr>

    </div>

<?php endforeach ?>

</div>
