<script type="text/javascript">
    <?php $this->headScript()->captureStart() ?>
    $(function() {
        $('#list').select()
    })
    <?php $this->headScript()->captureEnd() ?>
</script>

<textarea id="list" cols="80" rows="100">
<?php foreach ($ipedsIds as $ipeds): ?>
<?///= $this->serverUrl($this->url('reports/executive-print', array('ipeds' => $ipeds))) . "\n" ?>
<?= $this->serverUrl('/reports/executive-print-admin/' . $ipeds) . "\n" ?>
<?php endforeach ?>
</textarea>
