<?= $this->headLink()->appendStylesheet('/css/executive-report.css') ?>
<?php /** @var \Mrss\Entity\College $college */ ?>
<?php /** @var \Mrss\Entity\Subscription[] $subscriptions */ ?>

<div id="executiveReport" class="page">
<?php if (empty($open)): ?>
    <h1>Executive Report</h1>
    <p>The 2015 Executive Report is not yet available.</p>
<?php else: ?>
    <ul class="nav nav-pills report-nav">
        <?php foreach ($subscriptions as $subscription): ?>
            <li<? if ($subscription->getYear() == $year) echo ' class="active"' ?>>
                <a href="<?= $this->url('reports/executive', array('year' => $subscription->getYear())) ?>"><?= $subscription->getYear() ?></a>
            </li>
        <?php endforeach ?>
    </ul>


    <div class="executiveReportHeader">
        <h2>Executive Report for <?= $college->getExecFullName() ?></h2>
        <h1><?= $college->getName() ?></h1>
    </div>

    <div class="executiveReportIntro">
        <h3>Key National Benchmarks – Where Does Your Institution Stand?</h3>

        <p>Your college participated in the National Community College Benchmark Project in <?= $year ?>.  This research is conducted annually by The National Higher Education Benchmarking Institute (NHEBI) at Johnson County Community College.  We would like to share some of the key results of this study with you. The report illustrates how your college compared to national data, representing 270 community colleges.</p>

        <p>The full NCCBP report, available online, contains more than 150 benchmarks on student demographics, measures of student success, faculty and staff data, workforce and community outreach, and institutional characteristics and effectiveness metrics.</p>

        <p>Member colleges use the benchmarks to support:
        </p><ul>
            <li>Strategic planning and selection of KPIs</li>
            <li>Accreditation</li>
            <li>Internal and external accountability activities</li>
            <li>Institutional transparency</li>
            <li>Documentation of student success</li>
        </ul>
        <p></p>

    </div>

    <?php foreach ($reportData['important'] as $importantChart): ?>

        <div class="complete-chart-box">
            <?= $this->chart($importantChart['chart']) ?>


            <?php if (!empty($importantChart['description'])): ?>
                <p><?= $importantChart['description'] ?></p>
            <?php endif ?>

        </div>
    <?php endforeach ?>

    <div class="executiveReportStrengths">
        <h3>Strengths</h3>
        <p>The following benchmarks are where your community college performed at its best. The benchmark is followed by the percent rank for your institution.</p>
        <ol class="executiveReportList"><li>
                % of Full-Time Students that Transferred in Three Years
                <div class="executiveReportRank">Your Rank - 89<sup>th</sup> Percentile</div>
            </li><li>
                % of Leavers and Non-Completers  that Achieved their Educational Goal
                <div class="executiveReportRank">Your Rank - 82<sup>nd</sup> Percentile</div>
            </li><li>
                Training Expenditures per FTE Employee
                <div class="executiveReportRank">Your Rank - 78<sup>th</sup> Percentile</div>
            </li><li>
                % of Part-Time Students that Transferred in Three Years
                <div class="executiveReportRank">Your Rank - 76<sup>th</sup> Percentile</div>
            </li>
        </ol>
    </div>

    <div class="executiveReportImprovements">
        <h3>Opportunities for Improvement</h3>
        <p>The following benchmarks are where your community college may need improvement. The benchmark is followed by the percent rank for your institution.</p>
        <ol class="executiveReportList"><li>
                % of Students that Received a Passing Grade in Writing Developmental/Remedial Courses of those that Completed the Course
                <div class="executiveReportRank">Your Rank - 11<sup>th</sup> Percentile</div>
            </li><li>
                % of Students that Completed a Reading Developmental/Remedial Courses of those that Enrolled in the Course
                <div class="executiveReportRank">Your Rank - 16<sup>th</sup> Percentile</div>
            </li><li>
                % of Full-Time Students that Completed in Three Years
                <div class="executiveReportRank">Your Rank - 20<sup>th</sup> Percentile</div>
            </li>
        </ol>
    </div>


    <div class="executiveReportPeerCallout">
        <h4>Next Steps – Peer Comparisons</h4>

        <p>The NCCBP On-Line Peer Comparison Tool allows you to compare your results to similar community colleges.  Please contact us if you would like assistance using this tool.</p>
    </div>

    
    <div class="executiveReportFooter">
        <div class="executiveReportMoreInfo">
            <h3>More Information</h3>
            <p>Thank you for being an NCCBP member. Find more information on the NCCBP by visiting our website <a href="http://nccbp.org">nccbp.org</a> or by calling or emailing the Benchmark Institute.</p>

            <p>Your research office will be able to provide additional benchmarks from the research, including peer comparisons.</p>

            <p>The full NCCBP report, available online, contains more than 150 benchmarks on student demographics, measures of student success, faculty and staff data, workforce and community outreach, and institutional characteristics and effectiveness metrics.</p>

            <p class="executiveReportLinkToThisPage">To view this report online, go to <a href="http://nccbp.org/report/executive">nccbp.org/report/executive</a> and log in.</p>

        </div>

        <div class="executiveReportDirector">
            <p class="directorName">
                Dr. Lou Guthrie, Director<br>
                National Higher Education<br>
                Benchmarking Institute
            </p>

            <p class="directorContact">
                Johnson County Community College<br>
                12345 College Blvd.<br>
                Overland Park, KS  66210<br>
                913-469-8500 Ext. 4019<br>
                E-mail: <a href="mailto:louguthrie@jccc.edu">louguthrie@jccc.edu</a>
            </p>
        </div>


    </div>

    <?php //pr($reportData) ?>
<?php endif ?>
</div>
