<?php
//$open = false;
//$media = 'screen,print';
$cssVersion = 13;
?>
<?php $this->headTitle()->prepend('Executive Report') ?>
<?php $this->headTitle()->prepend($college->getName()) ?>

<?= $this->headLink()->appendStylesheet('/css/executive-report.css?v=' . $cssVersion, 'screen,print') ?>
<?= $this->headLink()->appendStylesheet('/css/executive-report-print.css?v=' . $cssVersion, $media) ?>

<?= $this->headLink()->appendStylesheet('http://fonts.googleapis.com/css?family=Open+Sans:300italic,400,600,700', 'screen,print') ?>

<?php /** @var \Mrss\Entity\College $college */ ?>
<?php /** @var \Mrss\Entity\Subscription[] $subscriptions */ ?>

<div id="executiveReport" class="page">
<?php if (empty($open)): ?>
    <h1>Executive Report</h1>
    <p>The <?= $year ?> Executive Report is not yet available.</p>
<?php else: ?>
    <ul class="nav nav-pills report-nav">
        <?php foreach ($subscriptions as $subscription): ?>
            <?php if ($subscription->getYear() == $this->currentStudy()->getCurrentYear() && !$this->currentStudy()->getReportsOpen()) continue; ?>
            <li<? if ($subscription->getYear() == $year) echo ' class="active"' ?>>
                <a href="<?= $this->url('reports/executive', array('year' => $subscription->getYear())) ?>"><?= $subscription->getYear() ?></a>
            </li>
        <?php endforeach ?>
    </ul>


    <?php if (false && $year == 2017): ?>

        <p>
            The 2017 Executive Report will be produced in October.  It is mailed to the college president and made available here at that time.  Watch for an email announcing when it is ready.
        </p>

    <?php else: ?>



    <div id="printButton">
        <a class="btn btn-default" href="<?= $this->url('reports/executive-print', array('year' => $year)) ?>">
            <span class="glyphicon glyphicon-print"></span>
            Print
        </a>
    </div>

    <div class="executiveReportHeader">
        <h2>Executive Report for <?= $college->getExecFullName() ?></h2>
        <h1><?= $college->getName() ?></h1>
    </div>

    <div class="executiveReportIntro">
        <h3>Key National Benchmarks – Where Does Your Institution Stand?</h3>

        <?= $reportData['intro'] ?>

    </div>

    <?php foreach ($reportData['important'] as $importantChart): ?>

        <div class="complete-chart-box<?php if ($year >= 2017) echo ' tall' ?>">
            <?= $this->chart($importantChart['chart']) ?>


            <?php if (!empty($importantChart['description'])): ?>
                <p><?= $importantChart['description'] ?></p>
            <?php endif ?>

        </div>
    <?php endforeach ?>

    <div class="executiveReportStrengthsImprovements">
    <div class="executiveReportStrengths">
        <h3>Strengths</h3>
        <p>The following benchmarks are where your community college performed at its best. The benchmark is followed by the percent rank for your institution.</p>
        <?php //pr($reportData['strengths']) ?>
        <ol class="executiveReportList">
            <?
            // Make sure this section doesn't get too long
            $maxTotalLabelLength = 750;
            $totalLabelLength = 0;
            ?>

            <?php foreach ($reportData['strengths'] as $benchmark): ?>
                <?php
                $totalLabelLength += strlen($benchmark['name']) + 100;
                if ($totalLabelLength > $maxTotalLabelLength) {
                    continue;
                }
                ?>

            <li>
                <?= $benchmark['name'] ?>
                <div class="executiveReportRank">Your Rank - <?= $benchmark['rank'] ?> Percentile <?= $benchmark['append'] ?></div>
            </li>
            <?php endforeach ?>

        </ol>
    </div>

    <div class="executiveReportImprovements">
        <h3>Opportunities for Improvement</h3>
        <p>The following benchmarks are where your community college may need improvement. The benchmark is followed by the percent rank for your institution.</p>
        <ol class="executiveReportList">
            <?php
            $totalLabelLength = 0;
            ?>

            <?php foreach ($reportData['weaknesses'] as $benchmark): ?>
                <?php
                $totalLabelLength += strlen($benchmark['name']) + 100;
                if ($totalLabelLength > $maxTotalLabelLength) {
                    continue;
                }
                ?>

                <li>
                    <?= $benchmark['name'] ?>
                    <div class="executiveReportRank">Your Rank - <?= $benchmark['rank'] ?> Percentile <?= $benchmark['append'] ?></div>
                </li>
            <?php endforeach ?>

        </ol>
    </div>
    </div>

    <?php if ($year < 2017): ?>
    <div class="executiveReportPeerCallout">
        <h4>Next Steps &mdash; Peer Comparisons</h4>

        <p>The NCCBP On-Line Peer Comparison Tool allows you to compare your results to similar community colleges.  Please contact us if you would like assistance using this tool.</p>
    </div>
    <?php endif ?>


    <div class="executiveReportFooter">
        <div class="row">
            <div class="col-xs-12">

                    <h3>More Information</h3>
                    <?= $reportData['moreInfo'] ?>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-4">
                <p class="directorName">
                    Dr. Lou Guthrie, Director<br>
                    National Higher Education<br>
                    Benchmarking Institute
                </p>
            </div>

            <div class="col-xs-4">
                <p class="directorContact">
                    Johnson County Community College<br>
                    12345 College Blvd.<br>
                    Overland Park, KS  66210<br>
                    913-469-8500 Ext. 4019<br>
                    E-mail: <a href="mailto:louguthrie@jccc.edu">louguthrie@jccc.edu</a><br>
                    Twitter: <a href="http://twitter.com/EdBenchmark" target="_blank">@EdBenchmark</a>
                </p>
            </div>

            <div class="col-xs-2">
                <p class="instituteLogo">
                    <img src="/images/benchmark_logo_black.png" />
                </p>

            </div>
        </div>





    </div>

    <?php //pr($reportData) ?>
<?php endif ?>
</div>


<script type='text/javascript'>
    <?php $this->headScript()->captureStart() ?>
    function chartLoaded(event)
    {
        var lastChart = this
        fixupExecCharts()
    }

    function fixupExecCharts() {
    var zeros = [0, '0%', '0.00%', '$0']
    //$(function() {
        // Only show the first stack total label
        $('.highcharts-stack-labels text').hide();
        $('.highcharts-stack-labels text:first-child').show()

        // Handle not reported
        var ycLabel = $('.highcharts-stack-labels text:first-child');
        ycLabel.each(function() {
            var label = $(this);
            if (zeros.indexOf(label.text()) > -1) {
                label.text('Not Reported');
            }
        })

        // Handle not reported for non-stack charts
        var ycLabel = $('.highcharts-data-labels text:first-child');
        var parent;
        ycLabel.each(function() {
            label = $(this);
            if (zeros.indexOf(label.text()) > -1) {
                label.text('Not Reported');
                label.attr('x', -23);

                if (label.parent().parent().parent().parent().is(parent)) {
                    label.hide();
                }

                parent = label.parent().parent().parent().parent();
            }
        })

        // If a multibar is reported and its neighbor is not, just leave
        // the neighbor's label blank
        multiCharts = [
            'chart_w_comp_succ',
            'chart_fall_fall_pers'
        ];

        for (var i in multiCharts) {
            var multiChart = multiCharts[i]
            var labels = $('#' + multiChart + ' .highcharts-data-labels text:first-child tspan');

            values = [];
            labels.each(function() {
                values.push($(this).text());
            })

            if ((values[0] == 'Not Reported' && values[1] != 'Not Reported')) {
                $(labels[0]).hide()
            }
            if ((values[1] == 'Not Reported' && values[0] != 'Not Reported')) {
                $(labels[1]).hide()
            }

        }

        // bar stack label
        $('#chart_pt_perminus7_comp .highcharts-stack-labels text:first-child').attr('visibility', 'show')

        // Shrink completer success labels to avoid overlap
        $('#chart_w_comp_succ .highcharts-data-labels text')
            .css('font-size', '10px')
            .last().attr('x', '7')
        $('#chart_fall_fall_pers .highcharts-data-labels text')
            .css('font-size', '10px')
            .last().attr('x', '7')

        // Swap out the logo for a higher quality one for printing
        $('.logo img')
            //.attr('src', '/images/nccbp-logo-cmyk.svg')
            .attr('src', '/images/NCCBP-logo-c-nc.png')
            //.css('width', '300px')

    }
    <?php $this->headScript()->captureEnd() ?>
</script>

<?php if ($autoPrint): ?>
    <script>
        <?php $this->headScript()->captureStart() ?>
        $(function() {
            setTimeout(function() {window.print()}, 2000);
        });
        <?php $this->headScript()->captureEnd() ?>
    </script>
<?php endif ?>


<?php endif ?>
