<?php
//$open = false;
//$media = 'screen,print';
?>
<?php $this->headTitle()->prepend('Executive Report') ?>
<?php $this->headTitle()->prepend($college->getName()) ?>

<?= $this->headLink()->appendStylesheet('/css/executive-report.css?v=3', 'screen,print') ?>
<?= $this->headLink()->appendStylesheet('/css/executive-report-print.css?v=3', $media) ?>
<?= $this->headLink()->appendStylesheet('http://fonts.googleapis.com/css?family=Open+Sans:300italic,400,600,700', 'screen,print') ?>

<?php /** @var \Mrss\Entity\College $college */ ?>
<?php /** @var \Mrss\Entity\Subscription[] $subscriptions */ ?>

<div id="executiveReport" class="page">
<?php if (empty($open)): ?>
    <h1>Executive Report</h1>
    <p>The 2014 Executive Report is not yet available.</p>
<?php else: ?>
    <ul class="nav nav-pills report-nav">
        <?php foreach ($subscriptions as $subscription): ?>
            <li<? if ($subscription->getYear() == $year) echo ' class="active"' ?>>
                <a href="<?= $this->url('reports/executive', array('year' => $subscription->getYear())) ?>"><?= $subscription->getYear() ?></a>
            </li>
        <?php endforeach ?>
    </ul>


    <div class="executiveReportHeader">
        <h2>Executive Report for <?= $college->getExecFullName() ?></h2>
        <h1><?= $college->getName() ?></h1>
    </div>

    <div class="executiveReportIntro">
        <h3>Key National Benchmarks – Where Does Your Institution Stand?</h3>

        <p>Your college participated in the National Community College Benchmark Project in <?= $year ?>.  This research is conducted annually by The National Higher Education Benchmarking Institute (NHEBI) at Johnson County Community College.  We would like to share some of the key results of this study with you. The report illustrates how your college compared to national data, representing 270 community colleges.</p>

        <p>The full NCCBP report, available online, contains more than 150 benchmarks on student demographics, measures of student success, faculty and staff data, workforce and community outreach, and institutional characteristics and effectiveness metrics.</p>

        <p>Member colleges use the benchmarks to support:
        </p><ul>
            <li>Strategic planning and selection of KPIs</li>
            <li>Accreditation</li>
            <li>Internal and external accountability activities</li>
            <li>Institutional transparency</li>
            <li>Documentation of student success</li>
        </ul>
        <p></p>

    </div>

    <?php foreach ($reportData['important'] as $importantChart): ?>

        <div class="complete-chart-box">
            <?= $this->chart($importantChart['chart']) ?>


            <?php if (!empty($importantChart['description'])): ?>
                <p><?= $importantChart['description'] ?></p>
            <?php endif ?>

        </div>
    <?php endforeach ?>

    <div class="executiveReportStrengths">
        <h3>Strengths</h3>
        <p>The following benchmarks are where your community college performed at its best. The benchmark is followed by the percent rank for your institution.</p>
        <?php //pr($reportData['strengths']) ?>
        <ol class="executiveReportList">
            <?
            // Make sure this section doesn't get too long
            $maxTotalLabelLength = 750;
            $totalLabelLength = 0;
            ?>

            <?php foreach ($reportData['strengths'] as $benchmark): ?>
                <?php
                $totalLabelLength += strlen($benchmark['name']) + 100;
                if ($totalLabelLength > $maxTotalLabelLength) {
                    continue;
                }
                ?>

            <li>
                <?= $benchmark['name'] ?>
                <div class="executiveReportRank">Your Rank - <?= $benchmark['rank'] ?> Percentile <?= $benchmark['append'] ?></div>
            </li>
            <?php endforeach ?>

        </ol>
    </div>

    <div class="executiveReportImprovements">
        <h3>Opportunities for Improvement</h3>
        <p>The following benchmarks are where your community college may need improvement. The benchmark is followed by the percent rank for your institution.</p>
        <ol class="executiveReportList">
            <?php
            $totalLabelLength = 0;
            ?>

            <?php foreach ($reportData['weaknesses'] as $benchmark): ?>
                <?php
                $totalLabelLength += strlen($benchmark['name']) + 100;
                if ($totalLabelLength > $maxTotalLabelLength) {
                    continue;
                }
                ?>

                <li>
                    <?= $benchmark['name'] ?>
                    <div class="executiveReportRank">Your Rank - <?= $benchmark['rank'] ?> Percentile <?= $benchmark['append'] ?></div>
                </li>
            <?php endforeach ?>

        </ol>
    </div>


    <div class="executiveReportPeerCallout">
        <h4>Next Steps &mdash; Peer Comparisons</h4>

        <p>The NCCBP On-Line Peer Comparison Tool allows you to compare your results to similar community colleges.  Please contact us if you would like assistance using this tool.</p>
    </div>


    <div class="executiveReportFooter">
        <div class="executiveReportMoreInfo">
            <h3>More Information</h3>
            <p>Thank you for being an NCCBP member. Find more information on the NCCBP by visiting our website <a href="http://nccbp.org">NCCBP.org</a> or by calling or emailing the Benchmark Institute.</p>

            <p>Your research office will be able to provide additional benchmarks from the research, including peer comparisons.</p>

            <p>The full NCCBP report, available online, contains more than 150 benchmarks on student demographics, measures of student success, faculty and staff data, workforce and community outreach, and institutional characteristics and effectiveness metrics.</p>

            <p class="executiveReportLinkToThisPage">To view this report online, go to <a href="http://nccbp.org/reports/executive">NCCBP.org/reports/executive</a> and log in.</p>

        </div>

        <div class="executiveReportDirector">
            <p class="directorName">
                Dr. Lou Guthrie, Director<br>
                National Higher Education<br>
                Benchmarking Institute
            </p>

            <p class="directorContact">
                Johnson County Community College<br>
                12345 College Blvd.<br>
                Overland Park, KS  66210<br>
                913-469-8500 Ext. 4019<br>
                E-mail: <a href="mailto:louguthrie@jccc.edu">louguthrie@jccc.edu</a>
            </p>

            <p class="instituteLogo">
                <img src="/images/benchmark_logo_black.png" />
            </p>

        </div>



    </div>

    <?php //pr($reportData) ?>
<?php endif ?>
</div>


<script type='text/javascript'>
    function chartLoaded(event)
    {
        var lastChart = this
        fixupExecCharts()
    }

    function fixupExecCharts() {
    var zeros = [0, '0%', '0.00%', '$0']
    //$(function() {
        // Only show the first stack total label
        $('.highcharts-stack-labels text').hide();
        $('.highcharts-stack-labels text:first-child').show()

        // Handle not reported
        var ycLabel = $('.highcharts-stack-labels text:first-child');
        ycLabel.each(function() {
            var label = $(this);
            if (zeros.indexOf(label.text()) > -1) {
                label.text('Not Reported');
            }
        })

        // Handle not reported for non-stack charts
        var ycLabel = $('.highcharts-data-labels text:first-child');
        var parent;
        ycLabel.each(function() {
            label = $(this);
            if (zeros.indexOf(label.text()) > -1) {
                label.text('Not Reported');
                label.attr('x', -23);

                if (label.parent().parent().parent().parent().is(parent)) {
                    label.hide();
                }

                parent = label.parent().parent().parent().parent();
            }
        })

        // If a multibar is reported and its neighbor is not, just leave
        // the neighbor's label blank
        multiCharts = [
            'chart_w_comp_succ',
            'chart_fall_fall_pers'
        ];

        for (var i in multiCharts) {
            var multiChart = multiCharts[i]
            var labels = $('#' + multiChart + ' .highcharts-data-labels text:first-child tspan');

            values = [];
            labels.each(function() {
                values.push($(this).text());
            })

            if ((values[0] == 'Not Reported' && values[1] != 'Not Reported')) {
                $(labels[0]).hide()
            }
            if ((values[1] == 'Not Reported' && values[0] != 'Not Reported')) {
                $(labels[1]).hide()
            }

        }

        // bar stack label
        $('#chart_pt_perminus7_comp .highcharts-stack-labels text:first-child').attr('visibility', 'show')

        // Shrink completer success labels to avoid overlap
        $('#chart_w_comp_succ .highcharts-data-labels text')
            .css('font-size', '10px')
            .last().attr('x', '7')
        $('#chart_fall_fall_pers .highcharts-data-labels text')
            .css('font-size', '10px')
            .last().attr('x', '7')


    }
    //})
</script>
