<style type="text/css">
    .explore form input, .explore form textarea {
        width: 90%
    }

    .explore .form-horizontal .control-label {
        width: 90%;
        text-align: center;
    }

    .explore .controls {
        clear: both;
    }
    select {
        width: 80%;
    }
</style>

<?php
$this->headLink()->appendStylesheet('/css/chosen.min.css');

$this->headScript()->appendFile(
    '/js/chosen.jquery.min.js?v=1',
    'text/javascript'
);

$this->headScript()->appendFile(
    '/js/explore.js?v=1',
    'text/javascript'
);

?>

<h2>Explore the Data</h2>

<?php
// Add an action and submit button to the form
$form->setAttribute('action', $this->url('reports/explore'));

?>

<div class="explore row row-fluid">
    <div class="span4 col-md-4">
        <?= $this->ztbForm($this->form->prepare()) ?>

        <ul class="savedCharts">
        <?php foreach ($charts as $savedChart): ?>
            <li><a href="#" onclick="return postChart(<?= $savedChart->getId() ?>)"><?= $savedChart->getName() ?></a></li>
            <script>
                savedCharts[<?= $savedChart->getId() ?>] = '<?= $savedChart->getConfig(0) ?>'
            </script>
        <?php endforeach ?>
        </ul>
    </div>

    <div class="span8 col-md-8">
        <div id="chart">
            <?= $this->chart($chart) ?>
        </div>
    </div>
</div>

