<?php
$this->headScript()->appendFile(
    '/js/report.js?v=4',
    'text/javascript'
);
// Data Tables
$this->headScript()->appendFile(
    '/js/jquery.dataTables.min.js',
    'text/javascript'
);
$this->headLink()->appendStylesheet('/css/jquery.dataTables.min.css');
?>

<h1>Academic Division Costs: Division Summaries</h1>


<table class="table sortable">
    <thead>
        <tr>
            <th></th>
            <th class="numberCell">Faculty Salary and Benefit Costs per FTE Student</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($reportData as $datum): ?>


        <tr>
            <th><?= $datum['label'] ?></th>
            <td class="numberCell"><?= $datum['value'] ?></td>
        </tr>
        <?php endforeach ?>
    </tbody>
</table>


<?= $this->chart($chart) ?>
