<?php
$this->headScript()->appendFile(
    '/js/report.js?v=4',
    'text/javascript'
);
// Data Tables
$this->headScript()->appendFile(
    '/js/jquery.dataTables.min.js',
    'text/javascript'
);
$this->headLink()->appendStylesheet('/css/jquery.dataTables.min.css');
?>

<h1>Academic Division Costs: Division Summaries</h1>


<table class="table table-striped sortable">
    <thead>
        <tr>
            <th></th>
            <?php foreach ($fields as $dbColumn => $label): ?>
            <th class="numberCell"><?= $label ?></th>
            <?php endforeach ?>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($reportData as $datum): ?>


        <tr>
            <th><?= $datum['label'] ?></th>
            <?php foreach ($fields as $dbColumn => $label): ?>
                <td class="numberCell"><?= $datum[$dbColumn] ?></td>
            <?php endforeach ?>
        </tr>
        <?php endforeach ?>
    </tbody>
</table>


<?= $this->chart($chart) ?>
