<h1>Instructional Activity Costs</h1>

<table class="table">
    <thead>
        <tr>
            <th></th>
            <th>Program Dev.</th>
            <th>Course Dev.</th>
            <th>Teaching</th>
            <th>Faculty Tutoring</th>
            <th>Faculty Advising</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($reportData as $reportRow): ?>
            <tr>
                <th><?= $reportRow[0] ?></th>
                <td><?= $reportRow[1] ?></td>
                <td><?= $reportRow[2] ?></td>
                <td><?= $reportRow[3] ?></td>
                <td><?= $reportRow[4] ?></td>
                <td><?= $reportRow[5] ?></td>
            </tr>
        <?php endforeach ?>
    </tbody>
</table>


<?php foreach ($charts as $chart): ?>
    <?= $this->chart($chart) ?>

<?php endforeach ?>
