<h1><?= $college->getName() ?> Institutional Reports</h1>

<p>
    <a href="/reports/all-institutional">View all reports on one page.</a>
</p>

<div class="institutionalReports">
    <h3><a href="/reports/instructional-costs">Instructional Costs</a> (Form 1)</h3>
<h3>Academic Division Costs (Form 2)</h3>
<h4><a href="/reports/division-summaries">Division Summaries</a></h4>
<h4><a href="/reports/activities-within-division">Comparing Activities Within a Division</a></h4>
<h4><a href="/reports/divisions-by-activity">Comparing Divisions by Activity</a></h4>
<h4><a href="/reports/division-salaries">Division Salaries</a></h4>

<h3><a href="/reports/student-services-costs">Student Services Costs</a> (Form 3)</h3>
<h3><a href="/reports/academic-support">Academic Support Activities</a> (Form 4)</h3>
</div>
