<h1><?= $college->getName() ?> Institutional Reports</h1>


<div class="institutionalReports">
    <h3><a href="/reports/institution-costs">Institutional Instruction Costs</a></h3>
<h3>Academic Division Costs</h3>
<h4><a href="/reports/instructional-costs">Division Summaries</a></h4>
<h4><a href="/reports/instructional-activity-costs">Comparing Activities Within a Division</a></h4>
<h4><a href="/reports/unit-costs">Comparing Divisions by Activity</a></h4>

<h3><a href="/reports/unit-demographics">Academic Division Salaries</a></h3>
<h3><a href="/reports/student-services-costs">Student Services Costs</a></h3>
<h3><a href="/reports/academic-support">Academic Support Activities</a></h3>
</div>
