<?= $this->headLink()->appendStylesheet('/css/report.css') ?>
<?php
$this->headScript()->appendFile(
    '/js/report.js?v=3',
    'text/javascript'
); ?>



<h1>Report of National Aggregate Data</h1>


<h3>Institutional Costs</h3>

<hr>





<h3>Instructional Activity Costs</h3>

<table class="table table-hover table-striped-manual">
    <thead>
    <tr class="topHeading">
        <th></th>
        <th colspan="2">Your Institution</th>
        <th colspan="7" class="nationalPercentiles"><?= $heading ?></th>
    </tr>
    <tr class="secondHeading">
        <th></th>
        <th>$/FTE Student</th>
        <th>% Rank</th>
        <th>N</th>
        <?php foreach ($breakpoints as $breakpoint): ?>
            <th><?= $breakpoint ?></th>
        <?php endforeach ?>
        <th><a href="#" class="btn btn-default showAllCharts" title="Display all charts"><i class="icon-signal glyphicon glyphicon-signal"></i></a></th>
    </tr>
    </thead>

    <tbody>
    <?php foreach ($reportData['instructional'] as $benchmark): ?>

        <?php $rowClass = $this->cycle(array('odd', 'even'))->next() ?>
        <?= $this->partial('mrss/report/percentile.row.phtml', array('rowClass' => $rowClass, 'benchmark' => $benchmark, 'topLevel' => true)) ?>


        <?php foreach ($benchmark['details'] as $detailBenchmark): ?>
            <?= $this->partial('mrss/report/percentile.row.phtml', array('rowClass' => 'reportDetailRow', 'benchmark' => $detailBenchmark)) ?>
        <?php endforeach ?>

    <?php endforeach ?>
    </tbody>
    <thead>
    <tr class="spacerRow">
        <td colspan="9"></td>
    </tr>
    </thead>
</table>
<hr>




<h3>Student Services Costs</h3>

<table class="table table-hover table-striped-manual">
    <thead>
    <tr class="topHeading">
        <th></th>
        <th colspan="2">Your Institution</th>
        <th colspan="7" class="nationalPercentiles"><?= $heading ?></th>
    </tr>
    <tr class="secondHeading">
        <th></th>
        <th>$/FTE Student</th>
        <th>% Rank</th>
        <th>N</th>
        <?php foreach ($breakpoints as $breakpoint): ?>
            <th><?= $breakpoint ?></th>
        <?php endforeach ?>
        <th><a href="#" class="btn btn-default showAllCharts" title="Display all charts"><i class="icon-signal glyphicon glyphicon-signal"></i></a></th>
    </tr>
    </thead>

    <tbody>
    <?php foreach ($reportData['studentServices'] as $benchmark): ?>

        <?php $rowClass = $this->cycle(array('odd', 'even'))->next() ?>
        <?= $this->partial('mrss/report/percentile.row.phtml', array('rowClass' => $rowClass, 'benchmark' => $benchmark, 'topLevel' => true)) ?>


        <?php foreach ($benchmark['details'] as $detailBenchmark): ?>
            <?= $this->partial('mrss/report/percentile.row.phtml', array('rowClass' => 'reportDetailRow', 'benchmark' => $detailBenchmark)) ?>
        <?php endforeach ?>

    <?php endforeach ?>
    </tbody>
    <thead>
    <tr class="spacerRow">
        <td colspan="9"></td>
    </tr>
    </thead>
</table>
<hr>


<h3>Academic Support Activities</h3>

<table class="table table-hover table-striped-manual">
    <thead>
    <tr class="topHeading">
        <th></th>
        <th colspan="2">Your Institution</th>
        <th colspan="7" class="nationalPercentiles"><?= $heading ?></th>
    </tr>
    <tr class="secondHeading">
        <th></th>
        <th>$/FTE Student<br>(Calculated Values)</th>
        <th>% Rank</th>
        <th>N</th>
        <?php foreach ($breakpoints as $breakpoint): ?>
            <th><?= $breakpoint ?></th>
        <?php endforeach ?>
        <th><a href="#" class="btn btn-default showAllCharts" title="Display all charts"><i class="icon-signal glyphicon glyphicon-signal"></i></a></th>
    </tr>
    </thead>

    <tbody>
    <?php foreach ($reportData['academicSupport'] as $benchmark): ?>
        <?php $rowClass = $this->cycle(array('odd', 'even'))->next() ?>
        <?= $this->partial('mrss/report/percentile.row.phtml', array('rowClass' => $rowClass, 'benchmark' => $benchmark, 'topLevel' => true)) ?>


        <?php foreach ($benchmark['details'] as $detailBenchmark): ?>
            <?= $this->partial('mrss/report/percentile.row.phtml', array('rowClass' => 'reportDetailRow', 'benchmark' => $detailBenchmark)) ?>
        <?php endforeach  ?>

    <?php endforeach ?>
    </tbody>
    <thead>
    <tr class="spacerRow">
        <td colspan="9"></td>
    </tr>
    </thead>
</table>
<hr>



<h3>Student Success</h3>


<hr>

<p class="footnote" id="bottom">
    - = % Rank cannot be reported on a zero.
</p>
