<?= $this->headLink()->appendStylesheet('/css/report.css') ?>
<?php
$this->headScript()->appendFile(
    '/js/report.js?v=3',
    'text/javascript'
); ?>


<div class="report">


<h1>Report of National Aggregate Data</h1>



<h3>Instructional Activity Costs</h3>

<?= $this->partial(
    'mrss/report/percentile.table.phtml',
    array(
        'heading' => $heading,
        'breakpoints' => $breakpoints,
        'reportData' => $reportData['instructional'],
        'valueColumnLabel' => '$/FTE Student'
    )
) ?>

<hr>




<h3>Student Services Costs</h3>

<?= $this->partial(
    'mrss/report/percentile.table.phtml',
    array(
        'heading' => $heading,
        'breakpoints' => $breakpoints,
        'reportData' => $reportData['studentServices'],
        'valueColumnLabel' => '$/FTE Student'
    )
) ?>
<hr>



<h3>Student Services Budget</h3>

<?= $this->partial(
    'mrss/report/percentile.table.phtml',
    array(
        'heading' => $heading,
        'breakpoints' => $breakpoints,
        'reportData' => $reportData['studentServicesPercentages'],
        'valueColumnLabel' => '% of Student<br>Services Budget'
    )
) ?>
<hr>



<h3>Academic Support Activities</h3>

<?= $this->partial(
    'mrss/report/percentile.table.phtml',
    array(
        'heading' => $heading,
        'breakpoints' => $breakpoints,
        'reportData' => $reportData['academicSupport'],
        'valueColumnLabel' => '$/FTE Student<br>(Calculated Values)'
    )
) ?>
<hr>



<h3>Student Success</h3>

<?= $this->partial(
    'mrss/report/percentile.table.phtml',
    array(
        'heading' => $heading,
        'breakpoints' => $breakpoints,
        'reportData' => $reportData['studentSuccess'],
        'valueColumnLabel' => 'Reported Value'
    )
) ?>

<hr>


<p class="footnote" id="bottom">
    - = % Rank cannot be reported on a zero.
</p>
</div>
