<?= $this->headLink()->appendStylesheet('/css/report.css') ?>
<?php
$this->headScript()->appendFile(
    '/js/report.js?v=3',
    'text/javascript'
); ?>



<h1>Report of National Aggregate Data</h1>


<h3>Student Services Costs</h3>

<table class="table table-hover table-striped-manual">
    <thead>
    <tr class="topHeading">
        <th></th>
        <th colspan="2">Your Institution</th>
        <th colspan="7" class="nationalPercentiles"><?= $heading ?></th>
    </tr>
    <tr class="secondHeading">
        <th></th>
        <th>Reported Value</th>
        <th>% Rank</th>
        <th>N</th>
        <?php foreach ($breakpoints as $breakpoint): ?>
            <th><?= $breakpoint ?></th>
        <?php endforeach ?>
        <th><a href="#" class="btn btn-default showAllCharts" title="Display all charts"><i class="icon-signal glyphicon glyphicon-signal"></i></a></th>
    </tr>
    </thead>

    <tbody>
    <?php foreach ($reportData['studentServices'] as $benchmark): ?>
        <?php /*if (!empty($benchmark['heading'])): ?>
            <tr class="retportSeparator"></tr>
            <tr class="reportSubHeading">
                <td colspan="10">
                    <?= $benchmark['name'] ?>
                </td>
            </tr>
            <?php continue ?>
        <?php endif; */ ?>

        <?php $rowClass = $this->cycle(array('odd', 'even'))->next() ?>
        <tr class="<?= $rowClass ?> topLevelBenchmark">
            <td class="benchmarkLabel">
                <a href="#" class="detailExpander">
                    <?= $benchmark['benchmark'] ?>
                </a>
                <?php if (!empty($benchmark['timeframe'])): ?>
                    <span class="timeframe">(<?= $benchmark['timeframe'] ?>)</span>
                <?php endif ?>
            </td>
            <?php if ($benchmark['reported'] !== null): ?>
                <td><?= $benchmark['prefix'] . number_format($benchmark['reported'], $benchmark['reported_decimal_places']) . $benchmark['suffix'] ?></td>
                <td class="percentileColor">
                    <?php if (!empty($benchmark['do_not_format_rank'])): ?>
                        <?= $benchmark['percentile_rank'] ?>
                    <?php else: ?>
                        <?= round($benchmark['percentile_rank']) ?>%
                    <?php endif ?>
                </td>
            <?php else: ?>
                <td>-</td>
                <td>-</td>
            <?php endif ?>
            <td><?= $benchmark['N'] ?></td>
            <?php foreach ($benchmark['percentiles'] as $percentile): ?>
                <td>
                    <?php if (!is_null($percentile)): ?>
                        <?= $benchmark['prefix'] . number_format($percentile, $benchmark['reported_decimal_places']) . $benchmark['suffix'] ?>
                    <?php endif ?>
                </td>
            <?php endforeach ?>
            <td><a href="#" class="btn btn-default openChart" title="Display chart"><i class="icon-signal glyphicon glyphicon-signal"></i></a></td>
        </tr>
        <tr class="nationalReportChart <?= $rowClass ?>" id="benchmark_<?= $benchmark['dbColumn'] ?>">
            <td></td>
            <td colspan="9">
                <?= $this->chart($benchmark['chart']) ?>

                <?php if (!empty($benchmark['description'])): ?>
                    <p class="nationalDataDefinition">
                        <?= $benchmark['description'] ?>
                    </p>
                <?php endif ?>
            </td>
        </tr>

        <?php foreach ($benchmark['details'] as $detailBenchmark): ?>
        <tr class="reportDetailRow">
            <td class="detailName">
                Detail: <?pr($detailBenchmark) ?>
            </td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <?php endforeach ?>

    <?php endforeach ?>
    </tbody>
    <thead>
    <tr class="spacerRow">
        <td colspan="9"></td>
    </tr>
    </thead>
</table>
<hr>



<p class="footnote" id="bottom">
    - = % Rank cannot be reported on a zero.
</p>
