<?php
$subHeadingColSpan = ($forPercentChange) ? 12 : 10;
$tableHeadingColSpan = ($forPercentChange) ? 4 : 2;
?>

<?= $this->headLink()->appendStylesheet('/css/report.css') ?>
<?php
$this->headScript()->appendFile(
    '/js/report.js?v=6',
    'text/javascript'
); ?>

<script>
    <?php $this->headScript()->captureStart() ?>
    $(document).ready(function(){
        $('.tooltipster').tooltipster({
            contentAsHTML: true,
        });
    });
    <?php $this->headScript()->captureEnd() ?>
</script>


<h1>
    <?php if ($forPercentChange): ?>
        Percent Change Report
    <?php elseif (empty($system)): ?>
        <?= $studyConfig->national_report_name ?>
    <?php else: ?>
        <?= $system->getName() ?> Report
    <?php endif ?>
</h1>

<ul class="nav nav-pills report-nav">
    <?php foreach ($subscriptions as $subscription): ?>
        <?php if ($subscription->getYear() == $this->currentStudy()->getCurrentYear() && !$this->currentStudy()->getReportsOpen()) continue; ?>
        <li<? if ($subscription->getYear() == $year) echo ' class="active"' ?>>
            <a href="<?= $this->url('reports/' . $reportPath, array('year' => $subscription->getYear())) ?>"><?= $subscription->getYear() ?></a>
        </li>
    <?php endforeach ?>
</ul>


<p>
    Prepared for <?= $college->getName() ?>
</p>


<p>
    <a href="<?= $this->url(
        'reports/' . $reportPath,
        array(
            'year' => $year,
            'format' => 'excel'
        )
    ) ?>" class="btn btn-default">
        <span class="glyphicon glyphicon-circle-arrow-down"></span>
        Download Report
    </a>

    <?php if (!$forPercentChange): ?>
    <a href="<?= $this->url(
        'institution/subscribed',
        array(
            'year' => $year
        )
    ) ?>" class="btn btn-default">
        <span class="glyphicon glyphicon-circle-arrow-down"></span>
        Download Members
    </a>
    <?php endif ?>
</p>



<div class="report">

    <?php foreach ($reportData as $benchmarkGroup): ?>
        <?php if (stristr($benchmarkGroup['benchmarkGroup'], '|')): ?>
            <?php list($formNumber, $formTitle) = explode(' | ', $benchmarkGroup['benchmarkGroup']) ?>
        <?php elseif (stristr($benchmarkGroup['benchmarkGroup'], ':')): ?>
            <?php $nameParts = explode(': ', $benchmarkGroup['benchmarkGroup']) ?>
            <?php $formNumber = array_shift($nameParts) ?>
            <?php $formTitle = implode(': ', $nameParts) ?>
        <?php else: ?>
            <?php $formTitle = $benchmarkGroup['benchmarkGroup'] ?>
        <?php endif ?>
        <h3 class="benchmarkGroupTitle" id="form_<?= $benchmarkGroup['url'] ?>">
            <span class="small-heading"><?= $formNumber ?></span><br>
            <?= $formTitle ?>
            <?php if (!empty($benchmarkGroup['timeframe'])): ?>
                <span class="timeframe">(<?= $benchmarkGroup['timeframe'] ?>)</span>
            <?php endif ?>

        </h3>

        <?php if (empty($system)) {
            $heading = 'National Percentiles';

            if ($this->currentStudy()->getId() == 4) {
                $heading = 'National Median Percentiles';
            }
        } else {
            $heading = 'System Percentiles';
        }?>

        <table class="table table-hover table-striped-manual">
            <thead>
                <tr class="topHeading">
                    <th></th>
                    <th colspan="<?= $tableHeadingColSpan ?>">
                        <?= $studyConfig->your_institution_label ?>
                    </th>
                    <th colspan="7" class="nationalPercentiles"><?= $heading ?></th>
                </tr>
                <tr class="secondHeading">
                    <th></th>
                    <?php if ($forPercentChange): ?>
                    <th><?= $year - 1 ?></th>
                    <th><?= $year ?></th>
                    <th>Percent<br>Change</th>
                    <?php else: ?>
                    <th>Reported Value</th>
                    <?php endif ?>


                    <th>% Rank</th>
                    <th>N</th>
                    <?php foreach ($breakpoints as $breakpoint): ?>
                    <th><?= $breakpoint ?></th>
                    <?php endforeach ?>
                    <th><a href="#" class="btn btn-default showAllCharts" title="Display all charts"><i class="icon-signal glyphicon glyphicon-signal"></i></a></th>
                </tr>
            </thead>

            <tbody>
                <?php foreach ($benchmarkGroup['benchmarks'] as $benchmark): ?>
                    <?php if (!empty($benchmark['heading'])): ?>
                        <tr class="retportSeparator"></tr>
                        <tr class="reportSubHeading">
                            <td colspan="<?= $subHeadingColSpan ?>">
                                <?= $benchmark['name'] ?>
                            </td>
                        </tr>
                        <?php continue ?>
                    <?php endif; ?>

                    <?php $rowClass = $this->cycle(array('odd', 'even'))->next() ?>
                    <tr class="<?= $rowClass ?>">
                        <td class="benchmarkLabel">
                            <?php if (!empty($benchmark['description'])): ?>
                                <span class="tooltipster" title="<?= addslashes($benchmark['description']) ?>">
                                    <?= $benchmark['benchmark'] ?>
                                </span>
                            <?php else: ?>
                                <?= $benchmark['benchmark'] ?>
                            <?php endif ?>


                            <?php if (!empty($benchmark['timeframe'])): ?>
                                <span class="timeframe">(<?= $benchmark['timeframe'] ?>)</span>
                            <?php endif ?>
                        </td>

                        <?php if ($forPercentChange): ?>
                            <?php if (!empty($benchmark['percentChange'])): ?>
                                <td>
                                    <?= $benchmark['oldValue'] ?>
                                </td>
                                <td>
                                    <?= $benchmark['newValue'] ?>
                                </td>
                                <td>
                                    <?= $benchmark['percentChange'] ?>
                                </td>
                                <td>
                                    <?= round($benchmark['percentile_rank']) ?>%
                                </td>
                                <?php $benchmark['prefix'] = ''; $benchmark['suffix'] = '%'; ?>
                            <?php else: ?>
                                <td>-</td>
                                <td>-</td>
                                <td>-</td>
                                <td>-</td>
                            <?php endif ?>

                        <?php else: ?>
                            <?php if ($benchmark['reported'] !== null): ?>
                                <?php if ($benchmark['reported_formatted']): ?>
                                    <td>
                                        <?= $benchmark['reported_formatted'] ?>
                                    </td>
                                <?php else: ?>
                                    <td>
                                        <?= $benchmark['prefix'] . number_format($benchmark['reported'], $benchmark['reported_decimal_places']) . $benchmark['suffix'] ?>
                                    </td>
                                 <?php endif ?>

                                <td class="percentileColor">
                                    <?php if (true || !empty($benchmark['do_not_format_rank'])): ?>
                                        <?= $benchmark['percentile_rank'] ?>
                                    <?php else: ?>
                                        <?= round($benchmark['percentile_rank']) ?>%
                                    <?php endif ?>
                                </td>
                            <?php else: ?>
                                <td>-</td>
                                <td>-</td>
                            <?php endif ?>
                        <?php endif ?>

                        <td>
                            <?= $benchmark['N'] ?>
                        </td>
                        <?php foreach ($benchmark['percentiles'] as $percentile): ?>
                        <td>
                            <?php if (!is_null($percentile)): ?>
                                <?= $benchmark['percentile_prefix'] . number_format($percentile, $benchmark['reported_decimal_places']) . $benchmark['percentile_suffix'] ?>
                            <?php endif ?>
                        </td>
                        <?php endforeach ?>
                        <td><a href="#" class="btn btn-default openChart" title="Display chart"><i class="icon-signal glyphicon glyphicon-signal"></i></a></td>
                    </tr>
                    <tr class="nationalReportChart <?= $rowClass ?>" id="benchmark_<?= $benchmark['dbColumn'] ?>">
                        <td></td>
                        <td colspan="9">

                            <?php if (!empty($benchmark['chart'])): ?>
                                <?= $this->chart($benchmark['chart']) ?>
                            <?php endif ?>

                            <?php if (!empty($benchmark['description'])): ?>
                            <p class="nationalDataDefinition">
                                <?= $benchmark['description'] ?>
                            </p>
                            <?php endif ?>
                        </td>
                    </tr>

                <?php endforeach ?>
            </tbody>
            <thead>
                <tr class="spacerRow">
                    <td colspan="9"></td>
                </tr>
            </thead>
        </table>
        <hr>
    <?php endforeach ?>


    <p class="footnote" id="bottom">
        - = % Rank cannot be reported on a zero.
    </p>
</div>
