<?= $this->headLink()->appendStylesheet('/css/report.css') ?>
<?php
$this->headScript()->appendFile(
    '/js/report.js',
    'text/javascript'
); ?>

<h2>Report of National Aggregate Data</h2>

<ul class="nav nav-tabs">
    <?php foreach ($subscriptions as $subscription): ?>
        <li<? if ($subscription->getYear() == $year) echo ' class="active"' ?>>
            <a href="<?= $this->url('reports/national', array('year' => $subscription->getYear())) ?>"><?= $subscription->getYear() ?></a>
        </li>
    <?php endforeach ?>
</ul>


<p>
    Prepared for <?= $college->getName() ?>
</p>

<p>
    <a href="<?= $this->url(
        'reports/national',
        array(
            'year' => $year,
            'format' => 'excel'
        )
    ) ?>" class="btn">Download</a>
</p>

<div class="report">
    <table class="table table-hover table-striped-manual">
    <?php foreach ($reportData as $benchmarkGroup): ?>

                <thead>
                    <tr class="topHeading">
                        <th class="benchmarkGroupTitle" rowspan="2"><h3><?= $benchmarkGroup['benchmarkGroup'] ?></h3></th>
                        <th colspan="2">Institution</th>
                        <th></th>
                        <th colspan="5">Percentiles</th>
                        <th></th>
                    </tr>
                    <tr class="secondHeading">
                        <th>Reported Value</th>
                        <th>% Rank</th>
                        <th>N</th>
                        <?php foreach ($breakpoints as $breakpoint): ?>
                        <th><?= $breakpoint ?></th>
                        <?php endforeach ?>
                        <th><a href="#" class="btn showAllCharts" title="Display all charts"><i class="icon-signal"></i></a></th>
                    </tr>
                </thead>

                <tbody>
                    <?php foreach ($benchmarkGroup['benchmarks'] as $benchmark): ?>
                        <?php $rowClass = $this->cycle(array('odd', 'even'))->next() ?>
                        <tr class="<?= $rowClass ?>">
                            <td class="benchmarkLabel"><?= $benchmark['benchmark'] ?></td>
                            <?php if ($benchmark['reported'] !== null): ?>
                            <td><?= $benchmark['prefix'] . number_format($benchmark['reported'], 0) . $benchmark['suffix'] ?></td>
                            <td class="percentileColor">
                                <?php if ($benchmark['percentile_rank'] == '-'): ?>
                                    <?= $benchmark['percentile_rank'] ?>
                                <?php else: ?>
                                    <?= round($benchmark['percentile_rank']) ?>
                                <?php endif ?>
                            </td>
                            <?php else: ?>
                                <td></td>
                                <td></td>
                            <?php endif ?>
                            <td><?= $benchmark['N'] ?></td>
                            <?php foreach ($benchmark['percentiles'] as $percentile): ?>
                            <td><?= $benchmark['prefix'] . number_format($percentile, 0) . $benchmark['suffix'] ?></td>
                            <?php endforeach ?>
                            <td><a href="#" class="btn openChart" title="Display chart"><i class="icon-signal"></i></a></td>
                        </tr>
                        <tr class="nationalReportChart <?= $rowClass ?>">
                            <td></td>
                            <td colspan="9"><?= $this->chart($benchmark['chart']) ?></td>
                        </tr>

                    <?php endforeach ?>
                </tbody>
                <thead>
                    <tr class="spacerRow">
                        <td colspan="9"></td>
                    </tr>
                </thead>



    <?php endforeach ?>
    </table>

    <p class="footnote">
        - = % Rank cannot be reported on a zero.
    </p>
</div>
