<?php
$this->headScript()->appendFile(
    '/js/report-outlier.js?v=3',
    'text/javascript'
); ?>

<h2>Outlier Report</h2>

<p>
    As a final check of <?= $year ?> <?= $studyName ?> data, we have identified values to the data elements listed below that are unusually large or small relative to mean values in the data set.  We have defined these outliers fairly conservatively and have included values that are more than two standard deviations above or below aggregate means.<br>
</p>

<p>
    Some data elements in the outlier report are collected in the data entry form.  Others are calculated from multiple raw data elements. For  calculated benchmarks, you will find a list of source benchmarks from which they are derived in the second column of the report.  This includes the value you entered and a link to edit that value. Click "Show equation" to see the formula.
</p>
<p>
    We understand that the reported values may be correct, but we would appreciate it if you would either confirm the values or provide corrected raw data. Additionally, you may revise any data even if it is not flagged as an outlier or add additional data during the data verification process.
</p>

<?php foreach ($report as $collegeInfo): ?>
    <?php
    /** @var \Mrss\Entity\College $college */
    $college = $collegeInfo['college'];

    /** @var \Mrss\Entity\Outlier[] $outliers */
    $outliers = $collegeInfo['outliers']
    ?>

    <h4><?= $college->getName() ?></h4>

    <?= $this->partial(
        'mrss/report/outliers.partial.phtml',
        array(
            'outliers' => $outliers,
            'admin' => false
        )
    ) ?>

<?php endforeach ?>
