Dear AAUP Faculty Compensation Survey Participant:<br>
<br>
As a final check of 2016 AAUP Faculty Compensation Survey data, the AAUP Research Office conducted an outlier analysis designed to identify values that are more than two standard deviations above or below aggregate means.<br>
<br>
Your submission did not include any outliers.<br>
<br>
Please take a moment to review one final time and if you need to make a correction, please enter the updated data online at the website, https://research.aaup.org. Please email jbarnshaw@aaup.org by close of business March 2, to let me know that you have made a change.  If you have not made a change, no further action is required on your part.  Please note that you will not be able to correct values past this deadline for the March/April submission.<br>
<br>
Please let me know if I can clarify this process or assist you in any way. Thank you for helping us assure that AAUP Faculty Compensation Survey data are as accurate as possible.<br>
<br>
You can also find this report on the web at https://research.aaup.org/reports/outlier<br>
<br>
No outliers.<br>
<br>
<br>
Thanks,<br>
<br>
John<br>
<br>
John Barnshaw, Ph.D.<br>
Senior Program Officer<br>
Senior Higher Education Researcher<br>
American Association of University Professors<br>
1133 19th Street Northwest – Suite 221<br>
Washington, DC, USA 20036<br>
202.737.5900 x3627<br>
jbarnshaw@aaup.org<br>

