Dear AAUP Faculty Compensation Survey Participant:<br>
<br>
As a final check of 2016 AAUP Faculty Compensation Survey data, we have identified values to the data elements listed below that are unusually large or small relative to mean values in the data set. We have defined these outliers fairly conservatively and have included values that are more than two standard deviations above or below aggregate means.<br>
<br>
We understand that the reported values may be correct, but we would appreciate it if you would either confirm the values or provide corrected raw data. Additionally, you may revise any data even if it is not flagged as an outlier or add additional data during the data verification process.<br>
<br>
Some data elements are collected in the data entry form and others are calculated from other elements. For calculated benchmarks, you will find a list of source benchmarks from which they are derived, including the value you entered and a link to edit that value. The formula below the source benchmarks shows how the value is calculated.<br>
<br>
To make a correction, please enter the updated data online at the website, https://research.aaup.org. Please email jbarnshaw@aaup.org by close of business March 2, to let me know that your data is final even if you make no changes. Please note that you will not be able to correct values past this deadline.<br>
<br>
Please let me know if I can clarify this process or assist you in any way. Thank you for helping us assure that AAUP Faculty Compensation Survey data are as accurate as possible.<br>
<br>
You can also find this report on the web at <a href="https://research.aaup.org/reports/outlier">https://research.aaup.org/reports/outlier</a><br>
<br>
<?= $this->partial(
    'mrss/report/outliers.partial.phtml',
    array(
        'outliers' => $outliers
    )
); ?><br>
<br>
<br>
Thanks,<br>
<br>
John<br>
<br>
John Barnshaw, Ph.D.<br>
Senior Program Officer<br>
Senior Higher Education Researcher<br>
American Association of University Professors<br>
1133 19th Street Northwest – Suite 221<br>
Washington, DC, USA 20036<br>
202.737.5900 x3627<br>
jbarnshaw@aaup.org<br>





