<?php /** @var \Mrss\Entity\Outlier[] $outliers */ ?>
<?php /** @var boolean $admin */ ?>
<?php
$tdStyle = "padding: 5px; border: 1px solid #DDD; ";
$thStyle = "$tdStyle background: #DDD; color: #000";
$tStyle = "border: 1px solid #DDD; border-collapse: collapse;";
?>

<style>
    .sourceHeading {
        width: 50%;
    }
</style>

<?php if (count($outliers)): ?>
    <table class="00table 00table-bordered outliers" style="<?= $tStyle ?>">
        <thead>
        <tr>
            <th style="<?= $thStyle ?>">Benchmark</th>
            <?php if (!empty($showDetails)): ?>
                <th style="<?= $thStyle ?>" class="sourceHeading">Source Benchmarks</th>
            <?php endif ?>
            <th style="<?= $thStyle ?>">Value</th>
            <th style="<?= $thStyle ?>">Problem</th>
            <?php if (empty($admin)): ?>
                <th style="<?= $thStyle ?>">Action</th>
            <?php endif ?>
        </tr>
        </thead>
        <tbody>

        <?php foreach ($outliers as $outlier): ?>
            <tr>
                <td style="<?= $tdStyle ?>">
                    <strong><?= $outlier['benchmark'] ?></strong>
                </td>

                <?php if (!empty($showDetails)): ?>

                    <td style="<?= $tdStyle ?>">
                        <?php if ($outlier['computed']): ?>
                            <table class="00table 00table-bordered" style="<?= $tStyle ?>">
                                <tbody>
                                <?php foreach ($outlier['baseBenchmarks'] as $baseBenchmark): ?>
                                    <tr>
                                        <td style="<?= $tdStyle ?>"><?= $baseBenchmark['benchmark'] ?></td>
                                        <td style="<?= $tdStyle ?> text-align:right"><?= $baseBenchmark['value'] ?></td>

                                        <?php if (empty($admin)): ?>
                                            <?php
                                            $url = $this->url(
                                                'data-entry/edit',
                                                array(
                                                    'benchmarkGroup' => $baseBenchmark['benchmarkGroup']
                                                ),
                                                array('force_canonical' => true)
                                            );

                                            $url .= '#' . $baseBenchmark['dbColumn'];
                                            ?>

                                            <td style="min-width: 92px; <?= $tdStyle ?>">
                                            <?php if (!$system): ?>
                                                <a class="underline" href="<?= $url ?>">Edit Form <?= $baseBenchmark['benchmarkGroup'] ?></a>
                                            <?php endif ?>
                                            </td>

                                        <?php endif ?>
                                    </tr>
                                <?php endforeach ?>
                                </tbody>
                            </table>

                            <a href="#" class="showOutlierEquation" style="display:none">Show formula</a>
                            <div class="outlierEquation">
                                <?= $outlier['equation'] ?>
                            </div>

                        <?php endif ?>
                    </td>

                <?php endif ?>

                <td class="text-right" style="<?= $tdStyle ?> text-align: right">
                    <?= $outlier['value'] ?>
                </td>
                <td style="<?= $tdStyle ?>">
                    <?= $outlier['problem'] ?>
                </td>

                <?php if (empty($admin)): ?>
                    <td style="<?= $tdStyle ?>">
                        <?php if (!$outlier['computed']): ?>
                            <?php
                            $url = $this->url(
                                'data-entry/edit',
                                array(
                                    'benchmarkGroup' => $outlier['benchmarkGroupId']
                                ),
                                array('force_canonical' => true)
                            );

                            $url .= '#' . $outlier['dbColumn'];
                            ?>
                            <?php if (!$system): ?>
                            <a href="<?= $url ?>">Edit Form <?= $outlier['benchmarkGroupId'] ?></a>
                            <?php endif ?>
                        <?php endif ?>
                    </td>
                <?php endif ?>
            </tr>

        <?php endforeach ?>

        </tbody>
    </table>

<?php else: ?>
    No outliers.
<?php endif ?>
