Dear <?= $studyName ?> Member:<br>
<br>
As a final check of <?= $year ?> <?= $studyName ?> data, we have identified values to the data elements that are unusually large or small relative to mean values in the data set.  Your college had no data elements that were in this range, therefore no corrections to your data are required.<br>
<br>
<?= $replyToName ?><br>
<?= $replyTo ?><br>
<?= $replyToPhone ?>
