Dear <?= $studyName ?> Member:<br>
<br>
As a final check of <?= $year ?> <?= $studyName ?> data, we have identified values to the data elements listed below that are unusually large or small relative to mean values in the data set.  We have defined these outliers fairly conservatively and have included values that are more than two standard deviations above or below aggregate means.<br>
<br>
We understand that the reported values may be correct, but we would appreciate it if you would either confirm the values or provide corrected raw data.<br>
<br>
To make a correction, please enter the updated data online at the website, <?= $url ?>.  Please email <?= $replyTo ?> before <?= $deadline ?>, to let me know that your data is final even if you make no changes. Please note that you will not be able to correct values past this deadline.<br>
<br>
Please let me know if I can clarify this process or assist you in any way.  Thank you for helping us assure that Workforce Training Benchmark Project data are as accurate as possible.<br>
<br>
<?= $this->partial(
    'mrss/report/outliers.partial.phtml',
    array(
        'outliers' => $outliers
    )
); ?><br>
<br>
<?= $replyToName ?><br>
<?= $replyTo ?><br>
<?= $replyToPhone ?>
