Dear AAUP Faculty Compensation Survey Participant:<br>
<br>
As a final check of 2016-2017 AAUP Faculty Compensation Survey data, AAUP Research and Public Policy conducted an outlier analysis designed to identify values that are more than two standard deviations above or below aggregate means.  This report does not mean that any error has necessarily occurred with your data, but that your data are simply out of a statistical range on a particular metric.
<br>
<br>
For some institutions, your data may be higher (e.g. Highly Selective Private Urban Doctoral Institution), or lower (e.g. Small, Private Liberal Arts College in the Midwest) than your institutional grouping because of regional or institutional variation, and thus, it does not necessarily mean that an input error has occurred.  However, last year, hundreds of errors were caught and corrected as a result of this process.  <br>
<br>
Please take a moment to review one final time and if you need to make a correction, please enter the updated data online at the website, <a href="https://research.aaup.org">https://research.aaup.org</a>. Please email <a href="mailto:aaupfcs@aaup.org">aaupfcs@aaup.org</a>  by close of business Monday, February 27, to let us know that you have made a change. If you have not made a change, no further action is required on your part. Please note that you will not be able to correct values past this deadline for the March/April submission.
<br>
<br>
Please let me know if I can clarify this process or assist you in any way. Thank you for helping us assure that AAUP Faculty Compensation Survey data are as accurate as possible.
<br>
<br>
You can also find this report on the web at <a href="https://research.aaup.org/reports/outlier">https://research.aaup.org/reports/outlier</a> <br>
<br>
For additional information, please visit:<br>
<a href="https://research.aaup.org/faq">https://research.aaup.org/faq</a><br>
<a href="https://research.aaup.org/instructions">https://research.aaup.org/instructions</a>
<br>
<br>
<?= $this->partial(
    'mrss/report/outliers.partial.phtml',
    array(
        'outliers' => $outliers
    )
); ?><br>
<br>
<br>
Regards,<br>
<br>
John<br>
<br>
John Barnshaw, Ph.D.<br>
Director<br>
jbarnshaw@aaup.org<br>
<br>
<br>
Samuel J. Dunietz<br>
Senior Program Officer, Research & Policy Analyst<br>
sdunietz@aaup.org




