<?php /** @var \Mrss\Entity\Outlier[] $outliers */ ?>
<?php /** @var boolean $admin */ ?>

<?php if (count($outliers)): ?>
    <table class="table table-bordered outliers">
        <thead>
            <tr>
                <th>Benchmark</th>
                <th>Source Benchmarks</th>
                <th>Value</th>
                <th>Problem</th>
                <?php if (empty($admin)): ?>
                <th>Action</th>
                <?php endif ?>
            </tr>
        </thead>
        <tbody>

        <?php foreach ($outliers as $outlier): ?>
            <tr>
                <td>
                    <strong><?= $outlier['benchmark'] ?></strong>
                </td>
                <td>
                    <?php if ($outlier['computed']): ?>
                        <table class="table table-bordered">
                            <tbody>
                                <?php foreach ($outlier['baseBenchmarks'] as $baseBenchmark): ?>
                                <tr>
                                    <td><?= $baseBenchmark['benchmark'] ?></td>
                                    <td style="text-align:right"><?= $baseBenchmark['value'] ?></td>

                                    <?php if (empty($admin)): ?>
                                        <?php
                                        $url = $this->url(
                                            'data-entry/edit',
                                            array(
                                                'benchmarkGroup' => $baseBenchmark['benchmarkGroup']
                                            ),
                                            array('force_canonical' => true)
                                        );

                                        $url .= '#' . $baseBenchmark['dbColumn'];
                                        ?>

                                        <td><a href="<?= $url ?>">Edit</a></td>

                                    <?php endif ?>
                                </tr>
                                <?php endforeach ?>
                            </tbody>
                        </table>

                        <a href="#" class="showOutlierEquation" style="display:none">Show forumula</a>
                        <div class="outlierEquation">
                            <?= $outlier['equation'] ?>
                        </div>

                    <?php endif ?>
                </td>
                <td class="text-right">
                    <?= $outlier['value'] ?>
                </td>
                <td>
                    <?= $outlier['problem'] ?>
                </td>

                <?php if (empty($admin)): ?>
                    <td>
                        <?php if (!$outlier['computed']): ?>
                        <?php
                            $url = $this->url(
                                'data-entry/edit',
                                array(
                                    'benchmarkGroup' => $outlier['benchmarkGroupId']
                                ),
                                array('force_canonical' => true)
                            );

                            $url .= '#' . $outlier['dbColumn'];
                        ?>
                        <a href="<?= $url ?>">Edit</a>
                        <?php endif ?>
                    </td>
                <?php endif ?>
            </tr>

        <?php endforeach ?>

        </tbody>
    </table>

<?php else: ?>
    No outliers.
<?php endif ?>
