
<h1>Demographic Peer Comparison</h1>

<script>
    $(function() {
        $('.formClearButton').click(function() {
            var form = $(this).parents('form')
            form.find('select, input').each(function(i, e) {
                if ($(e).attr('type') != 'submit') {
                    $(e).val('')
                }

            })

            return false
        })

        // Fix css issues that I couldn't fix below:
        $('#fieldset-buttons .controls').css('margin-left', 0)
        $('#control-group-submitButton').css('margin-left', '160px')
    })
</script>

<style type="text/css">
    #fieldset-buttons .control-group {
        width: 15%;
        float: left;
    }

    #fieldset-buttons label {
        display: none;
    }
</style>


<?php
// Add an action and submit button to the form
$form->setAttribute('action', $this->url('reports/peer-demographic'));

?>

<?= $this->ztbForm($this->form->prepare()) ?>
