<?php /** @var \Mrss\Entity\PeerGroup $peerGroup */ ?>

<?= $this->headLink()->appendStylesheet('/css/peer-comparison.css?v=2') ?>

<?php
$this->headLink()->appendStylesheet('/css/chosen.min.css');

$this->headScript()->appendFile(
    '/js/chosen.jquery.min.js?v=1',
    'text/javascript'
);

$this->headScript()->appendFile(
    '/js/peer-comparison.js?v=3',
    'text/javascript'
);

?>

<script type="text/javascript">
    var peerGroups = <?= $peerGroups ?>
</script>

<h1>Peer Comparison</h1>

<?php
// Add an action and submit button to the form
$form->setAttribute('action', $this->url('reports/peer'));
?>

<?php if (!empty($peerGroup)): ?>
    <div class="well">
        <h4>Demographic Criteria</h4>
        <p>
            <a href="<?= $this->url('reports/peer-demographic') ?>">Change</a>
        </p>

        <?php if (!empty($criteria)): ?>

            <?php foreach ($criteria as $label => $value): ?>
                <p>
                    <strong><?= $label ?>:</strong>
                    <?= $value ?>
                </p>


            <?php endforeach ?>

        <?php else: ?>
            <p>None selected</p>
        <?php endif ?>
    </div>

<?php endif ?>

<?= $this->ztbForm($this->form->prepare()) ?>
