<tr class="<?= $rowClass ?><?php if (!empty($topLevel)) echo ' topLevelBenchmark' ?>">
    <td class="benchmarkLabel">
        <a href="#" class="detailExpander">
            <?= $benchmark['benchmark'] ?>
        </a>
        <?php if (!empty($benchmark['timeframe'])): ?>
            <span class="timeframe">(<?= $benchmark['timeframe'] ?>)</span>
        <?php endif ?>

            <?php //pr($benchmark) ?>

    </td>
    <?php if ($benchmark['reported'] !== null): ?>
        <td><?= $benchmark['prefix'] . number_format($benchmark['reported'], $benchmark['reported_decimal_places']) . $benchmark['suffix'] ?></td>
        <td class="percentileColor">
            <?php if (!empty($benchmark['do_not_format_rank'])): ?>
                <?= $benchmark['percentile_rank'] ?>
            <?php else: ?>
                <?= round($benchmark['percentile_rank']) ?>%
            <?php endif ?>
        </td>
    <?php else: ?>
        <td>-</td>
        <td>-</td>
    <?php endif ?>
    <td><?= $benchmark['N'] ?></td>
    <?php foreach ($benchmark['percentiles'] as $percentile): ?>
        <td>
            <?php if (!is_null($percentile)): ?>
                <?= $benchmark['prefix'] . number_format($percentile, $benchmark['reported_decimal_places']) . $benchmark['suffix'] ?>
            <?php endif ?>
        </td>
    <?php endforeach ?>
    <td><a href="#" class="btn btn-default openChart" title="Display chart"><i class="icon-signal glyphicon glyphicon-signal"></i></a></td>
</tr>
<tr class="nationalReportChart <?= $rowClass ?>" id="benchmark_<?= $benchmark['dbColumn'] ?>">
    <td></td>
    <td colspan="9">
        <?= $this->chart($benchmark['chart']) ?>

        <?php if (!empty($benchmark['description'])): ?>
            <p class="nationalDataDefinition">
                <?= $benchmark['description'] ?>
            </p>
        <?php endif ?>
    </td>
</tr>
