<h1>Strengths Report</h1>

<ul class="nav nav-pills report-nav">
    <?php foreach ($subscriptions as $subscription): ?>
        <?php if ($subscription->getYear() == $this->currentStudy()->getCurrentYear() && !$this->currentStudy()->getReportsOpen()) continue; ?>
        <li<? if ($subscription->getYear() == $year) echo ' class="active"' ?>>
            <a href="<?= $this->url('reports/best-performers', array('year' => $subscription->getYear())) ?>"><?= $subscription->getYear() ?></a>
        </li>
    <?php endforeach ?>
</ul>


<p><em>Report description goes here.</em></p>


<div id="report-strengths">
    <? pr($strengths) ?>
</div>
