<?php
$this->headScript()->appendFile(
    '/js/report.js?v=3',
    'text/javascript'
); ?>

<h1>Student Services Costs</h1>

<table class="table table-striped studentServices">
    <thead>
        <tr>
            <td></td>
            <th class="numberCell">Cost per FTE Student</th>
            <th class="numberCell">Cost per Student Contact</th>
            <th class="numberCell">FTE Students per Employee</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($reportData as $row): ?>
        <tr>
            <?php foreach ($row as $key => $item): ?>
                <?php if ($key == 'name' && $item != 'N/A'): ?>
                    <th><?= $item ?></th>
                <?php else: ?>

                    <td class="numberCell"><?= $item ?></td>
                <?php endif ?>
            <?php endforeach ?>
        </tr>
    <?php endforeach ?>
    </tbody>
</table>

<?php foreach ($charts as $chart): ?>
    <div class="internalChart">
        <?= $this->chart($chart) ?>
    </div>
<?php endforeach ?>
