<?= $this->headLink()->appendStylesheet('/css/report-summary.css') ?>
<?= $this->headLink()->appendStylesheet('/css/report-summary-print.css', $printMedia) ?>

<p class="print-friendly-link">
    <a href="<?= $this->url('reports/summary-print', array('year' => $year)) ?>">Print-friendly version</a>
</p>

<h2>Key Benchmark Report</h2>

<p>
    Prepared for <?= $college->getName() ?>
</p>

<?php foreach ($reportData as $section): ?>
    <h3><?= $section['name'] ?></h3>

    <div class="summarySection clearfix">
        <?php foreach ($section['charts'] as $chart): ?>
            <div class="summaryChart">
                <?= $this->chart($chart['chart']) ?>

                <?php if (!empty($chart['description'])): ?>
                <p>
                    <?= $chart['description'] ?>
                </p>
                <?php endif ?>
            </div>
        <?php endforeach ?>
    </div>
<?php endforeach ?>
