<?= $this->headLink()->appendStylesheet('/css/report-summary.css') ?>

<h2>Key Benchmark Report</h2>

<p>
    Prepared for <?= $college->getName() ?>
</p>

<?php foreach ($reportData as $section): ?>
    <div class="summarySection clearfix">
        <h3><?= $section['name'] ?></h3>

        <?php foreach ($section['charts'] as $chart): ?>
            <div class="summaryChart">
                <?= $this->chart($chart['chart']) ?>

                <?php if (!empty($chart['description'])): ?>
                <p>
                    <?= $chart['description'] ?>
                </p>
                <?php endif ?>
            </div>
        <?php endforeach ?>
    </div>
<?php endforeach ?>
