<h1>Academic Unit Demographics</h1>

<table class="table table-striped">
    <thead>
    <tr>
        <th></th>
        <?php foreach ($headings as $heading): ?>
            <th><?= $heading ?></th>
        <?php endforeach ?>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($reportData as $unit): ?>
        <tr>
            <th><?= $unit['unit'] ?></th>
            <?php foreach ($unit['data'] as $datum): ?>
                <td><?= $datum ?></td>
            <?php endforeach ?>
        </tr>
    <?php endforeach ?>
    </tbody>
</table>
