<?php
// Data Tables
$this->headScript()->appendFile(
    '/js/jquery.dataTables.min.js',
    'text/javascript'
);
$this->headLink()->appendStylesheet('/css/jquery.dataTables.min.css');

$this->headScript()->appendFile(
    '/js/report.js?v=4',
    'text/javascript'
); ?>

<h1>Academic Division Costs: Comparing Divisions by Activity</h1>

<ul>
    <?php foreach ($reportData as $activityKey => $activity): ?>
        <li>
            <a href="#activity_<?= $activityKey ?>"><?= $activity['name'] ?></a>
        </li>
    <?php endforeach ?>
</ul>

<?php foreach ($reportData as $activityKey => $activity): ?>
    <div class="unit-cost-activity" id="activity_<?= $activityKey ?>">
        <h2><?= $activity['name'] ?></h2>

        <table class="table table-striped sortable">
            <thead>
                <tr>
                    <th></th>
                    <th class="numberCell">% of Time Full-time Faculty Spend on <?= $activity['name'] ?></th>
                    <th class="numberCell">FT Faculty<br>Salary and Benefits<br>per FTE Student</th>
                    <th class="numberCell">% of Time Part-time Faculty Spend on <?= $activity['name'] ?></th>
                    <th class="numberCell">PT Faculty<br>Salary and Benefits<br>per FTE Student</th>
                    <th class="numberCell">Total Faculty<br>Salary and Benefits<br>per FTE Student</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($activity['units'] as $unitName => $unitData): ?>
                    <tr>
                        <th><?= $unitName ?></th>
                        <td class="numberCell"><?= $unitData['inst_cost_full_' . $activityKey] ?></td>
                        <td class="numberCell"><?= $unitData['inst_cost_full_per_cred_hr_' . $activityKey] ?></td>
                        <td class="numberCell"><?= $unitData['inst_cost_part_'  . $activityKey] ?></td>
                        <td class="numberCell"><?= $unitData['inst_cost_part_per_cred_hr_' . $activityKey] ?></td>
                        <td class="numberCell"><?= $unitData['inst_cost_total_per_cred_hr_' . $activityKey] ?></td>
                    </tr>
                <?php endforeach ?>
            </tbody>
        </table>

        <?= $this->chart($activity['chart']) ?>

    </div>

<?php endforeach ?>

<?php if (empty($reportData)): ?>

    <p>There is no data available for this report. Please enter data in form 2.</p>
<?php endif ?>

