<h1>Academic Unit Instructional Costs</h1>

<?php foreach ($reportData as $activityKey => $activity): ?>
    <div id="actvity_<?= $activityKey ?>">
        <h2><?= $activity['name'] ?></h2>

        <table class="table table-striped">
            <thead>
                <tr>
                    <th></th>
                    <th>% Full-time Faculty</th>
                    <th>FT $/FTE Students</th>
                    <th>% Part-time Faculty</th>
                    <th>PT $/FTE Students</th>
                    <th>Total $/FTE Students</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($activity['units'] as $unitName => $unitData): ?>
                    <tr>
                        <th><?= $unitName ?></th>
                        <td><?= $unitData['inst_cost_full_perc'] ?></td>
                        <td><?= $unitData['inst_cost_full_per_cred_hr_' . $activityKey] ?></td>
                        <td><?= $unitData['inst_cost_part_perc'] ?></td>
                        <td><?= $unitData['inst_cost_part_per_cred_hr_' . $activityKey] ?></td>
                        <td><?= $unitData['inst_cost_total_per_cred_hr_' . $activityKey] ?></td>
                    </tr>
                <?php endforeach ?>
            </tbody>
        </table>

    </div>

<?php endforeach ?>

