<?php
/**
 * This is a special data-entry template that displays this form as a table
 */

$tableConfig = array(
    'Instructional Technology Support' => array(
        'as_tech_total',
        'as_tech_o_cost',
        'as_tech_emp',
        'as_tech_student',
        'as_tech_contract',
    ),
    'Library Services' => array(
        'as_library_total',
        'as_library_o_cost',
        'as_library_emp',
        '',
        'as_library_contract',
    ),
    'Experiential Education' => array(
        'as_experiential_total',
        'as_experiential_o_cost',
        'as_experiential_emp',
        'as_experiential_student',
        'as_experiential_contract',
    ),
);

$colClassConfig = array(
    'expenditures',
    'cost',
    'fte_num',
    'students_served',
    'contract'
);

?>

<?= $this->headLink()->appendStylesheet('/css/data-entry-grid.css') ?>

<?php
$this->headScript()->appendFile(
    '/js/data-entry.js',
    'text/javascript'
); ?>

<?= $this->systemAdmin() ?>

<h2>
    <?= $benchmarkGroup->getName() ?>
</h2>

<?php if ($description = $benchmarkGroup->getDescription()): ?>
    <div class="well">
        <?= $description ?>
    </div>
<?php endif ?>


<?php $form->prepare() ?>
<?= $this->form()->openTag($form) ?>

<table class="table table-condensed table-bordered data-entry-grid">
    <thead>
    <tr>
        <th></th>
        <th>Salaries and Benefits</th>
        <th>Non-labor Operating Costs</th>
        <th>Number of FTE Employees</th>
        <th>Number of Service Contacts</th>
        <th>Contract</th>
    </tr>
    </thead>

    <tbody>

    <?php foreach ($tableConfig as $label => $row): ?>
        <tr>
            <td class="grid-category">
                <?= $label ?>
            </td>

            <?php foreach ($row as $i => $field): ?>
                <?php if (!empty($field)): ?>
                    <td class="grid-value <?= $colClassConfig[$i] ?>-value"
                        id="<?= $colClassConfig[$i] ?>-<?= $field ?>">
                        <?= $this->simpleFormElement($form->get($field)) ?>
                    </td>
                <?php else: ?>
                    <td></td>
                <?php endif ?>
            <?php endforeach ?>

        </tr>

        <tr class="help-text">
            <td class="grid-category"></td>
            <td colspan="<?= count($row) ?>">

                <?php foreach ($row as $i => $field): ?>
                    <?php if (empty($field)) continue ?>
                    <div class="<?= $colClassConfig[$i] ?>-help">
                        <?= $form->get($field)->getOption('help-block') ?>
                    </div>
                <?php endforeach ?>

            </td>
        </tr>
    <?php endforeach ?>

    </tbody>
</table>

<fieldset id="fieldset-buttons" class="well well-small">
    <div class="control-group" id="control-group-buttons[submit]">
        <div class="controls" id="controls-buttons[submit]">
            <?= $this->formElement($form->get('buttons')->get('submit')) ?>
        </div>
    </div>
</fieldset>

<?= $this->form()->closeTag() ?>
