<?php /** @var \Mrss\Entity\BenchmarkGroup $benchmarkGroup */ ?>
<?php /** @var \Mrss\Entity\BenchmarkGroup[] $benchmarkGroups */ ?>


<?= $this->headLink()->appendStylesheet('/css/data-entry.css?v=6') ?>

<?php
$this->headScript()->appendFile(
    '/js/data-entry.js?v=12',
    'text/javascript'
); ?>


<?= $this->partial(
    'mrss/observation/data-entry-nav.partial.phtml',
    array(
        'benchmarkGroup' => $benchmarkGroup,
        'benchmarkGroups' => $benchmarkGroups
    )
)
?>

<div class="row">
    <div class="col-md-9 span9">
        <h1>
            <?= $benchmarkGroup->getName() ?>
        </h1>
    </div>
    <div class="col-md-3 span3">
        <?= $this->ztbForm($dataDefinitionForm->prepare()) ?>
    </div>
</div>



<?php if ($description = $benchmarkGroup->getDescription()): ?>
<div class="well">
    <?= $variable->substitute($description) ?>
</div>
<?php endif ?>

<?//= $this->ztbForm($form->prepare()) ?>


<?php $form->prepare() ?>
<?= $this->form()->openTag($form) ?>


<?php foreach ($benchmarkGroup->getChildren($this->currentStudy()->getCurrentYear(), false) as $benchmark): ?>
    <?php if (get_class($benchmark) == 'Mrss\Entity\BenchmarkHeading'): ?>

        <h3 class="heading"><?= $variable->substitute($benchmark->getName()) ?></h3>

        <?php if ($desc = $benchmark->getDescription()): ?>
            <p class="subheading-description">
                <?= $variable->substitute($desc) ?>
            </p>
        <?php endif ?>

    <?php else: ?>
        <?php if (!is_object($benchmark)): ?>
            <?php pr($benchmark); ?>
        <?php endif ?>
        <?= $this->ztbFormElement($form->get($benchmark->getDbColumn())) ?>
    <?php endif ?>

<?php endforeach ?>

<?php if ($this->currentStudy()->getDataEntryOpen()): ?>
    <fieldset id="fieldset-buttons" class="well well-small">
        <div class="control-group" id="control-group-buttons[submit]">
            <div class="controls" id="controls-buttons[submit]">
                <?= $this->formElement($form->get('buttons')->get('submit')) ?>
            </div>
        </div>
        <div class="control-group" id="control-group-buttons[save-edit]">
            <div class="controls" id="controls-buttons[save-edit]">
                <?= $this->formElement($form->get('buttons')->get('save-edit')) ?>
            </div>
        </div>
    </fieldset>
<?php endif ?>

<?= $this->form()->closeTag() ?>

