<?= $this->headLink()->appendStylesheet('/css/data-entry.css') ?>

<?php
$this->headScript()->appendFile(
    '/js/data-entry.js',
    'text/javascript'
); ?>

<h1>
    <?= $benchmarkGroup->getName() ?>
</h1>

<?php if ($description = $benchmarkGroup->getDescription()): ?>
<div class="well">
    <?= $description ?>
</div>
<?php endif ?>

<?//= $this->ztbForm($form->prepare()) ?>


<?php $form->prepare() ?>
<?= $this->form()->openTag($form) ?>


<?php foreach ($benchmarkGroup->getChildren($this->currentStudy()->getCurrentYear(), false) as $benchmark): ?>
    <?php if (get_class($benchmark) == 'Mrss\Entity\BenchmarkHeading'): ?>

        <h3><?= $variable->substitute($benchmark->getName()) ?></h3>

        <?php if ($desc = $benchmark->getDescription()): ?>
            <p>
                <?= $variable->substitute($desc) ?>
            </p>
        <?php endif ?>

    <?php else: ?>
        <?= $this->ztbFormElement($form->get($benchmark->getDbColumn())) ?>
    <?php endif ?>

<?php endforeach ?>

<?php if ($this->currentStudy()->getDataEntryOpen()): ?>
    <fieldset id="fieldset-buttons" class="well well-small">
        <div class="control-group" id="control-group-buttons[submit]">
            <div class="controls" id="controls-buttons[submit]">
                <?= $this->formElement($form->get('buttons')->get('submit')) ?>
            </div>
        </div>
    </fieldset>
<?php endif ?>

<?= $this->form()->closeTag() ?>

