<?= $this->headLink()->appendStylesheet('/css/data-entry.css') ?>

<?php
$this->headScript()->appendFile(
    '/js/data-entry.js',
    'text/javascript'
); ?>

<?= $this->systemAdmin() ?>

<h3>
    <?= $benchmarkGroup->getName() ?>
</h3>

<?php if ($description = $benchmarkGroup->getDescription()): ?>
<div class="well">
    <?= $description ?>
</div>
<?php endif ?>

<?= $this->ztbForm($form->prepare()) ?>

