
<?php if ($this->studyConfig()->prior_year_edits && $canEditPrior): ?>
    <ul class="nav nav-pills form-nav">
        <li class="form-nav-head">
            <h3>
                Year:
            </h3>
        </li>

        <?php foreach ($years as $listYear): ?>
            <? $params = array (
                'year' => $listYear
            );

            if (empty($route)) {
                $route = 'data-entry';
            }

            if (!empty($benchmarkGroup)) {
                $params['benchmarkGroup'] = $benchmarkGroup->getUrl();
                $route = 'data-entry/edit';
            }

            ?>

            <li<? if ($listYear == $year) echo ' class="active"' ?>>
                <a href="<?= $this->url(
                    $route,
                    $params
                ) ?>" title="<?= $listYear ?>" class="infotip">
                    <?= $listYear ?>
                </a>
            </li>
        <?php endforeach ?>
    </ul>
<?php endif ?>
