<?php
$this->headScript()->appendFile(
    '/js/data-entry-import.js',
    'text/javascript'
); ?>

<style>
    #fieldset-submit, #download {
        width: 450px;
    }
</style>


<?php if (!empty($errorMessages)): ?>
    <div class="well">
        <h2>Invalid Data</h2>

        <?php foreach ($errorMessages as $collegeMessage): ?>

            <h5><?= $collegeMessage['college'] ?></h5>
            <ul class="excelImportFailedMessages">
                <? foreach ($collegeMessage['errors'] as $field => $message): ?>

                    <li>
                        <strong><?= $field ?>:</strong>
                        <?= $message ?>
                    </li>
                <?php endforeach ?>
            </ul>
        <?php endforeach ?>
    </div>

<?php endif ?>

<?php
$url = $this->url('data-entry/export');
$directLink  = 'http://www.aaup.org/file/AAUP%20Faculty%20Compensation%20Survey%20-%202015-2016%20-%20Final_0.xlsx';
$downloadId = 'download';
$downloadNote = "<strong>Note:</strong> This file can take several minutes to download because it is being pre-populated with your data. If you encounter problems downloading the pre-populated file, please try downloading the blank template <a href='$directLink'>here</a>.";

if ($useDirectDownloadLink) {
    $url = $directLink;
    $downloadId = 'download-direct';
    $downloadNote = '';
}

?>

<h2>Download Excel File</h2>

<p>
    <strong>Step 1:</strong>
    If you prefer collecting your data in an Excel spreadsheet, download this file.<br>

    <strong>Step 2:</strong> Save the Excel spreadsheet to your computer. You should work exclusively on the website OR the Excel file.<br />

    <?php if ($downloadNote): ?>
        <?= $downloadNote ?><br>
    <?php endif ?>

</p>
<p>
    <div class="form-horizontal" id="<?= $downloadId ?>">
    <div class="controls">
        <a class="btn btn-primary" href="<?= $url ?>">Download</a>
    </div>
    </div>
</p>
<br>

<?php if ($this->currentStudy()->getDataEntryOpen()): ?>
<h2>Upload Excel File</h2>
<p>
    <strong>Step 1:</strong> Complete the Excel file <?php if ($this->currentStudy()->getId() == 2): ?>including all the Form 2 pages (tabs) for your divisions<?php endif ?>.<br>
    <strong>Step 2:</strong> Warning – Uploading the Excel file will overwrite any information you have entered on the website. Copy any information you have entered on the website into your Excel file and save.<br>
    <strong>Step 3:</strong>  Upload the updated file using the form below. Please allow for up to three minutes to complete. If there are any errors, they will be shown on the next screen.
</p>

<?= $this->ztbForm($this->form->prepare()) ?>

<?php endif ?>
