<?php if (!empty($errorMessages)): ?>
    <div class="well">
        <h2>Invalid Data</h2>

        <?php foreach ($errorMessages as $collegeMessage): ?>

            <h5><?= $collegeMessage['college'] ?></h5>
            <ul class="excelImportFailedMessages">
                <? foreach ($collegeMessage['errors'] as $field => $message): ?>

                    <li>
                        <strong><?= $field ?>:</strong>
                        <?= $message ?>
                    </li>
                <?php endforeach ?>
            </ul>
        <?php endforeach ?>
    </div>

<?php endif ?>

<h2>Import Data</h2>

<p><strong>Warning: If you have entered data in the web data collection instrument that is not contained in the excel form uploading the form to the website will overwrite the data on the web data collection instrument with the contents of the excel document including missing data.</strong></p>

<p>
    <strong>Step 1:</strong>
    <a href="<?= $this->url('data-entry/export') ?>">Export your current data as an
    Excel file</a>. Data definitions are included.<br />

    <strong>Step 2:</strong> Save the Excel file to your computer. Stop making any changes to the web data collection instrument until you have uploaded the Excel file to the website. Add your data to the Excel file on your computer.<br />

    <strong>Step 3:</strong> Upload the updated file using the form below. If there
    are any errors, the import will not be saved and the errors will be shown on the
    next screen.
</p>

<?= $this->ztbForm($this->form->prepare()) ?>
