<?php
/**
 * This is a special data-entry template that displays this form as a table
 */

$tableConfig = array(
    'Full-time' => array(
        'inst_full_total_expend',
        'inst_full_total_num',
    ),
    'Part-time' => array(
        'inst_part_total_expend',
        'inst_part_total_num',
    ),
    'Other Full-time' => array(
        'inst_other_total_expend',
        'inst_other_total_num',
    ),
);

$colClassConfig = array('expenditures', 'count');

?>

<?= $this->headLink()->appendStylesheet('/css/data-entry-grid.css') ?>

<?php
$this->headScript()->appendFile(
    '/js/data-entry.js',
    'text/javascript'
); ?>

<?= $this->systemAdmin() ?>

<h2>
    <?= $benchmarkGroup->getName() ?>
</h2>

<?php if ($description = $benchmarkGroup->getDescription()): ?>
    <div class="well">
        <?= $description ?>
    </div>
<?php endif ?>


<?php $form->prepare() ?>
<?= $this->form()->openTag($form) ?>

<table class="table table-condensed table-bordered data-entry-grid">
    <thead>
    <tr>
        <th>Instruction</th>
        <th>Total Expenditures<br>for Instructional Faculty</th>
        <th>Number of Faculty</th>
    </tr>
    </thead>

    <tbody>

    <?php foreach ($tableConfig as $label => $row): ?>
        <tr>
            <td class="grid-category">
                <?= $label ?>
            </td>

            <?php foreach ($row as $i => $field): ?>
                <td class="grid-value <?= $colClassConfig[$i] ?>-value"
                    id="<?= $colClassConfig[$i] ?>-<?= $field ?>">
                    <?= $this->simpleFormElement($form->get($field)) ?>
                </td>
            <?php endforeach ?>
        </tr>

        <tr class="help-text">
            <td class="grid-category"></td>
            <td colspan="<?= count($row) ?>">

                <?php foreach ($row as $i => $field): ?>
                    <div class="<?= $colClassConfig[$i] ?>-help">
                        <?= $form->get($field)->getOption('help-block') ?>
                    </div>
                <?php endforeach ?>

            </td>
        </tr>
    <?php endforeach ?>

    </tbody>
</table>

<fieldset id="fieldset-buttons" class="well well-small">
    <div class="control-group" id="control-group-buttons[submit]">
        <div class="controls" id="controls-buttons[submit]">
            <?= $this->formElement($form->get('buttons')->get('submit')) ?>
        </div>
    </div>
</fieldset>

<?= $this->form()->closeTag() ?>
