<?php
/**
 * This is a special data-entry template that displays this form as a table
 */

$tableConfig = array(
    // Faculty
    array(
        'title' => 'Faculty Categories',
        'rowClass' => 'grid-subcategory',
        'rows' => array(
            'Full-Time' => array(
                'inst_full_expend',
                'inst_full_num',
                'inst_full_cred_hrs'
            ),
            'Part-Time or Adjunct' => array(
                'inst_part_expend',
                'inst_part_num',
                'inst_part_cred_hrs'
            ),
        ),
    ),
    array(
        'rows' => array(
            'Executive Staff' => array(
                'inst_exec_expend',
                'inst_exec_num',
                ''
            ),
            'Clerical and Other Professional Staff' => array(
                'inst_admin_expend',
                'inst_admin_num',
                ''
            ),
            'Non-Labor Operating Costs' => array(
                'inst_o_cost',
                '',
                ''
            )
        )
    )
);

$colClassConfig = array('expenditures', 'count', 'credit_hours');

?>

<?= $this->headLink()->appendStylesheet('/css/data-entry-grid.css') ?>

<?php
$this->headScript()->appendFile(
    '/js/data-entry.js',
    'text/javascript'
); ?>

<?= $this->systemAdmin() ?>

<h3>
    <?= $benchmarkGroup->getName() ?>
</h3>

<?php if ($description = $benchmarkGroup->getDescription()): ?>
    <div class="well">
        <?= $description ?>
    </div>
<?php endif ?>


<?php $form->prepare() ?>


<?= $this->form()->openTag($form) ?>

<table class="table table-condensed table-bordered data-entry-grid" id="instructionalGrid">
    <thead>
    <tr>
        <th></th>
        <th>Salaries and Benefits</th>
        <th>
            Number of Annual<br>FTE Faculty / Staff
            <span class="icon-info-sign infotip" title="FTE: Full-time equivalent"></span>
        </th>
        <th>Number of Academic Year<br>Student Credit Hours</th>
    </tr>
    </thead>

    <tbody>
    <?php foreach ($tableConfig as $section): ?>
        <? if (!empty($section['title'])): ?>
            <tr>
                <td class="grid-category" colspan="4"><?= $section['title'] ?></td>
            </tr>
        <?php endif ?>

        <?php foreach ($section['rows'] as $label => $row): ?>
            <tr>
                <td class="grid-category <?= (empty($section['rowClass'])) ? '' : $section['rowClass'] ?>">
                    <?= $label ?>
                </td>

                <?php foreach ($row as $i => $field): ?>
                    <?php if (!empty($field)):  ?>
                    <td class="grid-value <?= $colClassConfig[$i] ?>-value"
                        id="<?= $colClassConfig[$i] ?>-<?= $field ?>">
                        <?= $this->simpleFormElement($form->get($field)) ?>
                    </td>
                    <?php else: ?>
                        <td class="emptyCell"></td>
                    <?php endif ?>
                <?php endforeach ?>
            </tr>

            <tr class="help-text">
                <td class="grid-category"></td>
                <td colspan="<?= count($row) ?>">

                    <?php foreach ($row as $i => $field): ?>
                        <?php if (empty($field)) continue ?>
                        <div class="<?= $colClassConfig[$i] ?>-help grid-help">
                            <h5><?= $form->get($field)->getLabel() ?></h5>
                            <?= $form->get($field)->getOption('help-block') ?>
                        </div>
                    <?php endforeach ?>

                </td>
            </tr>
        <?php endforeach ?>
    <?php endforeach ?>

    </tbody>
</table>

<?php if ($this->currentStudy()->getDataEntryOpen()): ?>
<fieldset id="fieldset-buttons" class="well well-small">
    <div class="control-group" id="control-group-buttons[submit]">
        <div class="controls" id="controls-buttons[submit]">
            <?= $this->formElement($form->get('buttons')->get('submit')) ?>
        </div>
    </div>
</fieldset>
<?php endif ?>

<?= $this->form()->closeTag() ?>
