<?php
/**
 * This is a special data-entry template that displays this form as a table
 */

$tableConfig = array(
    'Program Development' => array(
        'inst_at_full_program_dev',
        'inst_at_part_program_dev',
    ),
    'Course Development' => array(
        'inst_at_full_course_dev',
        'inst_at_part_course_dev',
    ),
    'Teaching' => array(
        'inst_at_full_teaching',
        'inst_at_part_teaching',
    ),
    'Tutoring' => array(
        'inst_at_full_tutoring',
        'inst_at_part_tutoring',
    ),
    'Advising' => array(
        'inst_at_full_advising',
        'inst_at_part_advising',
    ),
    'Academic Service' => array(
        'inst_at_full_ac_service',
        'inst_at_part_ac_service',
    ),
    'Assessment and Grading' => array(
        'inst_at_full_assessment',
        'inst_at_part_assessment',
    ),
    'Professional Development' => array(
        'inst_at_full_pd',
        'inst_at_part_pd',
    )
);

$colClassConfig = array('full', 'part');

?>

<?= $this->headLink()->appendStylesheet('/css/data-entry-grid.css') ?>

<?php
$this->headScript()->appendFile(
    '/js/data-entry.js',
    'text/javascript'
); ?>

<?= $this->systemAdmin() ?>

<h3>
    <?= $benchmarkGroup->getName() ?>
</h3>

<?php if ($description = $benchmarkGroup->getDescription()): ?>
    <div class="well">
        <?= $description ?>
    </div>
<?php endif ?>


<?php $form->prepare() ?>
<?= $this->form()->openTag($form) ?>

<table class="table table-condensed table-bordered data-entry-grid managerial">
    <thead>
    <tr>
        <th></th>
        <th colspan="2" class="top-table-heading">Percent of Time Spent on Activity</th>
    </tr>
    <tr>
        <th></th>
        <th>Full-time</th>
        <th>Part-time</th>
    </tr>
    </thead>

    <tbody>

    <?php foreach ($tableConfig as $label => $row): ?>
        <tr>
            <td class="grid-category">
                <?= $label ?>
            </td>

            <?php foreach ($row as $i => $field): ?>
                <td class="grid-value <?= $colClassConfig[$i] ?>-value"
                    id="<?= $colClassConfig[$i] ?>-<?= $field ?>">
                    <?= $this->simpleFormElement($form->get($field)) ?>
                </td>
            <?php endforeach ?>
        </tr>

        <tr class="help-text">
            <td class="grid-category"></td>
            <td colspan="<?= count($row) ?>">

                <?php foreach ($row as $i => $field): ?>
                    <div class="<?= $colClassConfig[$i] ?>-help">
                        <?= $form->get($field)->getOption('help-block') ?>
                    </div>
                <?php endforeach ?>

            </td>
        </tr>
    <?php endforeach ?>


    <tr>
        <td class="grid-category">Total</td>
        <td id="full-time-total"></td>
        <td id="part-time-total"></td>
    </tr>

    </tbody>
</table>

<fieldset id="fieldset-buttons" class="well well-small">
    <div class="control-group" id="control-group-buttons[submit]">
        <div class="controls" id="controls-buttons[submit]">
            <?= $this->formElement($form->get('buttons')->get('submit')) ?>
        </div>
    </div>
</fieldset>

<?= $this->form()->closeTag() ?>
