<?php
/**
 * This is a special data-entry template that displays this form as a table
 */

$tableConfig = array(
    'Program Development' => array(
        'inst_full_program_dev',
        'inst_part_program_dev',
        'inst_othr_program_dev'
    ),
    'Course Development' => array(
        'inst_full_course_dev',
        'inst_part_course_dev',
        'inst_othr_course_dev'
    ),
    'Teaching' => array(
        'inst_full_teaching',
        'inst_part_teaching',
        'inst_othr_teaching'
    ),
    'Tutoring' => array(
        'inst_full_tutoring',
        'inst_part_tutoring',
        'inst_othr_tutoring'
    ),
    'Advising' => array(
        'inst_full_advising',
        'inst_part_advising',
        'inst_othr_advising'
    ),
    'Academic Service' => array(
        'inst_full_ac_service',
        'inst_part_ac_service',
        'inst_othr_ac_service'
    ),
    'Assessment and Grading' => array(
        'inst_full_assessment',
        'inst_part_assessment',
        'inst_othr_assessment'
    ),
    'Other' => array(
        'inst_full_other',
        'inst_part_other',
        'inst_othr_other'
    )
);

$colClassConfig = array('full', 'part', 'other');

?>

<?= $this->headLink()->appendStylesheet('/css/data-entry-grid.css') ?>

<?php
$this->headScript()->appendFile(
    '/js/data-entry.js',
    'text/javascript'
); ?>

<?= $this->systemAdmin() ?>

<h2>
    <?= $benchmarkGroup->getName() ?>
</h2>

<?php if ($description = $benchmarkGroup->getDescription()): ?>
    <div class="well">
        <?= $description ?>
    </div>
<?php endif ?>


<?php $form->prepare() ?>
<?= $this->form()->openTag($form) ?>

<table class="table table-condensed table-bordered data-entry-grid">
    <thead>
        <tr>
            <th>Instructional Activities</th>
            <th>Percentage of Time<br> Spent on Activity<br> for Full Time</th>
            <th>Percentage of Time<br> Spent on Activity<br> for Part Time</th>
            <th>Percentage of Time<br> Spent on Activity<br> for Other Full<br> Time Employees</th>
        </tr>
    </thead>

    <tbody>

    <?php foreach ($tableConfig as $label => $row): ?>
        <tr>
            <td class="grid-category">
                <?= $label ?>
            </td>

            <?php foreach ($row as $i => $field): ?>
            <td class="grid-value <?= $colClassConfig[$i] ?>-value"
                id="<?= $colClassConfig[$i] ?>-<?= $field ?>">
                <?= $this->simpleFormElement($form->get($field)) ?>
            </td>
            <?php endforeach ?>
        </tr>

        <tr class="help-text">
            <td class="grid-category"></td>
            <td colspan="<?= count($row) ?>">

                <?php foreach ($row as $i => $field): ?>
                <div class="<?= $colClassConfig[$i] ?>-help">
                    <?= $form->get($field)->getOption('help-block') ?>
                </div>
                <?php endforeach ?>

            </td>
        </tr>
    <?php endforeach ?>


        <tr id="specify-other">
            <td class="grid-category">
                Specify Other
            </td>
            <td>
                <?= $this->simpleFormElement($form->get('inst_full_other_specify')) ?>
            </td>
            <td>
                <?= $this->simpleFormElement($form->get('inst_part_other_specify')) ?>
            </td>
            <td>
                <?= $this->simpleFormElement($form->get('inst_othr_other_specify')) ?>
            </td>
        </tr>

        <tr>
            <td class="grid-category">Total</td>
            <td id="full-time-total"></td>
            <td id="part-time-total"></td>
            <td id="other-time-total"></td>
        </tr>

    </tbody>
</table>

<fieldset id="fieldset-buttons" class="well well-small">
    <div class="control-group" id="control-group-buttons[submit]">
        <div class="controls" id="controls-buttons[submit]">
            <?= $this->formElement($form->get('buttons')->get('submit')) ?>
        </div>
    </div>
</fieldset>

<?= $this->form()->closeTag() ?>
