<?= $this->headLink()->appendStylesheet('/css/data-entry.css') ?>

<div class="page-header">
    <?php if ($this->currentStudy()->getDataEntryOpen()): ?>
        <h2>Data Entry</h2>
    <?php else: ?>
        <h2>Submitted Values</h2>
    <?php endif ?>
</div>

<?php if ($this->currentStudy()->getId() == 3): ?>
    <p>Non-credit workforce development refers to courses and other instructional activities that provide individuals with soft skills and/or technical skill-sets for the workplace but carry no institutional credit applicable toward a degree, diploma, or a credit certificate.  Offerings may be on-campus, off-campus, online, distance learning or at a specific organization/business.   The goal is to increase individual opportunity in the labor market to improve participants’ knowledge, skills, and abilities and/or provide specific employee training for the benefit of a given business client.</p>

    <p>Please enter all the data that you have available. If you do not have data for a particular data element, feel free to leave that cell blank. However, the more data you provide, the better you will be able to benchmark your institution.</p>

    <p>To navigate you can either click on the blue title or click the Data Entry link at the top of the page.</p>

    <p><strong>If  you prefer to upload your data in an Excel  spreadsheet please use the <a href="<?= $this->url('data-entry/import') ?>">Excel Spreadsheet</a>.</strong></p>
    <br>


<?php endif ?>

<?php if ($this->currentStudy()->getId() == 2): ?>
    <p>Welcome.</p>

    <p>You’re ready to begin entering your data and start maximizing your resources for student success.</p>

    <p>Click the links below to get started. Start with any form below, and feel free to save your progress along the way and return later to finish entering your data.</p>

    <p><strong>Prefer to upload your data?</strong></p>

    <p>Please use the <a href="<?= $this->url('data-entry/import') ?>">Excel Spreadsheet</a>.</p>

    <br>


<?php endif ?>


<div class="well">
    <h5>Your Data Entry Progress</h5>


    <div class="row row-fluid">
        <div class="span1 col-md-1">

        </div>

        <div class="span9 col-md-9">
            <div class="progress">
                <div class="bar progress-bar"
                     role="progressbar"
                     aria-valuenow="<?= $completionPercentage ?>"
                     aria-valuemin="0"
                     aria-valuemax="100"
                     style="width: <?= $completionPercentage ?>%;"></div>
            </div>
        </div>

        <div class="span2 col-md-2">
            <strong>
                <?= $completionPercentage ?>%
            </strong>
        </div>

    </div>


</div>


<?php foreach ($benchmarkGroups as $benchmarkGroup): ?>
    <div class="row row-fluid">
        <div class="span1 col-md-1">

        </div>

        <div class="span4 col-md-4">
            <a href="<?= $this->url(
                'data-entry/edit',
                array(
                    'benchmarkGroup' => $benchmarkGroup->getUrl()
                )
            ) ?>">
                <?= $benchmarkGroup->getName() ?>
            </a>

            <?php // List incomplete fields (for debugging ?>
            <?php $incompletes = $benchmarkGroup->getIncompleteBenchmarksForObservation($observation) ?>
            <?php if (false && count($incompletes)): ?>
                <div style="margin-left: 20px">
                Incomplete fields:<br>
                <?php foreach ($incompletes as $benchmark): ?>
                    <?= $benchmark->getName() ?> (<?= $benchmark->getDbColumn() ?>)<br>
                <?php endforeach ?>
                </div>
            <?php endif ?>

            <?php // List complete fields (for debugging ?>
            <?php $completes = $benchmarkGroup->getCompleteBenchmarksForObservation($observation) ?>
            <?php if (false && count($completes)): ?>
                <div style="margin-left: 20px">
                Complete fields:<br>
                <?php foreach ($completes as $benchmark): ?>
                    <?= $benchmark->getName() ?> (<?= $benchmark->getDbColumn() ?>)<br>
                <?php endforeach ?>
                </div>
            <?php endif ?>
        </div>

        <?php $completion = $benchmarkGroup->getCompletionPercentageForObservation($observation) ?>
        <div class="span7 col-md-7">
            <div class="progress benchmarkGroupProgress">
                <div class="bar progress-bar"
                     role="progressbar"
                     aria-valuenow="<?= $completion ?>"
                     aria-valuemin="0"
                     aria-valuemax="100"
                     style="width: <?= $completion ?>%;"></div>
            </div>
        </div>

    </div>
<?php endforeach ?>

<br>

<?php if (!$this->currentStudy()->getDataEntryOpen()): ?>
<div class="row row-fluid">
    <div class="span1 col-md-1">

    </div>

    <div class="span4 col-md-4">
        <a href="<?= $this->url('data-entry/all') ?>">All Submitted Values</a>
    </div>
</div>
<?php endif ?>

<?php if ($this->currentStudy()->getId() == 2): ?>
    <a target="_blank" href="/files/How-to-Complete.pdf">Detailed Instructions (PDF)</a>


<?php endif ?>


