<?= $this->headLink()->appendStylesheet('/css/data-entry.css') ?>

<?= $this->systemAdmin() ?>

<div class="page-header">
    <h2>Data Entry</h2>
</div>

<?php if ($this->currentStudy()->getId() == 3): ?>
    <p>Non-credit workforce development refers to courses and other instructional activities that provide individuals with soft skills and/or technical skill-sets for the workplace but carry no institutional credit applicable toward a degree, diploma, or a for-credit certificate.  Offerings may be on-campus, off-campus, online, distance learning or at a specific organization/business.   The goal is to increase individual opportunity in the labor market to improve participants’ knowledge, skills, and abilities and/or provide specific employee training for the benefit of a given business client.</p>

    <p>Please enter all the data that you have available. If you do not have data for a particular data element, feel free to leave that cell blank. However, the more data you provide, the better you will be able to benchmark your institution.</p>

    <p>To navigate you can either click on the blue title or click the Data Entry link at the top of the page.</p>

    <p><strong>If  you prefer to upload your data in an Excel  spreadsheet please use the <a href="<?= $this->url('data-entry/import') ?>">Excel Spreadsheet</a>.</strong></p>
    <br>


<?php endif ?>

<?php if ($this->currentStudy()->getId() == 2): ?>
    <p>Welcome to the Maximizing Resources for Student Success Data Section.</p>

    <p>Please follow the links below to enter your institution's data.</p>

    <p>To navigate you can either click on the blue title or click the Data Entry link at the top of the page.</p>

    <p><strong>If  you prefer to upload your data in an Excel  spreadsheet please use the <a href="<?= $this->url('data-entry/import') ?>">Excel Spreadsheet</a>.</strong></p>

    <br>


<?php endif ?>


<div class="well">
    <h5>Your Data Entry Progress</h5>


    <div class="row row-fluid">
        <div class="span1">

        </div>

        <div class="span9">
            <div class="progress">
                <div class="bar" style="width: <?= $completionPercentage ?>%;"></div>
            </div>
        </div>

        <div class="span2">
            <strong>
                <?= $completionPercentage ?>%
            </strong>
        </div>

    </div>


</div>


<?php foreach ($benchmarkGroups as $benchmarkGroup): ?>
    <div class="row row-fluid">
        <div class="span1">

        </div>

        <div class="span4">
            <a href="<?= $this->url(
                'data-entry/edit',
                array(
                    'benchmarkGroup' => $benchmarkGroup->getId()
                )
            ) ?>">
                <?= $benchmarkGroup->getName() ?>
            </a>

            <?php // List incomplete fields (for debugging ?>
            <?php $incompletes = $benchmarkGroup->getIncompleteBenchmarksForObservation($observation) ?>
            <?php if (false && count($incompletes)): ?>
                <div style="margin-left: 20px">
                Incomplete fields:<br>
                <?php foreach ($incompletes as $benchmark): ?>
                    <?= $benchmark->getName() ?> (<?= $benchmark->getDbColumn() ?>)<br>
                <?php endforeach ?>
                </div>
            <?php endif ?>
        </div>

        <div class="span7">
            <div class="progress benchmarkGroupProgress">
                <div class="bar" style="width: <?= $benchmarkGroup->getCompletionPercentageForObservation($observation) ?>%;
                    "></div>
            </div>
        </div>

    </div>
<?php endforeach ?>

<br>

