<?= $this->headLink()->appendStylesheet('/css/data-entry.css') ?>

<?= $this->systemAdmin() ?>

<div class="page-header">
    <h2>Data Entry</h2>
</div>

<?php if ($this->currentStudy()->getId() == 3): ?>
    <p>Non-credit workforce development refers to courses and other instructional activities that provide individuals with soft skills and/or technical skill-sets for the workplace but carry no institutional credit applicable toward a degree, diploma, or a for-credit certificate.  Offerings may be on-campus, off-campus, online, distance learning or at a specific organization/business.   The goal is to increase individual opportunity in the labor market to improve participants’ knowledge, skills, and abilities and/or provide specific employee training for the benefit of a given business client.</p>

    <p>
        <a href="<?= $this->url('data-entry/import') ?>">
            Import/Export
        </a>
    </p>
<?php endif ?>

<?php if ($this->currentStudy()->getId() == 2): ?>
    <p>Welcome to the Maximizing Resources for Student Success Data Section.</p>

    <p>Please follow the links below to enter your institution's data.</p>
    <br>


<?php endif ?>


<div class="well">
    <h5>Your Data Entry Progress</h5>


    <div class="row row-fluid">
        <div class="span1">

        </div>

        <div class="span9">
            <div class="progress">
                <div class="bar" style="width: <?= $completionPercentage ?>%;"></div>
            </div>
        </div>

        <div class="span2">
            <strong>
                <?= $completionPercentage ?>%
            </strong>
        </div>

    </div>


</div>


<?php foreach ($benchmarkGroups as $benchmarkGroup): ?>
    <div class="row row-fluid">
        <div class="span1">

        </div>

        <div class="span4">
            <a href="<?= $this->url(
                'data-entry/edit',
                array(
                    'benchmarkGroup' => $benchmarkGroup->getId()
                )
            ) ?>">
                <?= $benchmarkGroup->getName() ?>
            </a>
        </div>

        <div class="span7">
            <div class="progress benchmarkGroupProgress">
                <div class="bar" style="width: <?= $benchmarkGroup->getCompletionPercentageForObservation($observation) ?>%;
                    "></div>
            </div>
        </div>

    </div>
<?php endforeach ?>

<br>

<p>If  you prefer to upload your data in an Excel  spreadsheet please use the <a href="<?= $this->url('data-entry/import') ?>">Data Entry Template</a>.</p>
