<?php
/**
 * This is a special data-entry template that displays this form as a table
 */

$tableConfig = array(
    'Admissions' => array(
        'ss_admissions_total',
        'ss_admis_o_cost',
        'ss_admiss_emp',
        '',
        'ss_admissions_contract',
    ),
    'Recruitment' => array(
        'ss_recruitment_total',
        'ss_recruitment_o_cost',
        'ss_recruitment_emp',
        '',
        'ss_recruitment_contract',
    ),
    'Advising' => array(
        'ss_advising_total',
        'ss_advising_o_cost',
        'ss_advising_emp',
        'ss_advising_student',
        'ss_advising_contract',
    ),
    'Counseling' => array(
        'ss_counseling_total',
        'ss_counseling_o_cost',
        'ss_counseling_emp',
        'ss_counseling_student',
        'ss_counseling_contract',
    ),
    'Career Services' => array(
        'ss_career_total',
        'ss_career_o_cost',
        'ss_career_emp',
        'ss_career_student',
        'ss_career_contract',
    ),
    'Financial Aid' => array(
        'ss_financial_aid_total',
        'ss_financial_aid_o_cost',
        'ss_financial_aid_emp',
        'ss_financial_aid_student',
        'ss_financial_aid_contract',
    ),
    'Registrar / Student Records' => array(
        'ss_registrar_total',
        'ss_registrar_o_cost',
        'ss_registrar_emp',
        '',
        'ss_registrar_contract',
    ),
    'Tutoring' => array(
        'ss_tutoring_total',
        'ss_tutoring_o_cost',
        'ss_tutoring_emp',
        'ss_tutoring_students',
        'ss_tutoring_contract',
    ),
    'Testing Services' => array(
        'ss_testing_total',
        'ss_testing_o_cost',
        'ss_testing_emp',
        'ss_testing_student',
        'ss_testing_contract',
    ),
    'Co-curricular Activities' => array(
        'ss_cocurricular_total',
        'ss_cocurricular_o_cost',
        'ss_cocurricular_emp',
        '',
        'ss_cocurricular_contract',
    ),
    'Disability Services' => array(
        'ss_disabserv_total',
        'ss_disabserv_o_cost',
        'ss_disabserv_emp',
        'ss_disabserv_o_students',
        'ss_disabserv_contract'
    ),
    "Veterans' Services" => array(
        'ss_vetserv_total',
        'ss_vetserv_o_cost',
        'ss_vetserv_emp',
        'ss_vetserv_o_students',
        'ss_vetserv_contract'
    )
);

$colClassConfig = array(
    'expenditures',
    'cost',
    'fte_num',
    'students_served',
    'contract'
);

?>

<?= $this->headLink()->appendStylesheet('/css/data-entry-grid.css') ?>

<?php
$this->headScript()->appendFile(
    '/js/data-entry.js',
    'text/javascript'
); ?>

<?= $this->systemAdmin() ?>

<h2>
    <?= $benchmarkGroup->getName() ?>
</h2>

<?php if ($description = $benchmarkGroup->getDescription()): ?>
    <div class="well">
        <?= $description ?>
    </div>
<?php endif ?>


<?php $form->prepare() ?>
<?= $this->form()->openTag($form) ?>

<table class="table table-condensed table-bordered data-entry-grid">
    <thead>
    <tr>
        <th></th>
        <th>Salaries<br>and Benefits</th>
        <th>Non-labor<br>Operating Costs</th>
        <th>
            Number of<br>FTE Employees
            <span class="icon-info-sign infotip" title="FTE: Full-time equivalent"></span>

        </th>
        <th>
            Number of<br>Students Served
            <span class="icon-info-sign infotip" title="Number of email, phone and in-person student contacts."></span>
        </th>
        <th>Contract</th>
    </tr>
    </thead>

    <tbody>

    <?php foreach ($tableConfig as $label => $row): ?>
        <tr>
            <td class="grid-category">
                <?= $label ?>
            </td>

            <?php foreach ($row as $i => $field): ?>
                <?php if (!empty($field)): ?>
                <td class="grid-value <?= $colClassConfig[$i] ?>-value"
                    id="<?= $colClassConfig[$i] ?>-<?= $field ?>">
                    <?= $this->simpleFormElement($form->get($field)) ?>
                </td>
                <?php else: ?>
                <td></td>
                <?php endif ?>
            <?php endforeach ?>
        </tr>

        <tr class="help-text">
            <td class="grid-category"></td>
            <td colspan="<?= count($row) ?>">

                <?php foreach ($row as $i => $field): ?>
                    <?php if (empty($field)) continue; ?>
                    <div class="<?= $colClassConfig[$i] ?>-help">
                        <?= $form->get($field)->getOption('help-block') ?>
                    </div>
                <?php endforeach ?>

            </td>
        </tr>
    <?php endforeach ?>

    </tbody>
</table>

<fieldset id="fieldset-buttons" class="well well-small">
    <div class="control-group" id="control-group-buttons[submit]">
        <div class="controls" id="controls-buttons[submit]">
            <?= $this->formElement($form->get('buttons')->get('submit')) ?>
        </div>
    </div>
</fieldset>

<?= $this->form()->closeTag() ?>
