<?php
/**
 * This is a special data-entry template that displays this form as a table
 */

$tableConfig = array(
    'Admissions' => array(
        'ss_admissions_total',
        'ss_admissions_contract',
    ),
    'Recruitment' => array(
        'ss_recruitment_total',
        'ss_recruitment_contract',
    ),
    'Advising' => array(
        'ss_advising_total',
        'ss_advising_contract',
    ),
    'Counseling' => array(
        'ss_counceling_total',
        'ss_counceling_contract',
    ),
    'Career Services' => array(
        'ss_career_total',
        'ss_career_contract',
    ),
    'Financial Aid' => array(
        'ss_financial_aid_total',
        'ss_financial_aid_contract',
    ),
    'Registrar / Student Records' => array(
        'ss_registrar_total',
        'ss_registrar_total',
    ),
    'Tutoring' => array(
        'ss_tutoring_total',
        'ss_tutoring_contract',
    ),
    'Testing Services' => array(
        'ss_testing_total',
        'ss_testing_contract',
    ),
    'Co-curricular Activities' => array(
        'ss_cocurricular_total',
        'ss_cocurricular_contract',
    ),
);

$colClassConfig = array('expenditures', 'contract');

?>

<?= $this->headLink()->appendStylesheet('/css/data-entry-grid.css') ?>

<?php
$this->headScript()->appendFile(
    '/js/data-entry.js',
    'text/javascript'
); ?>

<?= $this->systemAdmin() ?>

<h2>
    <?= $benchmarkGroup->getName() ?>
</h2>

<?php if ($description = $benchmarkGroup->getDescription()): ?>
    <div class="well">
        <?= $description ?>
    </div>
<?php endif ?>


<?php $form->prepare() ?>
<?= $this->form()->openTag($form) ?>

<table class="table table-condensed table-bordered data-entry-grid">
    <thead>
    <tr>
        <th>Student Services</th>
        <th>Expenditures for Salary and Benefits</th>
        <th>Contract</th>
    </tr>
    </thead>

    <tbody>

    <?php foreach ($tableConfig as $label => $row): ?>
        <tr>
            <td class="grid-category">
                <?= $label ?>
            </td>

            <?php foreach ($row as $i => $field): ?>
                <td class="grid-value <?= $colClassConfig[$i] ?>-value"
                    id="<?= $colClassConfig[$i] ?>-<?= $field ?>">
                    <?= $this->simpleFormElement($form->get($field)) ?>
                </td>
            <?php endforeach ?>
        </tr>

        <tr class="help-text">
            <td class="grid-category"></td>
            <td colspan="<?= count($row) ?>">

                <?php foreach ($row as $i => $field): ?>
                    <div class="<?= $colClassConfig[$i] ?>-help">
                        <?= $form->get($field)->getOption('help-block') ?>
                    </div>
                <?php endforeach ?>

            </td>
        </tr>
    <?php endforeach ?>

    </tbody>
</table>

<fieldset id="fieldset-buttons" class="well well-small">
    <div class="control-group" id="control-group-buttons[submit]">
        <div class="controls" id="controls-buttons[submit]">
            <?= $this->formElement($form->get('buttons')->get('submit')) ?>
        </div>
    </div>
</fieldset>

<?= $this->form()->closeTag() ?>
