<?php
    /** @var \Mrss\Entity\Subscription $subscription */
?>
<style type="text/css">
    html table.table.submittedValues {
        width: 50%;
    }
    td.value {
        text-align: right;
    }
    td.computed {
        font-style: italic;
        color: #888;
    }
    .submittedValues h2 {
        padding-top: 20px;
    }
    .submittedValues h3 {
        font-size: 16px;
    }
</style>

<h1>Submitted Values</h1>


<?php if (count($otherSystems)): ?>
    <ul class="nav nav-pills report-nav">
        <?php $url = '/submitted-values/' . $year; ?>
        <?php foreach ($otherSystems as $otherSystem): ?>
            <li<?php if ($system->getId() == $otherSystem->getId()) echo ' class="active"'; ?>>
                <a href="/network-switch/<?= $otherSystem->getId() . '?redirect=' . urlencode($url) ?>">
                    <?= $otherSystem->getName() ?>
                </a>
            </li>
        <?php endforeach ?>
    </ul>
<?php endif ?>

<ul class="nav nav-pills report-nav">
    <?php foreach ($subscriptions as $subscription): ?>
        <li<? if ($subscription->getYear() == $year) echo ' class="active"' ?>>
            <a href="<?= $this->url('submitted-values', array('year' => $subscription->getYear())) ?>"><?= $subscription->getYear() ?></a>
        </li>
    <?php endforeach ?>
</ul>

<div class="reportDownloads">
    <a href="<?= $this->url('submitted-values', array('year' => $year, 'format' => 'xls')) ?>" class="btn btn-default">
        <span class="glyphicon glyphicon-circle-arrow-down"></span>
        Download
    </a>
</div>
<p>
    <strong>Please note:</strong> The website has created the values in grey italics based on the data you entered.
</p>

<?php if (false): ?>
<div class="row row-fluid">
    <div class="span2 col-md-2">
        <strong>Data Entry Progress:</strong>
    </div>

    <div class="span3 col-md-3">
        <div class="progress">
            <div class="bar progress-bar"
                 role="progressbar"
                 aria-valuenow="<?= $completionPercentage ?>"
                 aria-valuemin="0"
                 aria-valuemax="100"
                 style="width: <?= $completionPercentage ?>%;"></div>
        </div>
    </div>

    <div class="span2 col-md-2">
        <strong>
            <?= $completionPercentage ?>%
        </strong>
    </div>

</div>
<?php endif ?>

<table class="table submittedValues">
<?php foreach ($submittedValues as $benchmarkGroup): ?>
        <tr>
            <td colspan="2">
                <h2><?= $benchmarkGroup['benchmarkGroup'] ?></h2>
            </td>
        </tr>

    <?php foreach ($benchmarkGroup['benchmarks'] as $benchmark): ?>
        <tr>

        <?php if (!empty($benchmark['heading'])): ?>
            <td colspan="2">
                <h3><?= $benchmark['name'] ?></h3>
                <?php if (!empty($benchmark['description'])): ?>
                    <p><?= $benchmark['description'] ?></p>
                <?php endif ?>
            </td>

        <?php else: ?>
            <?php $b = $benchmark['benchmark'] ?>
            <?php $class = ($b->getComputed()) ? 'computed' : 'submitted' ?>
            <td class="<?= $class ?>"><?= $benchmark['benchmarkName'] ?></td>
            <td class="value <?= $class ?>"><?= $benchmark['value'] ?></td>
        <?php endif ?>
        </tr>
    <?php endforeach ?>
<?php endforeach ?>
</table>
