<h3>
    <?= $this->observation->getCollege()->getName() ?>:
    <?= $this->observation->getYear() ?>
</h3>

<?php if (empty($this->benchmarkGroup)): ?>

    <h4>Select a Form</h4>

    <ul>
        <?php foreach ($this->benchmarkGroups as $benchmarkGroup): ?>
            <li>
                <div class="progress benchmarkGroupProgress">
                    <div class="bar progress-bar" style="width: <?= $benchmarkGroup->getCompletionPercentageForObservation($this->observation) ?>%;
                    "></div>
                </div>

                <a href="<?= $this->url(
                    'observation/group',
                    array(
                        'id' => $this->observation->getId(),
                        'benchmarkGroupId' => $benchmarkGroup->getId())
                ) ?>">
                    <?= $benchmarkGroup->getName() ?>
                </a> (<?= count($benchmarkGroup->getBenchmarks()) ?> benchmarks)

                <div class="clear"></div>
            </li>
        <?php endforeach ?>
    </ul>

<?php else: ?>

    <h4><?= $this->benchmarkGroup->getName() ?></h4>

    <?php if ($description = $benchmarkGroup->getDescription()): ?>
    <div class="well">
        <?= $description ?>
    </div>
    <?php endif ?>

    <a href="<?= $this->url(
        'observation/group/edit',
        array(
            'id' => $this->observation->getId(),
            'benchmarkGroupId' => $this->benchmarkGroup->getId()
        )
    ) ?>">
        Edit
    </a>

    <table class="style1">
        <tr>
            <th>Benchmark</th>
            <th>Value</th>
        </tr>

        <?php foreach ($this->fields as $key => $label): ?>
            <tr>
                <td><?= $label ?></td>
                <td><?= $this->observation->get($key) ?></td>
            </tr>
        <?php endforeach ?>
    </table>

<?php endif ?>



