<?php /** @var \Mrss\Entity\Report $report */ ?>

<?= $this->headLink()->appendStylesheet('/css/custom-report.css?v=1', 'screen,print') ?>
<?//= $this->headLink()->appendStylesheet('/css/executive-report-print.css?v=5', $media) ?>
<?//= $this->headLink()->appendStylesheet('http://fonts.googleapis.com/css?family=Open+Sans:300italic,400,600,700', 'screen,print') ?>

<script type="text/javascript">
    $(function() {
        var url = '/reports/custom/<?= $report->getId() ?>/reorder'

        $('.reportItems').sortable({
            //handle: '.handle',
            update: function(event, ui) {
                var data = $('.reportItems').sortable('serialize')

                $.post(url, data, function(result) {})
            }
        })

        $('.delete-confirm').click(function() {
            return confirm('Are you sure you want to delete this?')
        })
    })
</script>

<div class="back">
    <a href="/reports/custom">
        <span class="glyphicon glyphicon-arrow-left"></span>
        Back to Custom Reports
    </a>
</div>

<?= $this->partial(
    'mrss/custom-report/report-controls.partial.phtml',
    array('report' => $report, 'active' => 'build')
) ?>


<h1><?= $report->getName() ?></h1>

<p class="reportDescription"><?= $report->getDescription() ?></p>

<p>
    <a href="<?= $this->url('reports/custom/addItem', array('id' => $report->getId())) ?>" class="btn btn-default">
        <span class="glyphicon glyphicon-plus icon icon-plus"></span>
        Add an Item
    </a>

    <span class="smallNote">Drag and drop to reorder.</span>
</p>


<div class="reportItems">
    <?php $footnotes = array(); ?>
    <?php foreach ($report->getItems() as $item): ?>
        <?= $this->partial(
            'mrss/custom-report/report-item.partial.phtml',
            array('item' => $item, 'buttons' => true)
        ) ?>
        <?php
        if ($itemFootnotes = $item->getCacheFootnotes()) {
            $footnotes[] = array(
                'name' => $item->getName(),
                'footnotes' => $itemFootnotes
            );
        }

        ?>
    <?php endforeach ?>
</div>

<div style="clear: both; margin-bottom: 30px"></div>

<?php if (!empty($footnotes)): ?>

    <h2>Footnotes</h2>

    <?= $this->partial(
        'mrss/custom-report/footnotes.partial.phtml',
        array('footnotes' => $footnotes)
    ) ?>

<?php endif ?>
