<?php /** @var \Mrss\Entity\Report $report */ ?>

<?= $this->headLink()->appendStylesheet('/css/custom-report.css?v=15', 'screen,print') ?>
<? $this->headLink()->appendStylesheet('/css/custom-report-print.css?v=4', 'print') ?>
<?//= $this->headLink()->appendStylesheet('/css/executive-report-print.css?v=5', $media) ?>
<?//= $this->headLink()->appendStylesheet('http://fonts.googleapis.com/css?family=Open+Sans:300italic,400,600,700', 'screen,print') ?>

<?php
$this->headScript()->appendFile(
    '/js/report.js?v=8',
    'text/javascript'
);
?>


<script type="text/javascript">
    <?php $this->headScript()->captureStart() ?>
    $(function() {
        var url = '/reports/custom/<?= $report->getId() ?>/reorder'

        $('.reportItems').sortable({
            //handle: '.handle',
            update: function(event, ui) {
                var data = $('.reportItems').sortable('serialize')

                $.post(url, data, function(result) {})
            }
        })

        $('.delete-confirm').click(function() {
            return confirm('Are you sure you want to delete this?')
        })
    })
    <?php $this->headScript()->captureEnd() ?>
</script>

<div class="back">
    <a href="/reports/custom">
        <span class="glyphicon glyphicon-arrow-left"></span>
        Back to Custom Reports
    </a>
</div>

<?= $this->partial(
    'mrss/custom-report/report-controls.partial.phtml',
    array('report' => $report, 'active' => 'build')
) ?>


<h1><?= $report->getName() ?></h1>

<p class="reportDescription"><?= $report->getDescription() ?></p>

<?php $url = $this->url('reports/custom/addItem', array('id' => $report->getId())) ?>

<div class="addItemButton">
    <div class="btn-group">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="glyphicon glyphicon-plus icon icon-plus"></span>
            Add an Item <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
            <?php foreach ($presentationOptions as $key => $label): ?>
                <li><a href="<?= $url ?>/<?= $key ?>"><?= $label ?></a></li>
            <?php endforeach ?>
        </ul>
    </div>

    <span class="smallNote">Drag and drop to reorder.</span>
</div>




    <div class="reportItems">
        <?php $footnotes = array(); ?>
        <?php foreach ($report->getItems() as $item): ?>
            <?= $this->partial(
                'mrss/custom-report/report-item.partial.phtml',
                array('item' => $item, 'buttons' => true)
            ) ?>
            <?php
            if ($itemFootnotes = $item->getCacheFootnotes()) {
                $footnotes[] = array(
                    'name' => $item->getName(),
                    'footnotes' => $itemFootnotes
                );
            }

            ?>
        <?php endforeach ?>
    </div>

    <div style="clear: both; margin-bottom: 30px"></div>

    <?php if (!empty($footnotes) && $report->getDisplayFootnotes()): ?>
        <?= $this->partial(
            'mrss/custom-report/footnotes.partial.phtml',
            array('footnotes' => $footnotes)
        ) ?>

    <?php endif ?>
