<?= $this->headLink()->appendStylesheet('/css/custom-report.css?v=1', 'screen,print') ?>
<div class="back">
    <a href="/reports/custom">
        <span class="glyphicon glyphicon-arrow-left"></span>
        Back to Custom Reports
    </a>
</div>

<?= $this->partial(
    'mrss/custom-report/report-controls.partial.phtml',
    array('report' => $report, 'active' => 'edit')
) ?>

<h1>Edit Report</h1>

<?php
// Add an action to the form
$form->setAttribute('action', $this->url('reports/custom/edit'));

?>

<?= $this->ztbForm($this->form->prepare()) ?>
