<?php
/** @var \Mrss\Entity\Report[] $reports */
$this->headLink()->appendStylesheet('/css/custom-report.css?v=14', 'screen,print')
?>

<script type="text/javascript">
    <?php $this->headScript()->captureStart() ?>
    $(function() {
        $('.delete-confirm').click(function() {
            return confirm('Are you sure you want to delete this?')
        })
    })
    <?php $this->headScript()->captureEnd() ?>
</script>



<div class="btn-group heading-btns">
    <a href="<?= $this->url('reports/custom/add') ?>" class="btn btn-default"><span class="glyphicon glyphicon-plus icon icon-plus"></span> Add a Report</a>
</div>

<h1>Custom Reports</h1>

<?php if (false): ?>
<div class="well">
    <p><a href="<?= $webinarLink ?>">Request a webinar</a> to learn more about custom reports.</p>
</div>
<?php endif ?>

<div class="customReportList">
<?php foreach ($reports as $report): ?>
    <div class="customReport">
        <?= $this->partial(
            'mrss/custom-report/report-controls.partial.phtml',
            array('report' => $report, 'active' => null)
        ) ?>

        <a href="<?= $this->url('reports/custom/view', array('id' => $report->getId())) ?>">
            <h2><?= $this->escapeHtml($report->getName()) ?></h2>
        </a>

        <p class="reportDescription"><?= $report->getDescription() ?></p>
    </div>
<?php endforeach ?>
</div>
