<?php /** @var \Mrss\Entity\Report $report */ ?>
<div class="btn-group heading-btns" role="group">
    <?php if ($report->isPublic()): ?>
    <a href="<?= $this->url('reports/custom/public', array('id' => $report->getId())) ?>"
       class="btn btn-default"
       title="Public URL of report.">
        <span class="glyphicon glyphicon-globe"></span>
        Public
    </a>
    <?php endif ?>

    <a href="<?= $this->url('reports/custom/view', array('id' => $report->getId())) ?>"
       class="btn btn-default<?php if ($active == 'view') echo ' active' ?>"
       title="View the report.">
        <span class="glyphicon glyphicon-eye-open"></span>
        View
    </a>
    <a href="<?= $this->url('reports/custom/edit', array('id' => $report->getId())) ?>"
       class="btn btn-default<?php if ($active == 'edit') echo ' active' ?>"
       title="Edit basic report details like title and description.">
        <span class="glyphicon glyphicon-edit"></span>
        Edit
    </a>
    <a href="<?= $this->url('reports/custom/build', array('id' => $report->getId())) ?>"
       class="btn btn-default<?php if ($active == 'build') echo ' active' ?>"
       title="Build report by adding charts and text.">
        <span class="glyphicon glyphicon-wrench"></span>
        Build
    </a>
    <a href="<?= $this->url('reports/custom/print', array('id' => $report->getId())) ?>"
       class="btn btn-default<?php if ($active == 'print') echo ' active' ?>"
       title="Print the report to paper or PDF.">
        <span class="glyphicon glyphicon-print"></span>
        Print
    </a>

    <?php if ($this->isAllowed('adminMenu', 'view') || $this->isAllowed('systemSwitch', 'view')): ?>
    <a href="<?= $this->url('reports/custom/publish', array('id' => $report->getId())) ?>"
       class="btn btn-default<?php if ($active == 'copy') echo ' active' ?>"
       title="Copy this report to other <?= $this->studyConfig()->institutions_label ?>.">
        <span class="glyphicon glyphicon-share"></span>
        Publish
    </a>
    <?php endif ?>

    <a href="<?= $this->url('reports/custom/duplicate', array('id' => $report->getId())) ?>"
       class="btn btn-default"
       title="Make a duplicate copy of this for yourself.">
        <span class="glyphicon glyphicon-duplicate"></span>
        Duplicate
    </a>

    <a href="<?= $this->url('reports/custom/delete', array('id' => $report->getId())) ?>"
       class="btn btn-default delete-confirm"
       title="Permanently delete the report.">
        <span class="glyphicon glyphicon-trash"></span>
        Delete
    </a>
</div>
