<?php /** @var \Mrss\Entity\Report $report */ ?>
<div class="btn-group heading-btns" role="group">
    <?php if ($report->isPublic()): ?>
    <a href="<?= $this->url('reports/custom/public', array('id' => $report->getId())) ?>"
       class="btn btn-default"
       title="Public URL of report.">
        <span class="glyphicon glyphicon-share"></span>
        Public
    </a>
    <?php endif ?>

    <a href="<?= $this->url('reports/custom/view', array('id' => $report->getId())) ?>"
       class="btn btn-default<?php if ($active == 'view') echo ' active' ?>"
       title="View the report.">
        <span class="glyphicon glyphicon-eye-open"></span>
        View
    </a>
    <a href="<?= $this->url('reports/custom/edit', array('id' => $report->getId())) ?>"
       class="btn btn-default<?php if ($active == 'edit') echo ' active' ?>"
       title="Edit basic report details like title and description.">
        <span class="glyphicon glyphicon-edit"></span>
        Edit
    </a>
    <a href="<?= $this->url('reports/custom/build', array('id' => $report->getId())) ?>"
       class="btn btn-default<?php if ($active == 'build') echo ' active' ?>"
       title="Build report by adding charts and text.">
        <span class="glyphicon glyphicon-wrench"></span>
        Build
    </a>
    <a href="<?= $this->url('reports/custom/print', array('id' => $report->getId())) ?>"
       class="btn btn-default<?php if ($active == 'print') echo ' active' ?>"
       title="Print the report to paper or PDF.">
        <span class="glyphicon glyphicon-print"></span>
        Print
    </a>

    <?php if ($this->isAllowed('adminMenu', 'view')): ?>
    <a href="<?= $this->url('reports/custom/copy', array('id' => $report->getId())) ?>"
       class="btn btn-default<?php if ($active == 'copy') echo ' active' ?>"
       title="Copy this report to all institutions."
       onclick="return confirm('Are you sure you want to copy this to every institution?')">
        <span class="glyphicon glyphicon-duplicate"></span>
        Copy
    </a>
    <?php endif ?>

    <a href="<?= $this->url('reports/custom/delete', array('id' => $report->getId())) ?>"
       class="btn btn-default delete-confirm"
       title="Permanently delete the report.">
        <span class="glyphicon glyphicon-trash"></span>
        Delete
    </a>
</div>
