<?php /** @var \Mrss\Entity\Report $report */ ?>
<? $this->headLink()->appendStylesheet('/css/custom-report.css?v=1', 'screen,print') ?>

<div class="customReport">
    <div class="back">
        <a href="/reports/custom">
            <span class="glyphicon glyphicon-arrow-left"></span>
            Back to Custom Reports
        </a>
    </div>

    <?= $this->partial(
        'mrss/custom-report/report-controls.partial.phtml',
        array('report' => $report, 'active' => 'view')
    ) ?>

    <h1><?= $this->escapeHtml($report->getName()) ?></h1>

    <p class="reportDescription"><?= $report->getDescription() ?></p>

    <div class="reportItems">
        <?php foreach ($report->getItems() as $item): ?>
            <?= $this->partial(
                'mrss/custom-report/report-item.partial.phtml',
                array('item' => $item, 'buttons' => false)
            ) ?>
        <?php endforeach ?>
    </div>

    <div style="clear: both; margin-bottom: 30px"></div>


</div>
