<?php /** @var \Mrss\Entity\Report $report */ ?>
<? $this->headLink()->appendStylesheet('/css/custom-report.css?v=13', 'screen,print') ?>
<? $this->headLink()->appendStylesheet('/css/custom-report-print.css?v=4', $printMedia) ?>
<?php
$this->headScript()->appendFile(
    '/js/report.js?v=7',
    'text/javascript'
);
?>


<?php if ($print): ?>

    <script>
        <?php $this->headScript()->captureStart() ?>
        $(function() {
            if (true) {
                var systemLogo = '<?= $systemLogo ?>';

                if (systemLogo) {
                    // Move header logo to bottom
                    var oldLogo = $('.header .logo-benchmark').clone();

                    // Network/system logo
                    $('.header .logo-benchmark').css('background-image', 'url(/images/' + systemLogo + ')');
                    $('.header .logo-benchmark').css('height', '80px');
                    $('.header .logo-benchmark').css('background-size', '150px');
                    $('.header .logo-benchmark img').css('height', '80px');
                    $('.header .logo-benchmark img').attr('src', '/images/' + systemLogo);
                    $('.container.header').css('margin-left', '40px');

                    oldLogo.find('img').css('height', '40px');
                    oldLogo.find('img').css('margin-left', '40px');
                    $('#content').append(oldLogo);

                }

            }


            // Show print
            setTimeout(function() {window.print()}, 2000);
        });


        <?php $this->headScript()->captureEnd() ?>
    </script>


<?php endif ?>

<div class="customReport">
    <?php if (empty($public)): ?>
    <div class="back">
        <a href="/reports/custom">
            <span class="glyphicon glyphicon-arrow-left"></span>
            Back to Custom Reports
        </a>
    </div>
    <?php endif ?>

    <?php if (empty($public)): ?>
    <?= $this->partial(
        'mrss/custom-report/report-controls.partial.phtml',
        array('report' => $report, 'active' => 'view')
    ) ?>
    <?php endif ?>

    <h1><?= $this->escapeHtml($report->getName()) ?></h1>

    <p class="reportDescription">
        <?= $report->getDescription() ?>
        <?php if ($dateUpdated = $report->getUpdated()): ?>
            Last updated on <?= $dateUpdated ?>
        <?php endif ?>
    </p>

    <div class="reportItems">
        <?php foreach ($report->getItems() as $item): ?>
            <?= $this->partial(
                'mrss/custom-report/report-item.partial.phtml',
                array('item' => $item, 'buttons' => false)
            ) ?>
            <?php
            if ($itemFootnotes = $item->getCacheFootnotes()) {
                $footnotes[] = array(
                    'name' => $item->getName(),
                    'footnotes' => $itemFootnotes
                );
            }

            ?>
        <?php endforeach ?>
    </div>

    <div style="clear: both; margin-bottom: 30px"></div>

    <?php if (!empty($footnotes) && $report->getDisplayFootnotes()): ?>
        <?= $this->partial(
            'mrss/custom-report/footnotes.partial.phtml',
            array('footnotes' => $footnotes)
        ) ?>
    <?php endif ?>

</div>


