<?php //$this->headScript()->appendFile('http://code.jquery.com/ui/1.10.3/jquery-ui.js') ?>
<?php $this->headScript()->appendFile('/js/subscribe.js') ?>

<?php $this->headLink()->appendStylesheet('/css/ui-lightness/jquery-ui-1.10.3.custom.min.css') ?>
<?php $this->headLink()->appendStylesheet('/css/join.css') ?>

<h2>Join</h2>

<?php
// Add an action and submit button to the form
$form->setAttribute('action', $this->url('join'));
$form->setAttribute('method', 'post');

?>

<?= $this->ztbForm($this->form->prepare()) ?>

