<h1>American Association of University Professors (AAUP) Faculty Compensation Survey Terms and Conditions</h1>

<p><strong>Data Use.</strong>  These data are intended for the internal use of the requesting institution.  Internal use includes posting on a secure institutional website that is not publically viewable, and the transmission to employees and contractors of the institution for use in planning and decision-making. Commercial use of these data are strictly prohibited.  Please do not publish or redistribute these data without permission of the AAUP Research Office.  For questions of use, please contact the AAUP Research Office at aaupfcs@aaup.org.</p>

<p>Users agree that they will not allow access to institutional or aggregate data by unauthorized individuals or other non-users to review, generate benchmark information, learn identities of institutions, or make peer comparisons for commercial, competitive, or any other purposes.  Faculty Compensation Survey aggregate data reports shall not be posted to web sites accessible to the general public or made otherwise available to institutions or individuals. The aggregate data reports are the intellectual property of AAUP Faculty Compensation Survey and shall NOT be considered public record.</p>

<p><strong>Data Quality.</strong>  The AAUP Faculty Compensation Survey collects data from two- and four-year institutions across the United States through an online submission portal. These data are reviewed through our internal verification process, and, wherever the AAUP believes a possible error may have occurred, institutional repre¬sentatives are contacted with a request to review those possible errors.</p>

<p>Nearly all institutions comply with our requests for additional review.  If resubmitted data meet our internal standard, they are approved for inclusion in the Faculty Compensation Survey. Questionable data without an institutional response are not included in the Faculty Compensation Survey.</p>

<p>While the AAUP makes every effort to provide the most accurate data, the Faculty Compensation Survey may include inaccuracies and errors or omissions. Users assume the sole risk and responsibility of making use of these data; under no circumstances will the AAUP be liable to any user for damages arising from use of these data.</p>

<p>The AAUP publishes additions and corrections to the Annual Report on the Economic Status of the Profes¬sion in the July–August issue of Academe (the Bulletin of the American Association of University Professors) and may make modifications to the content at any time.
Should there be an error to the Faculty Compensation Survey, the AAUP will also notify Inside Higher Ed, which publishes data from the survey on its website.</p>

<p><strong>Attribution.</strong> Users shall provide to the Faculty Compensation Survey Research Office an abstract and reference for any published research material resulting from the use of the Faculty Compensation Survey data. Users shall acknowledge in all publications and presentations based on Faculty Compensation Survey data, whether internal, or external, that the source of these data are the "Faculty Compensation Survey."</p>

<p><strong>Acknowledgements of Faculty Compensation Survey Agreement.</strong> I agree that my institution will abide by the Terms and Conditions set out above --including the provision regarding the posting of Faculty Compensation Survey reports that makes them available to non-subscribers --and I understand that my institution will not pay an annual subscription fee for our participation in the Faculty Compensation Survey.</p>

