<h2>Select Payment Type</h2>

<?php if ($this->currentStudy()->getEnrollmentOpen()): ?>

    <div class="well">
        <h3>Option 1: Pay by Credit Card</h3>

        <p>Once your credit card information has been accepted, be sure to click the "Continue" buttons until you are redirected back to this site.</p>

        <?= $this->ztbForm($ccForm->prepare()) ?>
    </div>

    <div class="well">
        <h3>Option 2: Request an Invoice</h3>

        <p>If your institution wishes to receive an invoice by U.S. Mail from our Billing Department, click the "Request an Invoice" button.</p>

        <?= $this->ztbForm($invoiceForm->prepare()) ?>
    </div>

    <div class="well">

    <h3>Option 3: Paid by System</h3>

        <p>If funding is provided by a College System or State Sytem, please enter the name of the College System or State System below and click the "Paid by System" button.</p>

        <?= $this->ztbForm($systemForm->prepare()) ?>
    </div>

<?php endif ?>


<?php if ($this->currentStudy()->getPilotOpen()): ?>

    <div class="well">

        <h3>Pilot Program: Free</h3>

        <p>Participation in the pilot program is free of charge. To complete
            your pilot subscription, click this button:</p>

        <?= $this->ztbForm($pilotForm->prepare()) ?>
    </div>


<?php endif ?>
