<h2>Select Payment Type</h2>

<div class="well">
    <h3>Option 1: Pay by Credit Card</h3>

    <?= $this->ztbForm($ccForm->prepare()) ?>
</div>

<div class="well">
    <h3>Option 2: Request an Invoice</h3>

    <p>If your institution wishes to receive an invoice from our Billing Department, click the "Request an Invoice" button.</p>

    <?= $this->ztbForm($invoiceForm->prepare()) ?>
</div>

<div class="well">

<h3>Option 3: Paid by System</h3>

    <p>If funding is provided by a College System or State Sytem, please enter the name of the College System or State System below and click the "Paid by System" button.</p>

    <?= $this->ztbForm($systemForm->prepare()) ?>
</div>
