<?php /** @var \Mrss\Entity\College $college */ ?>

<?php if ($this->currentStudy(false)->getConfig()->free_to_join): ?>
    <h1>Start the Survey</h1>
<?php else: ?>
    <h1>Renew Your Membership</h1>
<?php endif ?>


<p>Please review the information below and make any necessary changes before continuing.</p>

<div class="row renewForm">
    <p><?= $this->ztbForm($this->form->prepare()) ?></p>
</div>


<div class="row-fluid row renewInfo">
    <div class="span6 col-md-6">
        <p>
            <a href="/institution/edit/renew" class="btn btn-default">Update Institution Information</a>
        </p>

        <dl>
            <dt>Institution</dt>
            <dd><?= $college->getName() ?></dd>

            <dt>IPEDS Unit ID</dt>
            <dd><?= $college->getIpeds() ?></dd>

            <dt>Address</dt>
            <dd><?= $college->getFullAddress() ?></dd>

            <dt>Executive Title</dt>
            <dd><?= $college->getExecTitle() ?></dd>

            <dt>Executive Name</dt>
            <dd><?= $college->getExecFullName() ?></dd>
        </dl>

    </div>

    <div class="span6 col-md-6">

        <p>
            <a href="/institution/users/renew" class="btn btn-default">Update Institution Users</a>
        </p>

        <?php foreach ($college->getUsersByStudy($this->currentStudy()) as $user): ?>
            <dl>
                <dt>Name</dt>
                <dd><?= $user->getFullName() ?></dd>

                <dt>Title</dt>
                <dd><?= $user->getTitle() ?></dd>

                <dt>Email</dt>
                <dd><?= $user->getEmail() ?></dd>

                <dt>Phone</dt>
                <dd><?= $user->getFullPhone() ?></dd>
                <br style="clear:both">
            </dl>
        <?php endforeach ?>

    </div>
</div>

<div class="row">
    <p><?= $this->ztbForm($this->form->prepare()) ?></p>
</div>
