# Save as .codeclimate.yml (note leading .) in project root directory
languages:
  PHP: true
exclude_paths:
- "autoload_classmap.php"
- "config/*"
- "data/*"
- "module/Mrss/config/module.config.php"
- "module/Mrss/Module.php"
- "public/*"
- "debug.php"
- "features/*"
- "module/Mrss/test/Bootstrap.php"
- "module/Mrss/src/Mrss/Service/ImportNccbp.php"
