# Save as .codeclimate.yml (note leading .) in project root directory
languages:
  PHP: true
exclude_paths:
- "config/*"
- "data/*"
- "module/Mrss/config/module.config.php"
- "module/Mrss/Module.php"
