<?php $unique = rand(1, 100); ?>

<ul class="nav pull-right">
    <?php $count = 0 ?>
    <?php foreach ($this->container as $page): ?>
        <?php /* @var $page Zend\Navigation\Page\Mvc */ ?>
        <?php // when using partials we need to manually check for ACL conditions ?>
        <?php if( ! $page->isVisible() || !$this->navigation()->accept($page)) continue; ?>
        <?php $hasChildren = $page->hasPages() ?>
        <?php if( ! $hasChildren): ?>
            <li>
            <a href="<?php echo $page->getHref() ?>"
                <?php echo ($page->isActive()) ? 'class="active"' : '' ?>
                >
                <?php echo $this->translate($page->getLabel()) ?>
            </a>
        <?php else: ?>
            <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <span><?php echo $this->translate($page->getLabel()) ?></span>
                <b class="caret"></b>
            </a>
            <ul class="dropdown-menu" id="page_<?php echo $count ?>_<?php echo
            $unique ?>">
                <?php foreach($page->getPages() as $child): ?>
                    <?php // when using partials we need to manually check for ACL conditions ?>
                    <?php if( ! $child->isVisible() || !$this->navigation()->accept($child)) continue; ?>
                    <li>
                        <a href="<?php echo $child->getHref() ?>">
                            <?php echo $this->translate($child->getLabel()) ?>
                        </a>
                    </li>
                <?php endforeach ?>
            </ul>
        <?php endif ?>
        <?php $count++ ?>
        </li>
    <?php endforeach ?>
</ul>
