<?php /** @var \Mrss\Entity\ChangeSet[] $changeSets */ ?>

<?php

// Data Tables
$this->headScript()->appendFile(
    '/js/jquery.dataTables.min.js',
    'text/javascript'
);
$this->headLink()->appendStylesheet('/css/jquery.dataTables.min.css');
?>

<script>
    <?php $this->headScript()->captureStart() ?>
    $(document).ready(function() {
        $('.observationChanges').dataTable({
            "order": [[0, "desc"]],
            // show X entries options
            "aLengthMenu": [[50, 100, 200, -1], [50, 100, 200, "All"]],
            'iDisplayLength': 100
        });

        $('.heatMapYear, .heatmapTd').css('width', '20px')
    });
    <?php $this->headScript()->captureEnd() ?>
</script>

<h1>Recent Data Changes</h1>

<table class="table observationChanges">
    <thead>
        <tr>
            <th>Timestamp</th>
            <th>College and User</th>
            <th>Method</th>
            <th>Fields</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($changeSets as $changeSet): ?>
        <?php /** \Mrss\Entity\ChangeSet $changeSet */
            $changes = $changeSet->getChanges();
            $field = (count($changeSet->getChanges()) == 1) ? 'field' : 'fields'; ?>
        <tr class="changeSet">
            <td>
                <?= $changeSet->getDate()->format('Y-m-d H:i') ?>
            </td>
            <td>

                <?php if ($changeSet->getObservation()): ?>
                    <?php $college = $changeSet->getObservation()->getCollege() ?>
                    <strong>
                        <a href="<?= $this->url('colleges/view', array('id' => $college->getId())) ?>">
                            <?= $college->getName() ?>
                        </a>
                    </strong>
                    <br>
                    <?php if ($impersonator = $changeSet->getImpersonatingUser()): ?>
                        <?= $impersonator->getFullName() ?>, impersonating
                    <?php endif ?>
                        <?php if ($user = $changeSet->getUser()): ?>
                            <?= $changeSet->getUser()->getFullName() ?>
                        <?php endif ?>

                <?php else: ?>
                    Importer
                <?php endif ?>
            </td>
            <td>
                <?= $changeSet->getEditTypeLabel() ?>
                <?php if ($subObservation = $changeSet->getSubObservation()): ?>
                    in academic division
                    <?= $subObservation->getName() ?>
                <?php endif ?>
            </td>


            <td>
            <div class="changes">
                <?php foreach ($changes as $change): ?>
                    <div class="change row">
                        <div class="col-md-4">
                            <?= $change->getOldValue(true) ?>
                            => <?= $change->getNewValue(true) ?>
                        </div>
                        <div class="col-md-8">
                            <strong class="infotip" title="<?= $change->getBenchmark()->getDescriptiveReportLabel() ?> (<?= $change->getBenchmark()->getBenchmarkGroup()->getName() ?>)">
                                <?= $change->getBenchmark()->getName() ?>
                            </strong>
                        </div>
                    </div>

                <?php endforeach ?>
            </div>
            </td>
        </tr>
    <?php endforeach ?>
    </tbody>
</table>

