<h2>Subscriptions</h2>

<?php if (count($subscriptions)): ?>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Completion</th>
            <th>Institution</th>
            <th>Users</th>
            <th>Subscription Date</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($subscriptions as $subscription): ?>
            <tr>
                <td>
                    <a href="<?= $this->url(
                        'observation',
                        array('id' => $subscription->getObservation()->getId())
                    ) ?>">
                        <?= $this->currentStudy()->getCompletionPercentage(
                            $subscription->getObservation()
                        ) ?>%
                    </a>
                </td>
                <td>
                    <a href="<?= $this->url(
                        'colleges/view',
                        array('id' => $subscription->getCollege()->getId())
                    ) ?>">
                        <?= $subscription->getCollege()->getName() ?>
                    </a>
                </td>

                <td>
                    <?php
                        $userList = array();
                        foreach ($subscription->getCollege()->getUsers() as $user):
                            $name = $user->getFullName();

                            // Wrap in a link
                            $url = $this->url(
                                'users/edit',
                                array('id' => $user->getId())
                            );
                            $item = '<a title="Impersonate this user"
                                href="/admin/user/impersonate/' . $user->getId()
                                . '"><i class="icon icon-fire"></i></a> ';
                            $item .= "<a href='$url'>$name</a>";

                            if ($access = $user->getLastAccess()) {
                                $date = $access->format('Y-m-d H:i');
                                $item .= " ($date)";
                            }
                            $userList[] = $item;
                        endforeach;

                        echo implode('<br>', $userList);

                    ?>
                </td>

                <td>
                    <?= $subscription->getCreated()->format('Y-m-d') ?>
                </td>
            </tr>
        <?php endforeach ?>
    </tbody>
</table>

<?php else: ?>
    <p>No one has signed up yet.</p>
<?php endif ?>
