<h1>Admin Dashboard</h1>

<div class="row">
    <div class="col-md-5">
        <h2>Memberships (<?= $subscriptionCount ?>)</h2>

        <table class="table table-striped table-bordered" id="subscriptions">
            <thead class="thead-inverse">
            <tr>
                <th>Institution</th>
                <th>Users</th>
                <th>Date</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($subscriptions as $subscription): ?>
                <tr>
                    <td>
                        <a href="<?= $this->url(
                            'colleges/view',
                            array('id' => $subscription->getCollege()->getId())
                        ) ?>">
                            <strong><?= $subscription->getCollege()->getNameAndState() ?></strong>
                        </a>
                    </td>

                    <td>
                        <?php
                        $userList = array();
                        $users = $subscription->getCollege()
                            ->getUsersByStudy($this->currentStudy());
                        foreach ($users as $user):
                            $name = $user->getFullName();

                            // Wrap in a link
                            $url = $this->url(
                                'users/edit',
                                array('id' => $user->getId())
                            );
                            $item = '<a title="Impersonate this user"
                                href="/admin/user/impersonate/' . $user->getId()
                                . '"><i class="icon icon-fire glyphicon glyphicon-transfer"></i></a> ';
                            $item .= "<a href='$url'>$name</a>";

                            $userList[] = $item;
                        endforeach;

                        echo implode('<br>', $userList);

                        ?>

                    </td>

                    <td>
                        <?= $subscription->getCreated()->format('m/d/Y') ?><br>
                        <?= $subscription->getCreated()->format('H:i') ?>
                    </td>
                </tr>
            <?php endforeach ?>
            </tbody>
        </table>

        <a href="/admin/memberships"><h3>More...</h3></a>
    </div>








    <div class="col-md-1">
    </div>





    <div class="col-md-5">
        <h2>Recent Data Changes</h2>

        <table class="table table-striped table-bordered observationChanges">
            <thead class="thead-inverse">
            <tr>
                <th>Institution and User</th>
                <th>Method</th>
                <th>Changes</th>
                <th>Date</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($changeSets as $changeSet): ?>
                <?php /** \Mrss\Entity\ChangeSet $changeSet */
                $changes = $changeSet->getChanges();
                $field = (count($changeSet->getChanges()) == 1) ? 'field' : 'fields'; ?>
                <tr class="changeSet">
                    <td>

                        <?php if ($changeSet->getUser()): ?>
                            <?php $college = $changeSet->getUser()->getCollege() ?>
                            <strong>
                                <a href="<?= $this->url('colleges/view', array('id' => $college->getId())) ?>">
                                    <?= $college->getName() ?>
                                </a>
                            </strong>
                            <br>
                            <?php if ($impersonator = $changeSet->getImpersonatingUser()): ?>
                                <?= $impersonator->getFullName() ?>, impersonating
                            <?php endif ?>
                            <?= $changeSet->getUser()->getFullName() ?>

                        <?php else: ?>
                            Importer
                        <?php endif ?>
                    </td>
                    <td>
                        <?= $changeSet->getEditTypeLabel() ?>
                    </td>


                    <td>
                        <?= count($changes); ?>
                    </td>
                    <td>
                        <?= $changeSet->getDate()->format('m/d/Y H:i') ?>
                    </td>

                </tr>
            <?php endforeach ?>
            </tbody>
        </table>

        <a href="/admin/changes"><h3>More...</h3></a>
    </div>

</div>
