<link rel="stylesheet" type="text/css" href="http://cdn.datatables.net/1.10.2/css/jquery.dataTables.css"/>
<script src="http://cdn.datatables.net/1.10.2/js/jquery.dataTables.min.js"></script>

<script>
    $(document).ready(function() {
        $('#subscriptions').dataTable();
    } );
</script>

<?php /** @var \Mrss\Entity\Subscription[] $subscriptions */ ?>

<a href="/admin/changes">Recent data changes</a>

<h2>Subscriptions</h2>

<ul class="nav nav-tabs">
    <?php foreach ($years as $year): ?>
        <li<? if ($year == $currentYear) echo ' class="active"' ?>>
            <a href="<?= $this->url('admin', array('year' => $year)) ?>"><?= $year ?></a>
        </li>
    <?php endforeach ?>
</ul>


<?php if (count($subscriptions)): ?>
<p>
    <?= count($subscriptions) ?> subscriptions, $<?= number_format($total, 2) ?>.
</p>


<table class="table table-striped" id="subscriptions">
    <thead>
        <tr>
            <?php if ($showCompletion): ?>
            <th>Completion</th>
            <?php endif ?>
            <th>Institution</th>
            <th>Users</th>
            <th>Subscription Date</th>
            <th>Payment Method</th>
            <th>Payment Amount</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($subscriptions as $subscription): ?>
            <tr>
                <?php if ($showCompletion): ?>
                <td>
                    <a href="<?= $this->url(
                        'observation',
                        array('id' => $subscription->getObservation()->getId())
                    ) ?>">
                        <?= $this->currentStudy()->getCompletionPercentage(
                            $subscription->getObservation()
                        ) ?>%
                    </a>
                </td>
                <?php endif ?>
                <td>
                    <a href="<?= $this->url(
                        'colleges/view',
                        array('id' => $subscription->getCollege()->getId())
                    ) ?>">
                        <?= $subscription->getCollege()->getName() ?>
                    </a>
                    (<?= $subscription->getCollege()->getState() ?>)
                </td>

                <td>
                    <?php
                        $userList = array();
                        $users = $subscription->getCollege()
                            ->getUsersByStudy($this->currentStudy());
                        foreach ($users as $user):
                            $name = $user->getFullName();

                            // Wrap in a link
                            $url = $this->url(
                                'users/edit',
                                array('id' => $user->getId())
                            );
                            $item = '<a title="Impersonate this user"
                                href="/admin/user/impersonate/' . $user->getId()
                                . '"><i class="icon icon-fire"></i></a> ';
                            $item .= "<a href='$url'>$name</a>";

                            if ($access = $user->getLastAccess()) {
                                $date = $access->format('Y-m-d H:i');
                                $item .= " ($date)";
                            }
                            $userList[] = $item;
                        endforeach;

                        echo implode('<br>', $userList);

                    ?>

                    <br>
                    <a href="<?= $this->url(
                        'users/edit',
                        array(
                            'id' => 'add',
                            'college' => $subscription->getCollege()->getId()
                        )
                    ) ?>"><i class="icon icon-plus"></i> Add User</a>
                </td>

                <td>
                    <?= $subscription->getCreated()->format('Y-m-d') ?>
                </td>
                <td>
                    <?= $subscription->getPaymentMethodForDisplay() ?>
                </td>
                <td>
                    $<?= number_format($subscription->getPaymentAmount(), 2) ?>
                </td>
                <td>
                    <a href="<?= $this->url(
                        'subscription-delete',
                        array('id' => $subscription->getId())
                    ) ?>" class="deleteLink" onclick="return confirm('Are you sure you want to delete this subscription and all of its data?')">
                        delete
                    </a>
                </td>
            </tr>
        <?php endforeach ?>
    </tbody>
</table>


<?php else: ?>
    <p>No one has signed up yet.</p>
<?php endif ?>
