<?php

// Data Tables
$this->headScript()->appendFile(
'/js/jquery.dataTables.min.js',
'text/javascript'
);
$this->headLink()->appendStylesheet('/css/jquery.dataTables.min.css');
?>

<script type="text/javascript">
    // jquery extend function
    $.extend(
        {
            redirectPost: function(location, args)
            {
                var form = '';
                $.each( args, function( key, value ) {
                    form += '<input type="hidden" name="'+key+'" value="'+value+'">';
                });
                $('<form action="'+location+'" method="POST">'+form+'</form>').appendTo('body').submit();
            }
        });

    $(document).ready(function() {
        // Send invoice
        $('.sendLink').click(function() {
            console.log('in click')
            var id = $(this).attr('id').split('-').pop()
            var to = prompt('To whom?')

            var redirect = '/memberships/invoice';
            $.redirectPost(redirect, {id: id, to: to});

            return false
        })


        $('#subscriptions').dataTable({
            "order": [[1, "asc"]],
            'aoColumnDefs': [
                // Don't sort on the action column
                {'bSortable': false, 'aTargets': [6]}
            ],
            // show X entries options
            "aLengthMenu": [[25, 50, 100, -1], [25, 50, 100, "All"]],
            'iDisplayLength': 25
        });

    } );



</script>

<?php /** @var \Mrss\Entity\Subscription[] $subscriptions */ ?>

<p><a href="/admin/changes">Recent data changes</a></p>

<h1>Memberships</h1>

<ul class="nav nav-pills">
    <?php foreach ($years as $year): ?>
        <li<? if ($year == $currentYear) echo ' class="active"' ?>>
            <a href="<?= $this->url('admin/memberships', array('year' => $year)) ?>"><?= $year ?></a>
        </li>
    <?php endforeach ?>
</ul>


<?php if (count($subscriptions)): ?>
<p>
    <?= count($subscriptions) ?> subscriptions, $<?= number_format($total, 2) ?>.
</p>


<table class="table table-striped" id="subscriptions">
    <thead>
        <tr>
            <th>Completion</th>
            <th>Institution</th>
            <th>Users</th>
            <th>Subscription Date</th>
            <th>Payment Method</th>
            <th>Payment Amount</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($subscriptions as $subscription): ?>
            <tr>
                <td>
                    <a href="<?= $this->url(
                        'observation',
                        array('id' => $subscription->getObservation()->getId())
                    ) ?>">
                        <?= $subscription->getCompletion() ?>%
                    </a>
                </td>
                <td>
                    <a href="<?= $this->url(
                        'colleges/view',
                        array('id' => $subscription->getCollege()->getId())
                    ) ?>">
                        <?= $subscription->getCollege()->getNameAndState() ?>
                    </a>
                </td>

                <td>
                    <?php
                        $userList = array();
                        $users = $subscription->getCollege()
                            ->getUsersByStudy($this->currentStudy());
                        foreach ($users as $user):
                            $name = $user->getFullName();

                            // Wrap in a link
                            $url = $this->url(
                                'users/edit',
                                array('id' => $user->getId())
                            );
                            $item = '<a title="Impersonate this user"
                                href="/admin/user/impersonate/' . $user->getId()
                                . '"><i class="icon icon-fire glyphicon glyphicon-transfer"></i></a> ';
                            $item .= "<a href='$url'>$name</a>";

                            if ($access = $user->getLastAccess()) {
                                $date = $access->format('Y-m-d H:i');
                                $item .= " ($date)";
                            }
                            $userList[] = $item;
                        endforeach;

                        echo implode('<br>', $userList);

                    ?>

                    <br>
                    <a href="<?= $this->url(
                        'users/edit',
                        array(
                            'id' => 'add',
                            'college' => $subscription->getCollege()->getId()
                        )
                    ) ?>"><i class="icon icon-plus glyphicon glyphicon-plus"></i> Add User</a>
                </td>

                <td>
                    <?= $subscription->getCreated()->format('Y-m-d') ?>
                </td>
                <td>
                    <?= $subscription->getPaymentMethodForDisplay() ?>
                </td>
                <td>
                    $<?= number_format($subscription->getPaymentAmount(), 2) ?>
                </td>
                <td>
                    <a href="<?= $this->url(
                        'subscription-delete',
                        array('id' => $subscription->getId())
                    ) ?>" class="deleteLink" onclick="return confirm('Are you sure you want to delete this subscription and all of its data?')">
                        delete
                    </a><br>
                    <a href="#" class="sendLink" id="invoice-<?= $subscription->getId() ?>">send invoice</a>
                </td>
            </tr>
        <?php endforeach ?>
    </tbody>
</table>


<?php else: ?>
    <p>No one has signed up yet.</p>
<?php endif ?>
