<h1>Admin Settings</h1>

<ul class="adminSettings">

    <li class="">
        <a href="/admin" title="">
            Overview
        </a>
    </li>

    <li class="">
        <a href="/colleges" title="">
            Cities
        </a>
    </li>

    <li class="">
        <a href="/systems" title="">
            Networks
        </a>
    </li>

    <li class="">
        <a href="/studies" title="">
            Study Setup
        </a>
    </li>

    <li class="">
        <a href="/issues/staff" title="">
            Data Issues
        </a>
    </li>

    <li class="">
        <a href="/reports/calculate" title="">
            Report Calculations
        </a>
    </li>

    <li class="">
        <a href="/reports/custom/admin" title="">
            Custom Report Admin
        </a>
    </li>

    <li class="">
        <a href="/criteria" title="">
            Demographic Criteria
        </a>
    </li>

    <li class="">
        <a href="/pages" title="">
            Pages
        </a>
    </li>

    <li class="">
        <a href="/users/queue" title="">
            User Approval Queue
        </a>
    </li>

    <li class="">
        <a href="/tools" title="">
            Tools
        </a>
    </li>
</ul>
