<h3>Exports</h3>

<h4>Export all data</h4>

<p>
    <?php foreach ($years as $year): ?>
        <a href="<?= $this->url('export', array('action' => 'full', 'year' => $year)) ?>">Export all data for <?= $year ?> </a><br>
    <?php endforeach; ?>

</p>
<br>


<h4>Export users from <?= $this->currentStudy()->getDescription() ?></h4>

<p>
    <?php foreach ($years as $year): ?>
        <a href="<?= $this->url('export', array('action' => 'users', 'year' => $year)) ?>">Export users with memberships for <?= $year ?> </a><br>
    <?php endforeach; ?>
</p>

