<?php
/**
 * This is a special data-entry template that displays this form as a table
 */

$tableConfig = $dataEntryLayout;
$tableConfig2 = $this->currentStudy(false)->getConfig()->data_entry_layout->toArray();
$tableConfig2 = $tableConfig2['4b'];
$showValidationColumns = true;

$this->layout()->setVariable('noWrapper', true);

$colClassConfig = array(
    'professor exp 9-month', 
    'professor cov 9-month', 
    'associate exp 9-month', 
    'associate cov 9-month', 
    'assistant exp 9-month', 
    'assistant cov 9-month', 
    'instructor exp 9-month', 
    'instructor cov 9-month', 
    'lecturer exp 9-month', 
    'lecturer cov 9-month', 
    'no-rank exp 9-month',
    'no-rank cov 9-month',
);

$colClassConfig2 = array(
    'professor exp 12-month', 
    'professor cov 12-month', 
    'associate exp 12-month', 
    'associate cov 12-month', 
    'assistant exp 12-month', 
    'assistant cov 12-month', 
    'instructor exp 12-month', 
    'instructor cov 12-month', 
    'lecturer exp 12-month', 
    'lecturer cov 12-month', 
    'no-rank exp 12-month',
    'no-rank cov 12-month',
);

$colClassConfig3 = array(
    'no-diff exp 9-month',
    'no-diff cov 9-month'
);

$colClassConfig4 = array(
    'no-diff exp 12-month',
    'no-diff cov 12-month'
);

$benefitRowClassesWithLabels = array(
    'Retirement' => 'retirement',
    'Medical' => 'medical',
    'Dental' => 'dental',
    '(Optional) Combined Medical w/ Dental' => 'combined',
    'Disability' => 'disability',
    'Tuition' => 'tuition',
    'FICA' => 'fica',
    'Unemployment' => 'unemployment',
    'Group Life' => 'group-life',
    "Worker's Comp." => 'workers-comp',
    'Other' => 'other'
);
$benefitRowClasses = array_values($benefitRowClassesWithLabels);

$colSpan = 15;
?>

<?= $this->headLink()->appendStylesheet('/css/data-entry-grid.css') ?>
<?= $this->headLink()->appendStylesheet('/css/data-entry.css') ?>

<?php
$this->headScript()->appendFile(
    '/js/data-entry.js?v=3',
    'text/javascript'
); ?>


<div id="content">
    <div class="container-wide">


<?= $this->partial(
    'mrss/observation/data-entry-nav.partial.phtml',
    array(
        'benchmarkGroup' => $benchmarkGroup,
        'benchmarkGroups' => $benchmarkGroups
    )
)
?>

<script>
    // Conversion factor (set in form 1)
    var conversionFactor = <?= ($cf = $form->get('institution_conversion_factor')->getValue()) ? $cf : 1; ?>;


    $(function() {
        updateSalaryTotals();
        updateBenefitPercents();
        updateBenefitAverages();
        $('form input').change(function() {
            updateSalaryTotals();
            updateBenefitPercents();
            updateBenefitAverages();
        })

        updateAggregateToggle();
        $('select#institution_aggregate_benefits').change(function() {
            updateAggregateToggle();
        })
    })

    function updateAggregateToggle()
    {
        // Grab the tables
        var rankedTable = $('#benefitsRanked');
        var aggregateTable = $('#benefitsAggregate');

        // First, hide them both
        rankedTable.hide();
        aggregateTable.hide();

        // Now check the value of the dropdown
        var benefitSetting = $('select#institution_aggregate_benefits').val();

        if (benefitSetting == 'Yes') {
            aggregateTable.show();
        } else if (benefitSetting == 'No') {
            rankedTable.show();
        }
    }

    function updateBenefitPercents()
    {
        $('.benefitsAsPercent').each(function() {
            var cell = $(this);
            var id = cell.attr('id');
            var idParts = id.split(':');
            var salaries = parseFloat(idParts.pop());

            // Trash the first part of the id
            idParts.shift();

            var benefitClass = idParts.join('.');
            benefitClass = '.' + benefitClass + '.exp input';
            var benefitAmount = $(benefitClass).val();

            var percent;
            if (salaries && benefitAmount) {
                percent = Math.round(benefitAmount / salaries * 100 * 100) / 100;
                percent = percent + '%';
            } else {
                percent = '';
            }

            cell.html(percent);

        })
    }

    function updateBenefitAverages()
    {
        $('.benefitsAverage').each(function() {
            var cell = $(this);
            var id = cell.attr('id');
            var idParts = id.split(':');

            // Trash the first part of the id
            idParts.shift();

            var benefitClass = idParts.join('.');
            var countClass = benefitClass;
            benefitClass = '.' + benefitClass + '.exp input';
            countClass = '.' + countClass + '.cov input';

            benefitCost = parseFloat($(benefitClass).val());
            benefitCovered = parseFloat($(countClass).val());

            var result;
            if (benefitCost && benefitCovered) {
                result = Math.round(benefitCost / benefitCovered);
                result = '$' + result;
            } else {
                result = 'CHECK';
            }

            cell.html(result);
        })
    }
</script>


<h1>
    <?= $benchmarkGroup->getName() ?>
</h1>

<?php if ($description = $benchmarkGroup->getDescription()): ?>
    <div class="well">
        <?= $description ?>
    </div>
<?php endif ?>


<?php $form->prepare() ?>


<?= $this->form()->openTag($form) ?>


<p>
<h3>Aggregate Benefits</h3>
        Does Institution Aggregate Benefits?
<?= $this->formElement($form->get('institution_aggregate_benefits')) ?>
</p>

<table class="table table-condensed table-bordered data-entry-grid data-entry-compact" id="benefitsRanked">
    <thead>
    <tr class="splitHeading">
        <td></td>
        <th colspan="2" class="data-entry-red">Professor</th>
        <th colspan="2" class="data-entry-blue">Associate</th>
        <th colspan="2" class="data-entry-red">Assistant</th>
        <th colspan="2" class="data-entry-blue">Instructor</th>
        <th colspan="2" class="data-entry-red">Lecturer</th>
        <th colspan="2" class="data-entry-blue">No Rank</th>
        <th colspan="2" class="data-entry-red">TOTAL</th>
        <?php if ($showValidationColumns): ?>
            <td></td>
            <th colspan="8">Benefits as a Percent of Salary</th>

            <td></td>
            <th colspan="8">Benefits Average</th>

        <?php endif ?>
    </tr>
    <tr class="smallHeading splitHeading data-entry-heading">
        <th></th>
        <th>Total Expenditure</th>
        <th>Number Covered</th>
        <th>Total Expenditure</th>
        <th>Number Covered</th>
        <th>Total Expenditure</th>
        <th>Number Covered</th>
        <th>Total Expenditure</th>
        <th>Number Covered</th>
        <th>Total Expenditure</th>
        <th>Number Covered</th>
        <th>Total Expenditure</th>
        <th>Number Covered</th>
        <th>Total Expenditure</th>
        <th>Number Covered</th>

        <?php if ($showValidationColumns): ?>
            <td></td>
            <td></td>
            <th class="data-entry-red">Professor</th>
            <th class="data-entry-blue">Associate</th>
            <th class="data-entry-red">Assistant</th>
            <th class="data-entry-blue">Instructor</th>
            <th class="data-entry-red">Lecturer</th>
            <th class="data-entry-blue">No Rank</th>
            <th class="data-entry-red">All Ranks</th>

            <td></td>
            <td></td>
            <th class="data-entry-red">Professor</th>
            <th class="data-entry-blue">Associate</th>
            <th class="data-entry-red">Assistant</th>
            <th class="data-entry-blue">Instructor</th>
            <th class="data-entry-red">Lecturer</th>
            <th class="data-entry-blue">No Rank</th>
            <th class="data-entry-red">All Ranks</th>

        <?php endif ?>


    </tr>

    </thead>

    <tbody>
    <?php foreach ($tableConfig as $section): ?>
        <? if (!empty($section['title'])): ?>
            <tr>
                <td class="grid-category" colspan="4"><?= $section['title'] ?></td>
            </tr>
        <?php endif ?>

        <?php $sectionRow = 0; ?>
        <?php foreach ($section['rows'] as $label => $row): ?>
            <tr>
            <?php if (!is_array($row)): ?>
                <?php if ($row == '[total_row_9]' || $row == '[total_row_12]'): ?>
                    <?php $monthNumber = preg_replace('/[^0-9]/', '', $row) ?>
                    <td class="grid-category">TOTAL</td>
                    <?php foreach ($colClassConfig as $class): ?>
                        <?php $classes = explode(' ', $class); ?>
                        <?php $newId = implode('_', $classes); ?>
                        <?php if (in_array('exp', $classes)): ?>
                            <td class="column-total" id="<?= $newId ?>">0</td>
                        <?php else: ?>
                            <td class="column-input-max" id="<?= $newId ?>">0</td>
                        <?php endif ?>
                    <?php endforeach ?>

                    <td class="column-total" id="exp_<?= $monthNumber ?>-month">0</td>
                    <td class="column-max" id="cov_<?= $monthNumber ?>-month">0</td>

                    <?php showValidationColumnsTotal($monthNumber, $observation) ?>

                    <?php $colClassConfig = $colClassConfig2; ?>
                <?php else: ?>
                    <td colspan="<?= $colSpan ?>">
                        <h2 class="data-entry-subheading">
                            <?= $row ?>
                        </h2>
                    </td>
                <?php endif ?>
            <?php else: ?>
                <td class="grid-category <?= (empty($section['rowClass'])) ? '' : $section['rowClass'] ?>">
                    <?= $label ?>
                </td>

                <?php foreach ($row as $i => $field): ?>
                    <?php if (!empty($field)):  ?>
                        <td class="grid-value <?= $colClassConfig[$i] ?> <?= $benefitRowClasses[$sectionRow] ?>"
                            id="<?= $colClassConfig[$i] ?>-<?= $field ?>">
                            <?= $this->simpleFormElement($form->get($field)) ?>
                        </td>
                    <?php else: ?>
                        <td class="emptyCell"></td>
                    <?php endif ?>
                <?php endforeach ?>

                <?php
                $classParts = explode(' ', $colClassConfig[$i - 1]);
                array_shift($classParts);
                array_push($classParts, $benefitRowClasses[$sectionRow]);
                $totalId = implode('_', $classParts);
                ?>
                <td class="column-total" id="<?= $totalId ?>">0</td>

                <?php
                $classParts = explode(' ', $colClassConfig[$i]);
                array_shift($classParts);
                $maxClass = implode(' ', $classParts);
                array_push($classParts, $benefitRowClasses[$sectionRow]);
                $totalId = implode('_', $classParts);
                ?>
                <td class="column-total max-target <?= $maxClass ?>" id="<?= $totalId ?>">0</td>
                <?php $contract = $classParts[1]; ?>
                <?php if ($showValidationColumns) displayValidationColumns($contract, $sectionRow, $observation); ?>

                </tr>

                <tr class="help-text">
                <td class="grid-category"></td>
                <td colspan="<?= count($row) ?>">

                    <?php /* foreach ($row as $i => $field): ?>
                        <?php if (empty($field)) continue ?>
                        <div class="<?= $colClassConfig[$i] ?>-help grid-help">
                            <h5><?= $form->get($field)->getLabel() ?></h5>
                            <?= $form->get($field)->getOption('help-block') ?>
                        </div>
                    <?php endforeach */ ?>

                </td>
                <?php $sectionRow++ ?>
            <?php endif ?>
            </tr>
        <?php endforeach ?>
    <?php endforeach ?>

    <?php foreach ($benefitRowClassesWithLabels as $label => $rowClass): ?>
        <tr>
            <td class="grid-category"><?= $label ?></td>
            <?php foreach ($colClassConfig as $class): ?>
                <?php $class = str_replace(' 12-month', '', $class) . ' ' . $rowClass; ?>
                <?php $classes = explode(' ', $class) ?>
                <?php if (in_array('exp', $classes)): ?>
                    <td id="<?= implode('_', $classes) ?>" class="column-total apply-conversion">0</td>
                <?php else: ?>
                    <td class="column-total max-target <?= implode(' ', $classes) ?>" id="<?= implode('_', $classes) ?>">0</td>
                <?php endif ?>
            <?php endforeach ?>

            <td class="column-total apply-conversion" id="exp_<?= $rowClass ?>">0</td>
            <td class="column-total max-target cov" id="cov_<?= $rowClass ?>">0</td>

        </tr>
    <?php endforeach ?>

    <tr>
        <td class="grid-category">TOTAL</td>
        <?php foreach ($colClassConfig as $class): ?>
            <?php $class = str_replace(' 12-month', '', $class); ?>
            <?php $classes = explode(' ', $class); ?>
            <?php if (in_array('exp', $classes)): ?>
                <td id="<?= implode('_', $classes) ?>" class="column-total apply-conversion">0</td>
            <?php else: ?>
                <td id="<?= implode('_', $classes) ?>" class="column-max">0</td>
            <?php endif ?>
        <?php endforeach ?>

        <td class="column-total apply-conversion" id="exp">0</td>
        <td class="column-max" id="cov">0 @todo</td>

    </tr>


    </tbody>
</table>








<?php $colSpan = 3; ?>



<table class="table table-condensed table-bordered data-entry-grid data-entry-compact" id="benefitsAggregate">
    <thead>
    <tr class="splitHeading">
        <td></td>
        <th colspan="2" class="data-entry-red">UNDIFFERENTIATED RANK</th>
    </tr>
    <tr class="smallHeading splitHeading data-entry-heading">
        <th></th>
        <th>Total Expenditure</th>
        <th>Number Covered</th>
    </tr>

    </thead>

    <tbody>
    <?php foreach ($tableConfig2 as $section): ?>
        <? if (!empty($section['title'])): ?>
            <tr>
                <td class="grid-category" colspan="3"><?= $section['title'] ?></td>
            </tr>
        <?php endif ?>

        <?php $sectionRow = 0; ?>
        <?php foreach ($section['rows'] as $label => $row): ?>
            <tr>
            <?php if (!is_array($row)): ?>
                <?php if ($row == '[total_row_9]' || $row == '[total_row_12]'): ?>
                    <?php $monthNumber = preg_replace('/[^0-9]/', '', $row) ?>
                    <td class="grid-category">TOTAL</td>
                    <?php foreach ($colClassConfig3 as $class): ?>
                        <?php $classes = explode(' ', $class); ?>
                        <?php $newId = implode('_', $classes); ?>
                        <?php if (in_array('exp', $classes)): ?>
                            <td class="column-total" id="<?= $newId ?>">0</td>
                        <?php else: ?>
                            <td class="column-input-max" id="<?= $newId ?>">0</td>
                        <?php endif ?>
                    <?php endforeach ?>

                    <?php $colClassConfig3 = $colClassConfig4; ?>
                <?php else: ?>
                    <td colspan="<?= $colSpan ?>">
                        <h2 class="data-entry-subheading">
                            <?= $row ?>
                        </h2>
                    </td>
                <?php endif ?>
            <?php else: ?>
                <td class="grid-category <?= (empty($section['rowClass'])) ? '' : $section['rowClass'] ?>">
                    <?= $label ?>
                </td>

                <?php foreach ($row as $i => $field): ?>
                    <?php if (!empty($field)):  ?>
                        <td class="grid-value <?= $colClassConfig3[$i] ?> <?= $benefitRowClasses[$sectionRow] ?>"
                            id="<?= $colClassConfig3[$i] ?>-<?= $field ?>">
                            <?= $this->simpleFormElement($form->get($field)) ?>
                        </td>
                    <?php else: ?>
                        <td class="emptyCell"></td>
                    <?php endif ?>
                <?php endforeach ?>
                </tr>

                <tr class="help-text">
                <td class="grid-category"></td>
                <td colspan="<?= count($row) ?>">

                    <?php /* foreach ($row as $i => $field): ?>
                        <?php if (empty($field)) continue ?>
                        <div class="<?= $colClassConfig[$i] ?>-help grid-help">
                            <h5><?= $form->get($field)->getLabel() ?></h5>
                            <?= $form->get($field)->getOption('help-block') ?>
                        </div>
                    <?php endforeach */ ?>

                </td>
                <?php $sectionRow++ ?>
            <?php endif ?>
            </tr>
        <?php endforeach ?>
    <?php endforeach ?>

    <?php foreach ($benefitRowClassesWithLabels as $label => $rowClass): ?>
        <tr>
            <td class="grid-category"><?= $label ?></td>
            <?php foreach ($colClassConfig3 as $class): ?>
                <?php $class = str_replace(' 12-month', '', $class) . ' ' . $rowClass; ?>
                <?php $classes = explode(' ', $class) ?>
                <?php if (in_array('exp', $classes)): ?>
                    <td id="<?= implode('_', $classes) ?>" class="column-total apply-conversion">0</td>
                <?php else: ?>
                    <td class="column-total max-target <?= implode(' ', $classes) ?>" id="<?= implode('_', $classes) ?>">0</td>
                <?php endif ?>
            <?php endforeach ?>

        </tr>
    <?php endforeach ?>


    <tr>
        <td class="grid-category">TOTAL</td>
        <?php foreach ($colClassConfig3 as $class): ?>
            <?php $class = str_replace(' 12-month', '', $class); ?>
            <?php $classes = explode(' ', $class); ?>
            <?php if (in_array('exp', $classes)): ?>
                <td id="<?= implode('_', $classes) ?>" class="column-total apply-conversion">0</td>
            <?php else: ?>
                <td id="<?= implode('_', $classes) ?>" class="column-max">0</td>
            <?php endif ?>
        <?php endforeach ?>
    </tr>


    </tbody>
</table>







<?php if ($this->currentStudy()->getDataEntryOpen()): ?>
    <fieldset id="fieldset-buttons" class="well well-small">
        <div class="control-group" id="control-group-buttons[submit]">
            <div class="controls" id="controls-buttons[submit]">
                <?= $this->formElement($form->get('buttons')->get('submit')) ?>
            </div>
        </div>
        <div class="control-group" id="control-group-buttons[save-edit]">
            <div class="controls" id="controls-buttons[save-edit]">
                <?= $this->formElement($form->get('buttons')->get('save-edit')) ?>
            </div>
        </div>

    </fieldset>
<?php endif ?>

<?= $this->form()->closeTag() ?>
</div>
</div>


<?php

function displayValidationColumns($contract, $sectionRow, $observation)
{
    list($benefit, $benefitLabel) = getBenefit($sectionRow);
    $benefitShort = shortenBenefit($benefit);

    // First, the benefits as percent table

    ?>

    <td></td>
    <td class="grid-category"><?= $benefitLabel ?></td>

    <?php foreach (getRanks() as $rank => $rankLabel): ?>
        <?php
            $salaries = getSalaries($rank, $contract, $observation);
            $rankShort = shortenRank($rank);
        ?>

        <td class="benefitsAsPercent" id="val1:<?= $rankShort ?>:<?= $benefitShort ?>:<?= $contract ?>:<?= $salaries ?>">

        </td>
    <?php endforeach ?>

    <?php $salaries = getSalaries('faculty', $contract, $observation); ?>
    <td class="benefitsAsPercent" id="val:<?= $benefitShort ?>:<?= $contract ?>:<?= $salaries ?>"></td>


    <?php // Now the benefits average table ?>
    <td></td>
    <td class="grid-category"><?= $benefitLabel ?></td>
    <?php foreach (getRanks() as $rank => $rankLabel): ?>
        <?php
        $rankShort = shortenRank($rank);
        ?>

        <td class="benefitsAverage" id="val2:<?= $rankShort ?>:<?= $benefitShort ?>:<?= $contract ?>">

        </td>
    <?php endforeach ?>


    <?php
}

function showValidationColumnsTotal($monthNumber, $observation)
{
    $contract = "$monthNumber-month";

    ?>

        <td></td>
        <td class="grid-category">TOTAL</td>

        <?php foreach (getRanks() as $rank => $rankLabel): ?>
            <?php
            $salaries = getSalaries($rank, $contract, $observation);
            $rankShort = shortenRank($rank);
            ?>

            <td class="benefitsAsPercent" id="val1:<?= $rankShort ?>:<?= $contract ?>:<?= $salaries ?>">

            </td>
        <?php endforeach ?>

        <?php $salaries = getSalaries('faculty', $contract, $observation); ?>
        <td class="benefitsAsPercent" id="val:<?= $contract ?>:<?= $salaries ?>"></td>


    <?php
}

function shortenBenefit($benefit)
{
    $search = array(
        'combined_medical_dental',
        'group_life',
        'worker_comp'
    );

    $replace = array(
        'combined',
        'group-life',
        'workers-comp'
    );

    $shortened = str_replace($search, $replace, $benefit);

    return $shortened;
}

function shortenRank($rank)
{
    $search = array(
        'associate_professor',
        'assistant_professor',
        'no_rank'
    );

    $replace = array(
        'associate',
        'assistant',
        'no-rank'
    );

    $shortened = str_replace($search, $replace, $rank);

    return $shortened;
}

function getRanks() {
    return array(
        'professor' => 'Professor',
        'associate_professor' => 'Associate',
        'assistant_professor' => 'Assistant',
        'instructor' => 'Instructor',
        'lecturer' => 'Lecturer',
        'no_rank' => 'No Rank'
    );
}

function getBenefits()
{
    return array(
        'retirement' => 'Retirement',
        'medical' => 'Medical',
        'dental' => 'Dental',
        'combined_medical_dental' => 'Combined Medical/Dental',
        'disability' => 'Disability',
        'tuition' => 'Tuition',
        'fica' => 'FICA',
        'unemployment' => 'Unemployment',
        'group_life' => 'Group Life',
        'worker_comp' => 'Worker\'s Comp',
        'other' => 'Other'
    );
}

function getSalaries($rank, $contract, $observation)
{
    $contract = str_replace('-', '_', $contract);

    $maleKey = "ft_male_{$rank}_salaries_$contract";
    $femaleKey = "ft_female_{$rank}_salaries_$contract";

    $total = $observation->get($maleKey) + $observation->get($femaleKey);

    return $total;
}

function getBenefit($rowNumber)
{
    $i = 0;
    foreach (getBenefits() as $key => $label) {
        if ($i == $rowNumber) {
            return array($key, $label);
        }
        $i++;
    }
}

