<?php
/**
 * This is a special data-entry template that displays this form as a table
 */

$currentYear = $this->currentStudy()->getCurrentYear();

$tableConfig = array(
    // Faculty
    array(
        'rows' => array(
            'Full-time Faculty on 9-Month Contracts',
            'Professor' => array(
                'ft_number_continuing_professor_standard',
                'ft_current_salary_professor_standard',
                'ft_previous_salary_professor_standard',
            ),
            'Associate' => array(
                'ft_number_continuing_associate_professor_standard',
                'ft_current_salary_associate_professor_standard',
                'ft_previous_salary_associate_professor_standard',
            ),
            'Assistant' => array(
                'ft_number_continuing_assistant_professor_standard',
                'ft_current_salary_assistant_professor_standard',
                'ft_previous_salary_assistant_professor_standard',
            ),
            'Instructor' => array(
                'ft_number_continuing_instructor_standard',
                'ft_current_salary_instructor_standard',
                'ft_previous_salary_instructor_standard',
            ),
            'Lecturer' => array(
                'ft_number_continuing_lecturer_standard',
                'ft_current_salary_lecturer_standard',
                'ft_previous_salary_lecturer_standard',
            ),
            'No Rank' => array(
                'ft_number_continuing_no_rank_standard',
                'ft_current_salary_no_rank_standard',
                'ft_previous_salary_no_rank_standard',
            ),
        ),
    ),
    array(
        'rows' => array(
            'Full-time Faculty on 12-Month Contracts',
            'Professor' => array(
                'ft_number_continuing_professor_12_month',
                'ft_current_salary_professor_12_month',
                'ft_previous_salary_professor_12_month',
            ),
            'Associate' => array(
                'ft_number_continuing_associate_professor_12_month',
                'ft_current_salary_associate_professor_12_month',
                'ft_previous_salary_associate_professor_12_month',
            ),
            'Assistant' => array(
                'ft_number_continuing_assistant_professor_12_month',
                'ft_current_salary_assistant_professor_12_month',
                'ft_previous_salary_assistant_professor_12_month',
            ),
            'Instructor' => array(
                'ft_number_continuing_instructor_12_month',
                'ft_current_salary_instructor_12_month',
                'ft_previous_salary_instructor_12_month',
            ),
            'Lecturer' => array(
                'ft_number_continuing_lecturer_12_month',
                'ft_current_salary_lecturer_12_month',
                'ft_previous_salary_lecturer_12_month',
            ),
            'No Rank' => array(
                'ft_number_continuing_no_rank_12_month',
                'ft_current_salary_no_rank_12_month',
                'ft_previous_salary_no_rank_12_month',
            ),
        ),
    ),
);

$colClassConfig = array('faculty', 'salaries', 'ntt', 'tt', 'tenured');
$colSpan = 6;
?>

<?= $this->headLink()->appendStylesheet('/css/data-entry-grid.css') ?>

<?php
$this->headScript()->appendFile(
    '/js/data-entry.js',
    'text/javascript'
); ?>


<?= $this->partial(
    'mrss/observation/data-entry-nav.partial.phtml',
    array(
        'benchmarkGroup' => $benchmarkGroup,
        'benchmarkGroups' => $benchmarkGroups
    )
)
?>

<h1>
    <?= $benchmarkGroup->getName() ?>
</h1>

<?php if ($description = $benchmarkGroup->getDescription()): ?>
    <div class="well">
        <?= $description ?>
    </div>
<?php endif ?>


<?php $form->prepare() ?>


<?= $this->form()->openTag($form) ?>


<table class="table table-condensed table-bordered data-entry-grid" id="instructionalGrid">
    <thead>
    <tr>
        <th>Academic Rank <?= $currentYear - 3 ?>-<?= $currentYear - 2 ?></th>
        <th>Number of Continuing Faculty</th>
        <th>Current Year (<?= $currentYear - 2 ?>-<?= $currentYear - 1 ?>)</th>
        <th>Previous Year (<?= $currentYear - 3 ?>-<?= $currentYear - 2 ?>)</th>
    </tr>
    </thead>

    <tbody>
    <?php foreach ($tableConfig as $section): ?>
        <? if (!empty($section['title'])): ?>
            <tr>
                <td class="grid-category" colspan="4"><?= $section['title'] ?></td>
            </tr>
        <?php endif ?>

        <?php foreach ($section['rows'] as $label => $row): ?>
            <tr>
            <?php if (!is_array($row)): ?>
                <td colspan="<?= $colSpan ?>">
                    <h2 class="data-entry-subheading">
                        <?= $row ?>
                    </h2>
                </td>
            <?php else: ?>
                <td class="grid-category <?= (empty($section['rowClass'])) ? '' : $section['rowClass'] ?>">
                    <?= $label ?>
                </td>

                <?php foreach ($row as $i => $field): ?>
                    <?php if (!empty($field)):  ?>
                        <td class="grid-value <?= $colClassConfig[$i] ?>-value"
                            id="<?= $colClassConfig[$i] ?>-<?= $field ?>">
                            <?= $this->simpleFormElement($form->get($field)) ?>
                        </td>
                    <?php else: ?>
                        <td class="emptyCell"></td>
                    <?php endif ?>
                <?php endforeach ?>
                </tr>

                <tr class="help-text">
                <td class="grid-category"></td>
                <td colspan="<?= count($row) ?>">

                    <?php foreach ($row as $i => $field): ?>
                        <?php if (empty($field)) continue ?>
                        <div class="<?= $colClassConfig[$i] ?>-help grid-help">
                            <h5><?= $form->get($field)->getLabel() ?></h5>
                            <?= $form->get($field)->getOption('help-block') ?>
                        </div>
                    <?php endforeach ?>

                </td>
            <?php endif ?>
            </tr>
        <?php endforeach ?>
    <?php endforeach ?>

    </tbody>
</table>

<?php if ($this->currentStudy()->getDataEntryOpen()): ?>
    <fieldset id="fieldset-buttons" class="well well-small">
        <div class="control-group" id="control-group-buttons[submit]">
            <div class="controls" id="controls-buttons[submit]">
                <?= $this->formElement($form->get('buttons')->get('submit')) ?>
            </div>
        </div>
    </fieldset>
<?php endif ?>

<?= $this->form()->closeTag() ?>
