<?php
/**
 * This is a special data-entry template that displays this form as a table
 */

$currentYear = $this->currentStudy()->getCurrentYear();

$tableConfig = $dataEntryLayout;

$colClassConfig = array('faculty', 'current', 'previous');
$colSpan = 6;
?>

<?= $this->headLink()->appendStylesheet('/css/data-entry-grid.css') ?>
<?= $this->headLink()->appendStylesheet('/css/data-entry.css') ?>

<?php
$this->headScript()->appendFile(
    '/js/data-entry.js?v=2',
    'text/javascript'
); ?>


<?= $this->partial(
    'mrss/observation/data-entry-nav.partial.phtml',
    array(
        'benchmarkGroup' => $benchmarkGroup,
        'benchmarkGroups' => $benchmarkGroups
    )
)
?>


<script>
    // Conversion factor (set in form 1)
    var conversionFactor = <?= getConversionFactor($observation) ?>;


    $(function() {
        updateSalaryTotals();
        updatePercentageIncrease();
        $('form input').change(function() {
            updateSalaryTotals();
            updatePercentageIncrease();
        })
    })

    function floatFromString(string)
    {
        // Remove commas and spaces
        if (string) {
            string = string.replace(',', '').replace(' ', '')
        }

        return parseFloat(string)
    }

    function updatePercentageIncrease()
    {
        $('.percentage-increase').each(function() {
            var previous = floatFromString($(this).parent().find('.previous input').val());
            var current = floatFromString($(this).parent().find('.current input').val());

            // Handle total rows. They have no inputs
            if ($(this).parent().find('input').length == 0) {
                previous = floatFromString($(this).parent().find('.previous').html());
                current = floatFromString($(this).parent().find('.current').html());
            }

            var increase = 0;
            if (current && previous) {
                increase = ((current - previous) / previous) * 100;
            }

            increase = round(increase, 2);
            increase = increase + '%';
            $(this).html(increase);
        })
    }
</script>

<h1>
    <?= $benchmarkGroup->getName() ?>
</h1>

<?php if ($description = $benchmarkGroup->getDescription()): ?>
    <div class="well">
        <?= $description ?>
    </div>
<?php endif ?>


<?php $form->prepare() ?>


<?= $this->form()->openTag($form) ?>


<table class="table table-condensed table-bordered data-entry-grid" id="instructionalGrid">
    <thead>
    <tr>
        <td colspan="2"></td>
        <th colspan="2">
            Total Salary Outlays
        </th>
        <td></td>
    </tr>
    <tr>
        <th>Academic Rank <?= $currentYear - 2 ?>-<?= $currentYear - 1 ?></th>
        <th>Number of Continuing Faculty</th>
        <th>Current Year (<?= $currentYear - 1 ?>-<?= $currentYear ?>)</th>
        <th>Previous Year (<?= $currentYear - 2 ?>-<?= $currentYear - 1 ?>)</th>
        <th>Percentage Increase</th>
    </tr>
    </thead>

    <tbody>
    <?php foreach ($tableConfig as $section): ?>
        <? if (!empty($section['title'])): ?>
            <tr>
                <td class="grid-category" colspan="4"><?= $section['title'] ?></td>
            </tr>
        <?php endif ?>

        <?php foreach ($section['rows'] as $label => $row): ?>
            <tr>
            <?php if (!is_array($row)): ?>
                <td colspan="<?= $colSpan ?>">
                    <h2 class="data-entry-subheading">
                        <?= $row ?>
                    </h2>
                </td>
            <?php else: ?>
                <td class="grid-category <?= (empty($section['rowClass'])) ? '' : $section['rowClass'] ?>">
                    <?= $label ?>
                </td>

                <?php foreach ($row as $i => $field): ?>
                    <?php if (!empty($field)):  ?>
                        <?php $months = (stristr($field, '12')) ? 12 : 9; ?>
                        <td class="grid-value <?= $colClassConfig[$i] ?> month-<?= $months ?> <?= str_replace(' ', '-', strtolower($label)) ?>"
                            id="<?= $colClassConfig[$i] ?>-<?= $field ?>">
                            <?= $this->simpleFormElement($form->get($field)) ?>
                        </td>
                    <?php else: ?>
                        <td class="emptyCell"></td>
                    <?php endif ?>
                <?php endforeach ?>

                <td class="percentage-increase">
                    0.00%
                </td>

                </tr>

                <tr class="help-text">
                <td class="grid-category"></td>
                <td colspan="<?= count($row) ?>">
                    <?php if (false): ?>
                    <?php foreach ($row as $i => $field): ?>
                        <?php if (empty($field)) continue ?>
                        <div class="<?= $colClassConfig[$i] ?>-help grid-help">
                            <h5><?= $form->get($field)->getLabel() ?></h5>
                            <?= $form->get($field)->getOption('help-block') ?>
                        </div>
                    <?php endforeach ?>
                    <?php endif ?>

                </td>
            <?php endif ?>
            </tr>
        <?php endforeach ?>

        <tr>
            <td class="grid-category">TOTAL</td>
            <td class="column-total faculty" id="faculty_month-<?= $months ?>">0</td>
            <td class="column-total current" id="current_month-<?= $months ?>">0</td>
            <td class="column-total previous" id="previous_month-<?= $months ?>">0</td>
            <td class="percentage-increase">0.00%</td>
        </tr>
    <?php endforeach ?>

        <tr>
            <td colspan="<?= $colSpan ?>">
                <h2 class="data-entry-subheading">
                    Section 3.  9-Month plus 12-Month Converted  (Calculates automatically)
                </h2>
            </td>
        </tr>
        <?php $facultyTypes = array(
            'professor',
            'associate',
            'assistant',
            'instructor',
            'lecturer',
            'no-rank'
        ); ?>
        <?php foreach ($facultyTypes as $type): ?>
        <tr>
            <td class="grid-category"><?= ucwords(str_replace('-', ' ', $type)) ?></td>
            <td class="column-total faculty" id="faculty_<?= $type ?>">0</td>
            <td class="column-total apply-conversion current" id="current_<?= $type ?>">0</td>
            <td class="column-total apply-conversion previous" id="previous_<?= $type ?>">0</td>
            <td class="percentage-increase">0.00%</td>
        </tr>
        <?php endforeach ?>

        <tr>
            <td class="grid-category">TOTAL</td>
            <td class="column-total faculty" id="faculty">0</td>
            <td class="column-total apply-conversion current" id="current">0</td>
            <td class="column-total apply-conversion previous" id="previous">0</td>
            <td class="percentage-increase">0.00%</td>
        </tr>

    </tbody>
</table>

<?php if ($this->currentStudy()->getDataEntryOpen()): ?>
    <fieldset id="fieldset-buttons" class="well well-small">
        <div class="control-group" id="control-group-buttons[submit]">
            <div class="controls" id="controls-buttons[submit]">
                <?= $this->formElement($form->get('buttons')->get('submit')) ?>
            </div>
        </div>
        <div class="control-group" id="control-group-buttons[save-edit]">
            <div class="controls" id="controls-buttons[save-edit]">
                <?= $this->formElement($form->get('buttons')->get('save-edit')) ?>
            </div>
        </div>

    </fieldset>
<?php endif ?>

<?= $this->form()->closeTag() ?>


<?php

function getConversionFactor($observation)
{
    $cf = $observation->get('institution_conversion_factor');
    if (empty($cf)) {
        $cf = 1;
    }

    return $cf;
}
