<?php
/**
 * This is a special data-entry template that displays this form as a table
 */

$tableConfig = array(
    // Faculty
    array(
        'rows' => array(
            'Faculty on 9-Month Contracts (i.e., regardless of number of installments)',
            'Retirement' => array(
                'ft_retirement_expenditure_professor_9_month',
                'ft_retirement_covered_professor_9_month',
                'ft_retirement_expenditure_associate_professor_9_month',
                'ft_retirement_covered_associate_professor_9_month',
                'ft_retirement_expenditure_assistant_professor_9_month',
                'ft_retirement_covered_assistant_professor_9_month',
                'ft_retirement_expenditure_instructor_9_month',
                'ft_retirement_covered_instructor_9_month',
                'ft_retirement_expenditure_lecturer_9_month',
                'ft_retirement_covered_lecturer_9_month',
                'ft_retirement_expenditure_no_rank_9_month',
                'ft_retirement_covered_no_rank_9_month'
            ),
            'Medical' => array(
                'ft_medical_expenditure_professor_9_month',
                'ft_medical_covered_professor_9_month',
                'ft_medical_expenditure_associate_professor_9_month',
                'ft_medical_covered_associate_professor_9_month',
                'ft_medical_expenditure_assistant_professor_9_month',
                'ft_medical_covered_assistant_professor_9_month',
                'ft_medical_expenditure_instructor_9_month',
                'ft_medical_covered_instructor_9_month',
                'ft_medical_expenditure_lecturer_9_month',
                'ft_medical_covered_lecturer_9_month',
                'ft_medical_expenditure_no_rank_9_month',
                'ft_medical_covered_no_rank_9_month'
            ),
            'Dental' => array(
                'ft_dental_expenditure_professor_9_month',
                'ft_dental_covered_professor_9_month',
                'ft_dental_expenditure_associate_professor_9_month',
                'ft_dental_covered_associate_professor_9_month',
                'ft_dental_expenditure_assistant_professor_9_month',
                'ft_dental_covered_assistant_professor_9_month',
                'ft_dental_expenditure_instructor_9_month',
                'ft_dental_covered_instructor_9_month',
                'ft_dental_expenditure_lecturer_9_month',
                'ft_dental_covered_lecturer_9_month',
                'ft_dental_expenditure_no_rank_9_month',
                'ft_dental_covered_no_rank_9_month'
            ),
            '(Optional) Combined Medical w/ Dental' => array(
                'ft_combined_medical_dental_expenditure_professor_9_month',
                'ft_combined_medical_dental_covered_professor_9_month',
                'ft_combined_medical_dental_expenditure_associate_prof_9_month',
                'ft_combined_medical_dental_covered_associate_professor_9_month',
                'ft_combined_medical_dental_expenditure_assistant_prof_9_month',
                'ft_combined_medical_dental_covered_assistant_professor_9_month',
                'ft_combined_medical_dental_expenditure_instructor_9_month',
                'ft_combined_medical_dental_covered_instructor_9_month',
                'ft_combined_medical_dental_expenditure_lecturer_9_month',
                'ft_combined_medical_dental_covered_lecturer_9_month',
                'ft_combined_medical_dental_expenditure_no_rank_9_month',
                'ft_combined_medical_dental_covered_no_rank_9_month'
            ),
            'Disability' => array(
                'ft_disability_expenditure_professor_9_month',
                'ft_disability_covered_professor_9_month',
                'ft_disability_expenditure_associate_professor_9_month',
                'ft_disability_covered_associate_professor_9_month',
                'ft_disability_expenditure_assistant_professor_9_month',
                'ft_disability_covered_assistant_professor_9_month',
                'ft_disability_expenditure_instructor_9_month',
                'ft_disability_covered_instructor_9_month',
                'ft_disability_expenditure_lecturer_9_month',
                'ft_disability_covered_lecturer_9_month',
                'ft_disability_expenditure_no_rank_9_month',
                'ft_disability_covered_no_rank_9_month'
            ),
            'Tuition' => array(
                'ft_tuition_expenditure_professor_9_month',
                'ft_tuition_covered_professor_9_month',
                'ft_tuition_expenditure_associate_professor_9_month',
                'ft_tuition_covered_associate_professor_9_month',
                'ft_tuition_expenditure_assistant_professor_9_month',
                'ft_tuition_covered_assistant_professor_9_month',
                'ft_tuition_expenditure_instructor_9_month',
                'ft_tuition_covered_instructor_9_month',
                'ft_tuition_expenditure_lecturer_9_month',
                'ft_tuition_covered_lecturer_9_month',
                'ft_tuition_expenditure_no_rank_9_month',
                'ft_tuition_covered_no_rank_9_month'
            ),
            'FICA' => array(
                'ft_fica_expenditure_professor_9_month',
                'ft_fica_covered_professor_9_month',
                'ft_fica_expenditure_associate_professor_9_month',
                'ft_fica_covered_associate_professor_9_month',
                'ft_fica_expenditure_assistant_professor_9_month',
                'ft_fica_covered_assistant_professor_9_month',
                'ft_fica_expenditure_instructor_9_month',
                'ft_fica_covered_instructor_9_month',
                'ft_fica_expenditure_lecturer_9_month',
                'ft_fica_covered_lecturer_9_month',
                'ft_fica_expenditure_no_rank_9_month',
                'ft_fica_covered_no_rank_9_month'
            ),
            'Unemployment' => array(
                'ft_unemployment_expenditure_professor_9_month',
                'ft_unemployment_covered_professor_9_month',
                'ft_unemployment_expenditure_associate_professor_9_month',
                'ft_unemployment_covered_associate_professor_9_month',
                'ft_unemployment_expenditure_assistant_professor_9_month',
                'ft_unemployment_covered_assistant_professor_9_month',
                'ft_unemployment_expenditure_instructor_9_month',
                'ft_unemployment_covered_instructor_9_month',
                'ft_unemployment_expenditure_lecturer_9_month',
                'ft_unemployment_covered_lecturer_9_month',
                'ft_unemployment_expenditure_no_rank_9_month',
                'ft_unemployment_covered_no_rank_9_month'
            ),
            'Group Life' => array(
                'ft_group_life_expenditure_professor_9_month',
                'ft_group_life_covered_professor_9_month',
                'ft_group_life_expenditure_associate_professor_9_month',
                'ft_group_life_covered_associate_professor_9_month',
                'ft_group_life_expenditure_assistant_professor_9_month',
                'ft_group_life_covered_assistant_professor_9_month',
                'ft_group_life_expenditure_instructor_9_month',
                'ft_group_life_covered_instructor_9_month',
                'ft_group_life_expenditure_lecturer_9_month',
                'ft_group_life_covered_lecturer_9_month',
                'ft_group_life_expenditure_no_rank_9_month',
                'ft_group_life_covered_no_rank_9_month'
            ),
            'Worker\'s Comp.' => array(
                'ft_worker_comp_expenditure_professor_9_month',
                'ft_worker_comp_covered_professor_9_month',
                'ft_worker_comp_expenditure_associate_professor_9_month',
                'ft_worker_comp_covered_associate_professor_9_month',
                'ft_worker_comp_expenditure_assistant_professor_9_month',
                'ft_worker_comp_covered_assistant_professor_9_month',
                'ft_worker_comp_expenditure_instructor_9_month',
                'ft_worker_comp_covered_instructor_9_month',
                'ft_worker_comp_expenditure_lecturer_9_month',
                'ft_worker_comp_covered_lecturer_9_month',
                'ft_worker_comp_expenditure_no_rank_9_month',
                'ft_worker_comp_covered_no_rank_9_month'
            ),
            'Other' => array(
                'ft_other_expenditure_professor_9_month',
                'ft_other_covered_professor_9_month',
                'ft_other_expenditure_associate_professor_9_month',
                'ft_other_covered_associate_professor_9_month',
                'ft_other_expenditure_assistant_professor_9_month',
                'ft_other_covered_assistant_professor_9_month',
                'ft_other_expenditure_instructor_9_month',
                'ft_other_covered_instructor_9_month',
                'ft_other_expenditure_lecturer_9_month',
                'ft_other_covered_lecturer_9_month',
                'ft_other_expenditure_no_rank_9_month',
                'ft_other_covered_no_rank_9_month'
            ),

        ),
    ),
    array(
        'rows' => array(
            'Faculty on 12-Month Contracts (i.e., on actual basis, no conversion)',
            'Retirement' => array(
                'ft_retirement_expenditure_professor_12_month',
                'ft_retirement_covered_professor_12_month',
                'ft_retirement_expenditure_associate_professor_12_month',
                'ft_retirement_covered_associate_professor_12_month',
                'ft_retirement_expenditure_assistant_professor_12_month',
                'ft_retirement_covered_assistant_professor_12_month',
                'ft_retirement_expenditure_instructor_12_month',
                'ft_retirement_covered_instructor_12_month',
                'ft_retirement_expenditure_lecturer_12_month',
                'ft_retirement_covered_lecturer_12_month',
                'ft_retirement_expenditure_no_rank_12_month',
                'ft_retirement_covered_no_rank_12_month'
            ),
            'Medical' => array(
                'ft_medical_expenditure_professor_12_month',
                'ft_medical_covered_professor_12_month',
                'ft_medical_expenditure_associate_professor_12_month',
                'ft_medical_covered_associate_professor_12_month',
                'ft_medical_expenditure_assistant_professor_12_month',
                'ft_medical_covered_assistant_professor_12_month',
                'ft_medical_expenditure_instructor_12_month',
                'ft_medical_covered_instructor_12_month',
                'ft_medical_expenditure_lecturer_12_month',
                'ft_medical_covered_lecturer_12_month',
                'ft_medical_expenditure_no_rank_12_month',
                'ft_medical_covered_no_rank_12_month'
            ),
            'Dental' => array(
                'ft_dental_expenditure_professor_12_month',
                'ft_dental_covered_professor_12_month',
                'ft_dental_expenditure_associate_professor_12_month',
                'ft_dental_covered_associate_professor_12_month',
                'ft_dental_expenditure_assistant_professor_12_month',
                'ft_dental_covered_assistant_professor_12_month',
                'ft_dental_expenditure_instructor_12_month',
                'ft_dental_covered_instructor_12_month',
                'ft_dental_expenditure_lecturer_12_month',
                'ft_dental_covered_lecturer_12_month',
                'ft_dental_expenditure_no_rank_12_month',
                'ft_dental_covered_no_rank_12_month'
            ),
            '(Optional) Combined Medical w/ Dental' => array(
                'ft_combined_medical_dental_expenditure_professor_12_month',
                'ft_combined_medical_dental_covered_professor_12_month',
                'ft_combined_medical_dental_expenditure_associate_prof_12_month',
                'ft_combined_medical_dental_covered_associate_professor_12_month',
                'ft_combined_medical_dental_expenditure_assistant_prof_12_month',
                'ft_combined_medical_dental_covered_assistant_professor_12_month',
                'ft_combined_medical_dental_expenditure_instructor_12_month',
                'ft_combined_medical_dental_covered_instructor_12_month',
                'ft_combined_medical_dental_expenditure_lecturer_12_month',
                'ft_combined_medical_dental_covered_lecturer_12_month',
                'ft_combined_medical_dental_expenditure_no_rank_12_month',
                'ft_combined_medical_dental_covered_no_rank_12_month'
            ),
            'Disability' => array(
                'ft_disability_expenditure_professor_12_month',
                'ft_disability_covered_professor_12_month',
                'ft_disability_expenditure_associate_professor_12_month',
                'ft_disability_covered_associate_professor_12_month',
                'ft_disability_expenditure_assistant_professor_12_month',
                'ft_disability_covered_assistant_professor_12_month',
                'ft_disability_expenditure_instructor_12_month',
                'ft_disability_covered_instructor_12_month',
                'ft_disability_expenditure_lecturer_12_month',
                'ft_disability_covered_lecturer_12_month',
                'ft_disability_expenditure_no_rank_12_month',
                'ft_disability_covered_no_rank_12_month'
            ),
            'Tuition' => array(
                'ft_tuition_expenditure_professor_12_month',
                'ft_tuition_covered_professor_12_month',
                'ft_tuition_expenditure_associate_professor_12_month',
                'ft_tuition_covered_associate_professor_12_month',
                'ft_tuition_expenditure_assistant_professor_12_month',
                'ft_tuition_covered_assistant_professor_12_month',
                'ft_tuition_expenditure_instructor_12_month',
                'ft_tuition_covered_instructor_12_month',
                'ft_tuition_expenditure_lecturer_12_month',
                'ft_tuition_covered_lecturer_12_month',
                'ft_tuition_expenditure_no_rank_12_month',
                'ft_tuition_covered_no_rank_12_month'
            ),
            'FICA' => array(
                'ft_fica_expenditure_professor_12_month',
                'ft_fica_covered_professor_12_month',
                'ft_fica_expenditure_associate_professor_12_month',
                'ft_fica_covered_associate_professor_12_month',
                'ft_fica_expenditure_assistant_professor_12_month',
                'ft_fica_covered_assistant_professor_12_month',
                'ft_fica_expenditure_instructor_12_month',
                'ft_fica_covered_instructor_12_month',
                'ft_fica_expenditure_lecturer_12_month',
                'ft_fica_covered_lecturer_12_month',
                'ft_fica_expenditure_no_rank_12_month',
                'ft_fica_covered_no_rank_12_month'
            ),
            'Unemployment' => array(
                'ft_unemployment_expenditure_professor_12_month',
                'ft_unemployment_covered_professor_12_month',
                'ft_unemployment_expenditure_associate_professor_12_month',
                'ft_unemployment_covered_associate_professor_12_month',
                'ft_unemployment_expenditure_assistant_professor_12_month',
                'ft_unemployment_covered_assistant_professor_12_month',
                'ft_unemployment_expenditure_instructor_12_month',
                'ft_unemployment_covered_instructor_12_month',
                'ft_unemployment_expenditure_lecturer_12_month',
                'ft_unemployment_covered_lecturer_12_month',
                'ft_unemployment_expenditure_no_rank_12_month',
                'ft_unemployment_covered_no_rank_12_month'
            ),
            'Group Life' => array(
                'ft_group_life_expenditure_professor_12_month',
                'ft_group_life_covered_professor_12_month',
                'ft_group_life_expenditure_associate_professor_12_month',
                'ft_group_life_covered_associate_professor_12_month',
                'ft_group_life_expenditure_assistant_professor_12_month',
                'ft_group_life_covered_assistant_professor_12_month',
                'ft_group_life_expenditure_instructor_12_month',
                'ft_group_life_covered_instructor_12_month',
                'ft_group_life_expenditure_lecturer_12_month',
                'ft_group_life_covered_lecturer_12_month',
                'ft_group_life_expenditure_no_rank_12_month',
                'ft_group_life_covered_no_rank_12_month'
            ),
            'Worker\'s Comp.' => array(
                'ft_worker_comp_expenditure_professor_12_month',
                'ft_worker_comp_covered_professor_12_month',
                'ft_worker_comp_expenditure_associate_professor_12_month',
                'ft_worker_comp_covered_associate_professor_12_month',
                'ft_worker_comp_expenditure_assistant_professor_12_month',
                'ft_worker_comp_covered_assistant_professor_12_month',
                'ft_worker_comp_expenditure_instructor_12_month',
                'ft_worker_comp_covered_instructor_12_month',
                'ft_worker_comp_expenditure_lecturer_12_month',
                'ft_worker_comp_covered_lecturer_12_month',
                'ft_worker_comp_expenditure_no_rank_12_month',
                'ft_worker_comp_covered_no_rank_12_month'
            ),
            'Other' => array(
                'ft_other_expenditure_professor_12_month',
                'ft_other_covered_professor_12_month',
                'ft_other_expenditure_associate_professor_12_month',
                'ft_other_covered_associate_professor_12_month',
                'ft_other_expenditure_assistant_professor_12_month',
                'ft_other_covered_assistant_professor_12_month',
                'ft_other_expenditure_instructor_12_month',
                'ft_other_covered_instructor_12_month',
                'ft_other_expenditure_lecturer_12_month',
                'ft_other_covered_lecturer_12_month',
                'ft_other_expenditure_no_rank_12_month',
                'ft_other_covered_no_rank_12_month'
            ),

        ),
    ),
    /*array(
        'rows' => array(

        )
    )*/
);

$colClassConfig = array(
    'professor_exp', 
    'professor_cov', 
    'associate_exp', 
    'associate_cov', 
    'assistant_exp', 
    'assistant_cov', 
    'instructor_exp', 
    'instructor_cov', 
    'lecturer_exp', 
    'lecturer_cov', 
    'no_rank_exp', 
    'no_rank_cov',
);

$colSpan = 13;
?>

<?= $this->headLink()->appendStylesheet('/css/data-entry-grid.css') ?>

<?php
$this->headScript()->appendFile(
    '/js/data-entry.js',
    'text/javascript'
); ?>


<?= $this->partial(
    'mrss/observation/data-entry-nav.partial.phtml',
    array(
        'benchmarkGroup' => $benchmarkGroup,
        'benchmarkGroups' => $benchmarkGroups
    )
)
?>

<h1>
    <?= $benchmarkGroup->getName() ?>
</h1>

<?php if ($description = $benchmarkGroup->getDescription()): ?>
    <div class="well">
        <?= $description ?>
    </div>
<?php endif ?>


<?php $form->prepare() ?>


<?= $this->form()->openTag($form) ?>


<p>
<h3>Conversion factor (if entering 12-month data)</h3>
The 12 to 9 month conversion factor for this institution:
<?= $this->formElement($form->get('institution_conversion_factor')) ?>
</p>

<table class="table table-condensed table-bordered data-entry-grid" id="instructionalGrid">
    <thead>
    <tr class="splitHeading">
        <th></th>
        <th colspan="2">Professor</th>
        <th colspan="2">Associate</th>
        <th colspan="2">Assistant</th>
        <th colspan="2">Instructor</th>
        <th colspan="2">Lecturer</th>
        <th colspan="2">No Rank</th>
    </tr>
    <tr class="smallHeading splitHeading">
        <th></th>
        <th>Total Expenditure</th>
        <th>Number Covered</th>
        <th>Total Expenditure</th>
        <th>Number Covered</th>
        <th>Total Expenditure</th>
        <th>Number Covered</th>
        <th>Total Expenditure</th>
        <th>Number Covered</th>
        <th>Total Expenditure</th>
        <th>Number Covered</th>
        <th>Total Expenditure</th>
        <th>Number Covered</th>
    </tr>

    </thead>

    <tbody>
    <?php foreach ($tableConfig as $section): ?>
        <? if (!empty($section['title'])): ?>
            <tr>
                <td class="grid-category" colspan="4"><?= $section['title'] ?></td>
            </tr>
        <?php endif ?>

        <?php foreach ($section['rows'] as $label => $row): ?>
            <tr>
            <?php if (!is_array($row)): ?>
                <td colspan="<?= $colSpan ?>">
                    <h2 class="data-entry-subheading">
                        <?= $row ?>
                    </h2>
                </td>
            <?php else: ?>
                <td class="grid-category <?= (empty($section['rowClass'])) ? '' : $section['rowClass'] ?>">
                    <?= $label ?>
                </td>

                <?php foreach ($row as $i => $field): ?>
                    <?php if (!empty($field)):  ?>
                        <td class="grid-value <?= $colClassConfig[$i] ?>-value"
                            id="<?= $colClassConfig[$i] ?>-<?= $field ?>">
                            <?= $this->simpleFormElement($form->get($field)) ?>
                        </td>
                    <?php else: ?>
                        <td class="emptyCell"></td>
                    <?php endif ?>
                <?php endforeach ?>
                </tr>

                <tr class="help-text">
                <td class="grid-category"></td>
                <td colspan="<?= count($row) ?>">

                    <?php /* foreach ($row as $i => $field): ?>
                        <?php if (empty($field)) continue ?>
                        <div class="<?= $colClassConfig[$i] ?>-help grid-help">
                            <h5><?= $form->get($field)->getLabel() ?></h5>
                            <?= $form->get($field)->getOption('help-block') ?>
                        </div>
                    <?php endforeach */ ?>

                </td>
            <?php endif ?>
            </tr>
        <?php endforeach ?>
    <?php endforeach ?>

    </tbody>
</table>

<?php if ($this->currentStudy()->getDataEntryOpen()): ?>
    <fieldset id="fieldset-buttons" class="well well-small">
        <div class="control-group" id="control-group-buttons[submit]">
            <div class="controls" id="controls-buttons[submit]">
                <?= $this->formElement($form->get('buttons')->get('submit')) ?>
            </div>
        </div>
    </fieldset>
<?php endif ?>

<?= $this->form()->closeTag() ?>
