<?php
/**
 * This is a special data-entry template that displays this form as a table
 */

$tableConfig = $dataEntryLayout;

$colClassConfig = array('male faculty month-9', 'male salaries month-9', 'male ntt month-9', 'male tt month-9', 'male tenured month-9', 'female faculty month-9', 'female salaries month-9', 'female ntt month-9', 'female tt month-9', 'female tenured month-9');
$colClassConfig12 = array('male faculty month-12', 'male salaries month-12', 'male ntt month-12', 'male tt month-12', 'male tenured month-12', 'female faculty month-12', 'female salaries month-12', 'female ntt month-12', 'female tt month-12', 'female tenured month-12');
$colSpan = 11;
?>

<?= $this->headLink()->appendStylesheet('/css/data-entry-grid.css') ?>
<?= $this->headLink()->appendStylesheet('/css/data-entry.css') ?>


<?php
$this->headScript()->appendFile(
    '/js/data-entry.js',
    'text/javascript'
); ?>


<?= $this->partial(
    'mrss/observation/data-entry-nav.partial.phtml',
    array(
        'benchmarkGroup' => $benchmarkGroup,
        'benchmarkGroups' => $benchmarkGroups
    )
)
?>

<script>
    $(function() {
        updateSalaryTotals()
        $('form input').change(function() {
            updateSalaryTotals()
        })
    })
</script>

<h1>
    <?= $benchmarkGroup->getName() ?>
</h1>

<?php if ($description = $benchmarkGroup->getDescription()): ?>
    <div class="well">
        <?= $description ?>
    </div>
<?php endif ?>


<?php $form->prepare() ?>


<?= $this->form()->openTag($form) ?>

<?php if (false): ?>
<h3>Conversion factor (if entering 12-month data)</h3>
<p>
    The 12 to 9 month conversion factor for this institution:
    <?= $this->formElement($form->get('institution_conversion_factor')) ?>
</p>
<?php endif ?>


<table class="table table-condensed table-bordered data-entry-grid" id="instructionalGrid">
    <thead>
    <tr>
        <td></td>
        <th colspan="5" class="data-entry-blue">Men</th>
        <th colspan="5" class="data-entry-red">Women</th>
    </tr>
    <tr class="data-entry-heading">
        <th>Academic Rank</th>
        <th>Number of Faculty</th>
        <th>Total Contracted Salaries ($)</th>
        <th>Non-tenure-track</th>
        <th>On Tenure-track</th>
        <th class="data-entry-border-right">Tenured</th>
        <th>Number of Faculty</th>
        <th>Total Contracted Salaries ($)</th>
        <th>Non-tenure-track</th>
        <th>On Tenure-track</th>
        <th>Tenured</th>
    </tr>
    </thead>

    <tbody>
    <?php foreach ($tableConfig as $section): ?>
        <? if (!empty($section['title'])): ?>
            <tr>
                <td class="grid-category" colspan="4"><?= $section['title'] ?></td>
            </tr>
        <?php endif ?>

        <?php foreach ($section['rows'] as $label => $row): ?>
            <tr>
            <?php if (!is_array($row)): ?>
                <?php if ($row == '[total_row_9]'): ?>
                    <td class="grid-category">TOTAL</td>
                    <td class="column-total" id="male_faculty_month-9">0</td>
                    <td class="column-total" id="male_salaries_month-9">0</td>
                    <td class="column-total" id="male_ntt_month-9">0</td>
                    <td class="column-total" id="male_tt_month-9">0</td>
                    <td class="column-total data-entry-border-right" id="male_tenured_month-9">0</td>
                    <td class="column-total" id="female_faculty_month-9">0</td>
                    <td class="column-total" id="female_salaries_month-9">0</td>
                    <td class="column-total" id="female_ntt_month-9">0</td>
                    <td class="column-total" id="female_tt_month-9">0</td>
                    <td class="column-total" id="female_tenured_month-9">0</td>
                    <?php $colClassConfig = $colClassConfig12 ?>
                <?php elseif ($row == '[total_row_12]'): ?>
                    <td class="grid-category">TOTAL</td>
                    <td class="column-total" id="male_faculty_month-12">0</td>
                    <td class="column-total" id="male_salaries_month-12">0</td>
                    <td class="column-total" id="male_ntt_month-12">0</td>
                    <td class="column-total" id="male_tt_month-12">0</td>
                    <td class="column-total data-entry-border-right" id="male_tenured_month-12">0</td>
                    <td class="column-total" id="female_faculty_month-12">0</td>
                    <td class="column-total" id="female_salaries_month-12">0</td>
                    <td class="column-total" id="female_ntt_month-12">0</td>
                    <td class="column-total" id="female_tt_month-12">0</td>
                    <td class="column-total" id="female_tenured_month-12">0</td>
                <?php elseif ($row == '[total_rows_9_12]'): ?>
                    <td class="grid-category">Professor</td>
                    <td class="column-total" id="male_faculty_professor">0</td>
                    <td class="column-total" id="male_salaries_professor">0</td>
                    <td class="column-total" id="male_ntt_professor">0</td>
                    <td class="column-total" id="male_tt_professor">0</td>
                    <td class="column-total data-entry-border-right" id="male_tenured_professor">0</td>
                    <td class="column-total" id="female_faculty_professor">0</td>
                    <td class="column-total" id="female_salaries_professor">0</td>
                    <td class="column-total" id="female_ntt_professor">0</td>
                    <td class="column-total" id="female_tt_professor">0</td>
                    <td class="column-total" id="female_tenured_professor">0</td>
                    </tr><tr>
                    <td class="grid-category">Associate</td>
                    <td class="column-total" id="male_faculty_associate">0</td>
                    <td class="column-total" id="male_salaries_associate">0</td>
                    <td class="column-total" id="male_ntt_associate">0</td>
                    <td class="column-total" id="male_tt_associate">0</td>
                    <td class="column-total data-entry-border-right" id="male_tenured_associate">0</td>
                    <td class="column-total" id="female_salaries_associate">0</td>
                    <td class="column-total" id="female_salaries_associate">0</td>
                    <td class="column-total" id="female_ntt_associate">0</td>
                    <td class="column-total" id="female_tt_associate">0</td>
                    <td class="column-total" id="female_tenured_associate">0</td>
                    </tr><tr>
                    <td class="grid-category">Assistant</td>
                    <td class="column-total" id="male_faculty_assistant">0</td>
                    <td class="column-total" id="male_salaries_assistant">0</td>
                    <td class="column-total" id="male_ntt_assistant">0</td>
                    <td class="column-total" id="male_tt_assistant">0</td>
                    <td class="column-total data-entry-border-right" id="male_tenured_assistant">0</td>
                    <td class="column-total" id="female_salaries_assistant">0</td>
                    <td class="column-total" id="female_salaries_assistant">0</td>
                    <td class="column-total" id="female_ntt_assistant">0</td>
                    <td class="column-total" id="female_tt_assistant">0</td>
                    <td class="column-total" id="female_tenured_assistant">0</td>
                    </tr><tr>
                    <td class="grid-category">Instructor</td>
                    <td class="column-total" id="male_faculty_instructor">0</td>
                    <td class="column-total" id="male_salaries_instructor">0</td>
                    <td class="column-total" id="male_ntt_instructor">0</td>
                    <td class="column-total" id="male_tt_instructor">0</td>
                    <td class="column-total data-entry-border-right" id="male_tenured_instructor">0</td>
                    <td class="column-total" id="female_salaries_instructor">0</td>
                    <td class="column-total" id="female_salaries_instructor">0</td>
                    <td class="column-total" id="female_ntt_instructor">0</td>
                    <td class="column-total" id="female_tt_instructor">0</td>
                    <td class="column-total" id="female_tenured_instructor">0</td>
                    </tr><tr>
                    <td class="grid-category">Lecturer</td>
                    <td class="column-total" id="male_faculty_lecturer">0</td>
                    <td class="column-total" id="male_salaries_lecturer">0</td>
                    <td class="column-total" id="male_ntt_lecturer">0</td>
                    <td class="column-total" id="male_tt_lecturer">0</td>
                    <td class="column-total data-entry-border-right" id="male_tenured_lecturer">0</td>
                    <td class="column-total" id="female_salaries_lecturer">0</td>
                    <td class="column-total" id="female_salaries_lecturer">0</td>
                    <td class="column-total" id="female_ntt_lecturer">0</td>
                    <td class="column-total" id="female_tt_lecturer">0</td>
                    <td class="column-total" id="female_tenured_lecturer">0</td>
                    </tr><tr>
                    <td class="grid-category">No Rank</td>
                    <td class="column-total" id="male_faculty_no-rank">0</td>
                    <td class="column-total" id="male_salaries_no-rank">0</td>
                    <td class="column-total" id="male_ntt_no-rank">0</td>
                    <td class="column-total" id="male_tt_no-rank">0</td>
                    <td class="column-total data-entry-border-right" id="male_tenured_no-rank">0</td>
                    <td class="column-total" id="female_salaries_no-rank">0</td>
                    <td class="column-total" id="female_salaries_no-rank">0</td>
                    <td class="column-total" id="female_ntt_no-rank">0</td>
                    <td class="column-total" id="female_tt_no-rank">0</td>
                    <td class="column-total" id="female_tenured_no-rank">0</td>
                    </tr><tr>
                    <td class="grid-category">TOTAL</td>
                    <td class="column-total" id="male_faculty">0</td>
                    <td class="column-total" id="male_salaries">0</td>
                    <td class="column-total" id="male_ntt">0</td>
                    <td class="column-total" id="male_tt">0</td>
                    <td class="column-total data-entry-border-right" id="male_tenured">0</td>
                    <td class="column-total" id="female_salaries">0</td>
                    <td class="column-total" id="female_salaries">0</td>
                    <td class="column-total" id="female_ntt">0</td>
                    <td class="column-total" id="female_tt">0</td>
                    <td class="column-total" id="female_tenured">0</td>
                <?php else: ?>
                    <td colspan="<?= $colSpan ?>">
                        <h2 class="data-entry-subheading">
                            <?= $row ?>
                        </h2>
                    </td>
                <?php endif ?>
            <?php else: ?>
                <td class="grid-category <?= (empty($section['rowClass'])) ? '' : $section['rowClass'] ?>">
                    <?= $label ?>
                </td>

                <?php foreach ($row as $i => $field): ?>
                    <?php if (!empty($field)):  ?>
                        <?php $class = ($i == 4) ? 'data-entry-border-right' : ''; ?>
                        <td class="grid-value <?= $colClassConfig[$i] ?> <?= $class ?> <?= str_replace(' ', '-', strtolower($label)) ?>"
                            id="<?= $colClassConfig[$i] ?>-<?= $field ?>">
                            <?= $this->simpleFormElement($form->get($field)) ?>
                        </td>
                    <?php else: ?>
                        <td class="emptyCell"></td>
                    <?php endif ?>
                <?php endforeach ?>
                </tr>

                <tr class="help-text">
                <td class="grid-category"></td>
                <td colspan="<?= count($row) ?>">

                    <?php foreach ($row as $i => $field): ?>
                        <?php if (empty($field)) continue ?>
                        <div class="<?= $colClassConfig[$i] ?>-help grid-help">
                            <h5><?= $form->get($field)->getLabel() ?></h5>
                            <?= $form->get($field)->getOption('help-block') ?>
                        </div>
                    <?php endforeach ?>

                </td>
            <?php endif ?>
            </tr>
        <?php endforeach ?>
    <?php endforeach ?>

    </tbody>
</table>

<?php if ($this->currentStudy()->getDataEntryOpen()): ?>
    <fieldset id="fieldset-buttons" class="well well-small">
        <div class="control-group" id="control-group-buttons[submit]">
            <div class="controls" id="controls-buttons[submit]">
                <?= $this->formElement($form->get('buttons')->get('submit')) ?>
            </div>
        </div>
        <div class="control-group" id="control-group-buttons[save-edit]">
            <div class="controls" id="controls-buttons[save-edit]">
                <?= $this->formElement($form->get('buttons')->get('save-edit')) ?>
            </div>
        </div>

    </fieldset>
<?php endif ?>

<?= $this->form()->closeTag() ?>
