<h2>
    <?php if ($form->get('id')->getValue()): ?>
        Edit a <?= ucwords($this->currentStudy(false)->getConfig()->system_label) ?>
    <?php else: ?>
        Add a <?= ucwords($this->currentStudy(false)->getConfig()->system_label) ?>
    <?php endif ?>

</h2>


<?php
// Add an action and submit button to the form
$form->setAttribute('action', $this->url('systems/add'));
?>

<?= $this->ztbForm($this->form->prepare()) ?>
