<?php /** @var \Mrss\Entity\System[] $systems */ ?>


<div class="btn-group heading-btns">
    <a class="btn btn-default" href="<?= $this->url('systems/add') ?>">
        <i class="glyphicon glyphicon-plus"></i>
        Add a <?= $this->currentStudy(false)->getConfig()->system_label ?>
    </a>
</div>

<h1><?= ucwords($this->currentStudy(false)->getConfig()->system_label) ?>s</h1>

<?php if (!empty($systems)): ?>

    <table class="table">
        <thead>
            <th><?= ucwords($this->currentStudy(false)->getConfig()->system_label) ?></th>
            <th>Members</th>
        </thead>
        <?php foreach ($systems as $system): ?>
            <tr>
                <td>
                    <a href="<?= $this->url('systems/view', array('id' => $system->getId())) ?>">
                        <?= $system->getName() ?>
                    </a>
                </td>
                <td>
                    <?= count($system->getColleges()) ?>
                </td>
            </tr>
        <?php endforeach ?>
    </table>

<?php else: ?>

    <p>There are no systems yet.</p>

<?php endif ?>
