<?php /** @var \Mrss\Entity\System $system */ ?>

<div class="btn-group heading-btns">
    <a class="btn btn-default" href="<?= $this->url('systems/edit', array('id' => $system->getId())) ?>">
        <i class="glyphicon glyphicon-pencil"></i>
        Edit
    </a>

    <?php if ($this->studyConfig()->system_benchmarks): ?>
        <a class="btn btn-default" href="<?= $this->url('structures/edit', array('id' => $system->getDataEntryStructure()->getId())) ?>">
            <i class="glyphicon glyphicon-list"></i>
            Data Entry Measures
        </a>

        <a class="btn btn-default" href="<?= $this->url('structures/edit', array('id' => $system->getReportStructure()->getId())) ?>">
            <i class="glyphicon glyphicon-list"></i>
            Report Measures
        </a>

    <?php endif ?>
</div>

<h1><?= $system->getName() ?></h1>


<div class="btn-group heading-btns">
    <a class="btn btn-default" href="<?= $this->url(
        'systems/addadmin',
        array('system_id' => $system->getId())
    ) ?>">
        <i class="glyphicon glyphicon-plus"></i>
        Add <?= $this->studyConfig()->system_label ?> admin
    </a>
</div>

<h2><?= ucwords($this->studyConfig()->system_label) ?> Admin Users</h2>

<table class="table table-striped table-hover">
    <?php foreach ($system->getAdmins() as $user): ?>
        <tr>
            <td>
                <?php
                $item = '<a title="Impersonate this user"
                                href="/admin/user/impersonate/' . $user->getId()
                    . '"><i class="icon icon-fire glyphicon glyphicon-transfer"></i></a> ';
                $item .= "{$user->getFullName()}";
                echo $item;
                ?>

            </td>
            <td>
                <a href="<?= $this->url(
                    'systems/removeadmin',
                    array('user_id' => $user->getId())
                ) ?>" title="Remove <?= $this->studyConfig()->system_label ?> admin role from this user">
                    X
                </a>
            </td>
        </tr>
    <?php endforeach ?>
</table>


<div class="btn-group heading-btns">
    <a class="btn btn-default" href="<?= $this->url(
        'systems/addadmin',
        array('system_id' => $system->getId(), 'role' => 'system_viewer')
    ) ?>">
        <i class="glyphicon glyphicon-plus"></i>
        Add <?= $this->studyConfig()->system_label ?> viewer
    </a>
</div>

<h2><?= ucwords($this->studyConfig()->system_label) ?> Viewer Users</h2>

<table class="table table-striped table-hover">
    <?php foreach ($system->getViewers() as $user): ?>
        <tr>
            <td>
                <?php
                $item = '<a title="Impersonate this user"
                                href="/admin/user/impersonate/' . $user->getId()
                    . '"><i class="icon icon-fire glyphicon glyphicon-transfer"></i></a> ';
                $item .= "{$user->getFullName()}";
                echo $item;
                ?>

            </td>
            <td>
                <a href="<?= $this->url(
                    'systems/removeadmin',
                    array('user_id' => $user->getId())
                ) ?>" title="Remove system viewer role from this user">
                    X
                </a>
            </td>
        </tr>
    <?php endforeach ?>
</table>


<?php
$instLabel = $this->studyConfig()->institution_label;
$vowels = array('a', 'e', 'i', 'o', 'u');
?>

<div class="btn-group heading-btns">
    <a href="<?= $this->url('systems/addcollege', array('system_id' => $system->getId())) ?>" class="btn btn-default">
        <i class="glyphicon glyphicon-plus"></i>
        Add a<?php if (in_array(strtolower(substr($instLabel, 0, 1)), $vowels)) echo 'n' ?> <?= $instLabel ?>
    </a>
</div>

<h2><?= ucwords($this->studyConfig()->institutions_label) ?></h2>


<?php /*
<table class="table table-striped table-hover">
    <?php foreach ($system->getColleges() as $college): ?>
        <tr>
            <td>
                <?= $college->getName() ?>
            </td>
            <td>
                <a href="<?= $this->url(
                    'systems/removecollege',
                    array('college_id' => $college->getId())
                    ) ?>" title="Remove from system">
                    X
                </a>
            </td>
        </tr>
    <?php endforeach ?>
</table>
 */ ?>


<table class="table table-striped table-hover">
    <?php foreach ($system->getMemberColleges() as $collegeInfo): ?>
        <?php $college = $collegeInfo['college']; ?>
        <tr>
            <td>
                <?= $college->getName() ?>  (<?= implode(', ', $collegeInfo['years']) ?>)
            </td>
            <td>
                <a href="<?= $this->url(
                    'systems/editmember',
                    array(
                        'college_id' => $college->getId(),
                        'system_id' => $system->getId()
                    )
                ) ?>" title="Edit">
                    Edit
                </a>
            </td>
        </tr>
    <?php endforeach ?>
</table>


