<?php /** @var \Mrss\Entity\SubObservation[] $subObservations */ ?>
<?php /** @var \Mrss\Entity\Observation $observation */ ?>
<?php /** @var \Mrss\Entity\BenchmarkGroup $benchmarkGroup */ ?>
<?php /** @var array $totals */ ?>
<?= $this->headLink()->appendStylesheet('/css/data-entry.css?v=2') ?>
<?= $this->headLink()->appendStylesheet('/css/data-entry-grid.css?v=2') ?>

<h3>Check Academic Unit Data</h3>

<a href="<?= $this->url(
    'data-entry/edit',
    array('benchmarkGroup' => $benchmarkGroup->getId())
) ?>">
    Back to Academic Units
</a>


<table class="table table-bordered data-entry-grid">
    <thead>
        <tr>
            <th></th>
            <th colspan="3">Full-Time</th>
            <th colspan="3">Part-Time</th>
        </tr>
        <tr>
            <th>Academic Unit</th>
            <th>Salaries and Benefits</th>
            <th>Number of FTE Faculty</th>
            <th>Student Credit Hours</th>
            <th>Salaries and Benefits</th>
            <th>Number of FTE Faculty</th>
            <th>Student Credit Hours</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($subObservations as $subOb): ?>
            <tr>
                <td><?= $subOb->getName() ?></td>
                <?php foreach ($totals as $key => $total): ?>
                    <?php $benchmark = $benchmarks[$key] ?>
                    <td>
                        <?= $benchmark->getPrefix() ?><?= number_format($subOb->get($key)) ?><?= $benchmark->getSuffix() ?>
                    </td>
                <?php endforeach ?>
            </tr>
        <?php endforeach ?>
        <tr>
            <td>Total from Form 2</td>
            <?php foreach ($totals as $key => $total): ?>
                <?php $benchmark = $benchmarks[$key] ?>
                <td>
                    <?= $benchmark->getPrefix() ?><?= number_format($total) ?><?= $benchmark->getSuffix() ?>
                </td>
            <?php endforeach ?>
        </tr>
        <tr>
            <td>Data Entered in From 1</td>
            <?php foreach ($totals as $key => $total): ?>
                <?php $benchmark = $benchmarks[$key] ?>
                <?php $key = $benchmarkMap[$key] ?>
                <td>
                    <?php $value = $observation->get($key) ?>
                    <?php if ($value !== null): ?>
                        <?= $benchmark->getPrefix() ?><?= number_format($value) ?><?= $benchmark->getSuffix() ?>
                    <?php endif ?>
                </td>
            <?php endforeach ?>
        </tr>
    </tbody>
</table>
