<?php
    /** @var \Mrss\Entity\BenchmarkGroup $benchmarkGroup */
    /** @var \Mrss\Entity\Observation $observation */
?>
<?php
$this->headScript()->appendFile(
    '/js/data-entry.js',
    'text/javascript'
); ?>

<h3>
    <?//= $benchmarkGroup->getName() ?>
    Form 2: Academic Divisions
</h3>

<div class="well">
    <h4>2012-2013 Fiscal Year</h4>
    <br>
    Report this information at the credit instructional academic division.<br>
    <br>
    Leaders (typically deans) of each academic division may provide this information. <a href="/data-entry/import">The download Excel file</a> has sheets that can be distributed to the heads of your academic divisions.<br>
    <br>
    You may report up to ten academic divisions. Use the Add an Academic Division button to generate a page to report for another academic division. If you are unable to report by academic division, you should report for your entire institution.
</div>

<p>
<?php if ($this->currentStudy()->getDataEntryOpen()): ?>
    <?php if (count($observation->getSubObservations()) < $maxAcademicUnits): ?>
    <a href="<?= $this->url(
        'data-entry/edit/subob',
        array('benchmarkGroup' => $benchmarkGroup->getId())
    ) ?>" class="btn btn-default">
        <span class="icon-plus-sign"></span>
        Add an Academic Division
    </a>

    <?php else: ?>
            You have reached your maximum of <?= $maxAcademicUnits ?> academic divisions.
            <a href="/contact">Contact us</a> if you have any questions.
    <?php endif ?>
<?php endif ?>

<span style="padding-left: 20px">
    <a href="/data-entry">Back to data entry overview</a>
</span>

<span style="padding-left: 20px">
    <a href="<?= $this->url(
        'data-entry/edit/check',
        array('benchmarkGroup' => $benchmarkGroup->getId())
    ) ?>">
        Check data
    </a>
</span>

</p>

<h5>Academic Divisions</h5>

<?php $subobs = $observation->getSubObservations() ?>
<?php if (count($subobs)): ?>
<ul class="academicUnits">
    <?php foreach ($subobs as $subob): ?>
        <li>
            <a href="<?= $this->url(
                'data-entry/edit/subob',
                array(
                    'benchmarkGroup' => $benchmarkGroup->getId(),
                    'subId' => $subob->getId()
                )
            ) ?>">
                <?= $subob->getName() ?>
            </a>
            -
            <a href="<?= $this->url(
                'data-entry/edit/subob/delete',
                array(
                    'benchmarkGroup' => $benchmarkGroup->getId(),
                    'subId' => $subob->getId()
                )
            ) ?>" class="deleteLink">
                delete
            </a>
        </li>
    <?php endforeach ?>
</ul>
<?php else: ?>
    <p>You do not have any academic divisions yet. Create one using the button above.</p>
<?php endif ?>

