<?= $this->systemAdmin() ?>

<h3>
    <?= $benchmarkGroup->getName() ?>
</h3>

<div class="well">
    <b><h4>2012-2013 Fiscal Year</h4></b>
    <br>
    Report this information at the for-credit instructional academic unit level (such as division or program) that fits your organization. You may report up to ten academic units. Use the New Page button to create a sheet for each academic unit.<br>
    <br>
    Leaders of each academic unit may provide this information. The download Excel file has sheets that can be distributed to the heads of your academic units (such as division leadership, provosts or other faculty leaders.)<br>
    <br>
    You may report up to ten academic units. If you have more than ten academic units, contact us for assistance.(link to contact form) Use the new page button to generate a page to report for another academic unit. If you are unable to report by academic unit, enter ""Institution Wide"" in the name of the division and report for your institution as a whole.<br>
    <br>
    This form is collected at the academic unit level. Select a unit from the list
    to enter data or create a new unit using the button below.
</div>

<?php if (count($observation->getSubObservations()) <= 10): ?>
<a href="<?= $this->url(
    'data-entry/edit/subob',
    array('benchmarkGroup' => $benchmarkGroup->getId())
) ?>" class="btn">
    <span class="icon-plus-sign"></span>
    Add an Academic Unit
</a>
<?php else: ?>
    <p>
        You have reached your maximum of 10 academic units.
        <a href="/contact">Contact us</a> if you have any questions.
    </p>
<?php endif ?>

<h5>Academic Units</h5>

<?php $subobs = $observation->getSubObservations() ?>
<?php if (count($subobs)): ?>
<ul class="academicUnits">
    <?php foreach ($subobs as $subob): ?>
        <li>
            <a href="<?= $this->url(
                'data-entry/edit/subob',
                array(
                    'benchmarkGroup' => $benchmarkGroup->getId(),
                    'subId' => $subob->getId()
                )
            ) ?>">
                <?= $subob->getName() ?>
            </a>
        </li>
    <?php endforeach ?>
</ul>
<?php else: ?>
    <p>You do not have any academic units yet. Create one using the button above.</p>
<?php endif ?>

