<?php if ($edit): ?>
    <h1>Edit Report Item</h1>
<?php else : ?>
    <h1>Add Item to Report</h1>
<?php endif ?>




<style type="text/css">
    body .explore .form-horizontal .control-label {
        text-align: left;
    }
    body .form-horizontal .controls {
        margin-left: 5px;
    }
    .explore form input, .explore form textarea {
        width: 90%
    }

    .explore .form-horizontal .control-label {
        width: 90%;
        text-align: center;
    }

    .explore .controls {
        /*clear: both;*/
    }
    select {
        width: 80%;
    }

    #control-group-submitButton, #control-group-previewButton, #control-group-cancelButton {
        width: 33%;
        float: right;
        margin-left: 1px;
    }

    #control-group-cancelButton label {
        display: none;
    }

    #control-group-regression, #control-group-content {
        display: none;
    }
</style>

<?php
$this->headLink()->appendStylesheet('/css/custom-report.css');
$this->headLink()->appendStylesheet('/css/chosen.min.css');

$this->headScript()->appendFile(
    '/js/report.js?v=1',
    'text/javascript'
);
$this->headScript()->appendFile(
    '/js/chosen.jquery.min.js?v=1',
    'text/javascript'
);

$this->headScript()->appendFile(
    '/js/explore.js?v=1',
    'text/javascript'
);

$this->headScript()->appendFile(
    '/ckeditor/ckeditor.js?v=1',
    'text/javascript'
);


?>


<?php
// Add an action and submit button to the form
//$form->setAttribute('action', $this->url('reports/custom/addItem', array('id' => $report->getId())));
?>

<div class="explore row row-fluid">
    <div class="span4 col-md-4">
        <?= $this->ztbForm($this->form->prepare()) ?>
    </div>

    <div class="span8 col-md-8">
        <div class="row row-fluid">
            <div id="chart">
                <?php if ($chart): ?>
                    <?= $this->chart($chart) ?>
                <?php endif ?>
            </div>
            
            <div id="text-editor" style="display: none">
                <form action="#">
                    <textarea name="report-item-text-editor" id="report-item-text-editor" cols="30" rows="10">
                        <?= $form->get('content')->getValue() ?>
                    </textarea>
                </form>
            </div>
        </div>

        <div class="row row-fluid">
        <?php if (!empty($footnotes)): ?>
            <?php
            $footnotes = array(
                array(
                    'name' => '',
                    'footnotes' => $footnotes
                )
            );

            echo $this->partial(
                    'mrss/custom-report/footnotes.partial.phtml',
                    array('footnotes' => $footnotes)
                )
            ?>


        <?php endif ?>
        </div>

    </div>

</div>
