<?php if ($edit): ?>
    <h1>Edit Report Item</h1>
<?php else : ?>
    <h1>Add Item to Report</h1>
<?php endif ?>




<style type="text/css">
    select option {
        white-space: pre;
    }
</style>

<?php
$this->headLink()->appendStylesheet('/css/custom-report.css?v=6');
$this->headLink()->appendStylesheet('/css/chosen.min.css');

$this->headScript()->appendFile(
    '/js/report.js?v=4',
    'text/javascript'
);
$this->headScript()->appendFile(
    '/js/chosen.jquery.min.js?v=1',
    'text/javascript'
);

/*$this->headScript()->appendFile(
    '/js/bootstrap-select.js?v=1',
    'text/javascript'
);*/

$this->headScript()->appendFile(
    '/js/explore.js?v=35',// . microtime(1),
    'text/javascript'
);

$this->headScript()->appendFile(
    '/ckeditor/ckeditor.js?v=1',
    'text/javascript'
);

?>

<?php if (!empty($defaultBreakpoints)): ?>
    <script>
        <?php $this->headScript()->captureStart() ?>
        var defaultBreakpoints = <?= json_encode($defaultBreakpoints) ?>;
        var benchmarksByInputType = <?= json_encode($benchmarksByInputType) ?>;
        var peerMembers = <?= json_encode($peerMembers) ?>;
        var originalFormData = <?= json_encode($formData) ?>;
        var selectedExtraBenchmarks = <?= json_encode(array_values($selectedExtraBenchmarks)) ?>;
        //console.log(originalFormData['colleges'])
        <?php $this->headScript()->captureEnd() ?>
    </script>
<?php endif ?>

<?php
// Add an action and submit button to the form
//$form->setAttribute('action', $this->url('reports/custom/addItem', array('id' => $report->getId())));
?>

<div class="explore row row-fluid">
    <div class="span5 col-md-4">
        <?= $this->ztbForm($this->form->prepare()) ?>
    </div>

    <div class="span7 col-md-8 report-item-preview">
        <div class="row row-fluid">
            <div id="chart">
                <?php if ($chart): ?>
                    <?= $this->chart($chart) ?>
                <?php endif ?>
            </div>
            
            <div id="text-editor" style="display: none">
                <form action="#">
                    <textarea name="report-item-text-editor" id="report-item-text-editor" cols="30" rows="10">
                        <?= $form->get('content')->getValue() ?>
                    </textarea>
                </form>
            </div>
        </div>

        <div class="row row-fluid">
        <?php if (!empty($footnotes)): ?>
            <?php
            $footnotes = array(
                array(
                    'name' => '',
                    'footnotes' => $footnotes
                )
            );

            echo $this->partial(
                    'mrss/custom-report/footnotes.partial.phtml',
                    array('footnotes' => $footnotes)
                )
            ?>


        <?php endif ?>
        </div>

    </div>

</div>
