<?php
/** \Mrss\Entity\Criterion[] $criteria  */
?>

<script>
    <?php $this->headScript()->captureStart() ?>
    $(function() {
        // Make benchmrks sortable
        $('tbody.sortable').sortable({
            handle: '.sortHandle',
            update: function (event, ui) {
                var data = $(this).sortable('serialize')

                $.post('/criteria/reorder', data, function(result) {
                    console.log(result)
                    if (result != 'ok') {
                        alert('There was a problem saving your sequence. ');
                    }
                })
            }
        })
    })
    <?php $this->headScript()->captureEnd() ?>
</script>

<style>
    .sortable tr td.sortHandle {
        width: 15px;
    }
</style>

<h1>Demographic Criteria</h1>

<a href="/criteria/add" class="btn btn-default">
    <span class="glyphicon glyphicon-plus"></span>
    Add a Criterion
</a>


<table class="table">
    <tbody class="sortable">
    <?php foreach ($criteria as $criterion): ?>
        <tr id="criteria_<?= $criterion->getId() ?>">
            <td class="sortHandle">
                <span class="icon-move glyphicon glyphicon-move"></span>
            </td>
            <td>
                <?= $criterion->getName() ?>
            </td>
            <td>
                <a href="/criteria/delete/<?= $criterion->getId() ?>">Delete</a>
            </td>
        </tr>
    <?php endforeach ?>
    </tbody>
</table>
