<h1>Account Settings</h1>

<ul class="account-settings">

    <li class="">
        <a href="/institution/edit" title="">
            Manage Your City
        </a>
    </li>

    <li class="">
        <a href="/institution/users" title="">
            Manage Your City's Users
        </a>
    </li>

    <li class="">
        <a href="/peer-groups" title="">
            Manage Your Peer Groups
        </a>
    </li>
</ul>
