<script>
    $(function() {
        // Confirmation for delete button
        $('#deleteButton').click(function() {
            var confirmed = confirm("Are you sure you want to delete the selected user(s)? There is no undo for this and the deleted users do not get notified.");

            return confirmed;
        });

        // Check all
        $('#checkAll').change(function() {
            var checkbox = $(this);
            var checked = checkbox[0].checked;

            $('input[type=checkbox]').each(function() {
                this.checked = checked;
            })
        })
    })
</script>

<?php /** @var \Mrss\Entity\User[] $users */ ?>
<h1>User Approval Queue</h1>

<?php if (empty($users)): ?>
    <p>
        No pending users.
    </p>

<?php else: ?>

<form action="" class="form-horizontal" method="post">
    <table class="table">
        <thead>
            <tr>
                <th>
                    <input type="checkbox" id="checkAll" name="checkAll" title = "Check All" />
                </th>
                <th>Name</th>
                <th>Email</th>
                <th>Institution</th>
            </tr>
        </thead>

        <tbody>
            <?php foreach ($users as $user): ?>
                <tr>
                    <td>
                        <input type="checkbox" name="users[<?= $user->getId() ?>]" />
                    </td>
                    <td>
                        <a href="<?= $this->url('users/edit', array('id' => $user->getId(), 'redirect' => null)) ?>">
                            <?= $user->getFullName() ?>
                        </a>
                    </td>
                    <td>
                        <?= $user->getEmail() ?>
                    </td>
                    <td>
                        <?= $user->getCollege()->getName() ?>
                    </td>
                </tr>
            <?php endforeach ?>
        </tbody>
    </table>

    <fieldset id="fieldset-buttons" class="well well-small submit-fieldset">
        <div class="control-group" id="control-group-submitButton">
            <div class="controls" id="controls-submitButton" style="margin-right: 20px">
                <input type="submit" name="buttons[submit]" class="btn btn-primary" id="submitButton" value="Approve">
            </div>
        </div>

        <div class="control-group" id="control-group-deleteButton">
            <div class="controls" id="controls-deleteButton">
                <input type="submit" name="buttons[delete]" class="btn btn-danger" id="deleteButton" value="Delete">
            </div>
        </div>
    </fieldset>


</form>

<?php endif ?>
