
<img class="img-responsive" id="loginLogo" alt="<?= $this->currentStudy()->getDescription() ?>" src="<?= $this->currentStudy()->getLogo() ?>" title="<?= $this->currentStudy()->getDescription() ?>" />

<h1>Sign In</h1>

<?php
$this->layout()->bodyId = 'loginPage';

// Redirect to /members
if (empty($this->redirect)) {
    $this->redirect = '/members';
}

$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login') . '?redirect=' . $this->redirect);
$form->setAttribute('method', 'post');

$form->get('submit')->setAttribute('class', 'btn btn-primary');


?>

<?php echo $this->form()->openTag($form) ?>

<dl class="zend_form">
    <?php echo $this->formElementErrors($form->get('identity')) ?>

    <dt><?php echo $this->formLabel($form->get('identity')) ?></dt>
    <dd><?php echo $this->formInput($form->get('identity')) ?></dd>

    <dt><?php echo $this->formLabel($form->get('credential')) ?></dt>
    <dd><?php echo $this->formInput($form->get('credential')) ?></dd>

    <?php if ($this->redirect): ?>
        <input type="hidden" name="redirect" value="<?php echo $this->redirect ?>" />
    <?php endif ?>

    <dd><?php echo $this->formButton($form->get('submit')) ?></dd>
</dl>

<?php echo $this->form()->closeTag() ?>

<p class="passwordResetLink"><a href="/reset-password">Get a new password.</a></p>

<?php if ($this->enableRegistration) : ?>
    <p>Not registered? <a href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>">Sign up!</a></p>
<?php endif; ?>

<?php if ($extra = $this->studyConfig()->login_extra_text): ?>
    <p class="passwordResetLink">
        <?= $extra ?>
    </p>
<?php endif ?>

