<?php $this->headScript()->appendFile(
'/js/import.js') ?>

<h2>Import NCCBP</h2>

<p>Import data from the National Community College Benchmark Project.</p>

<form>
    <select name="year" id="year">
        <?php foreach (range(2007, date('Y')) as $year): ?>
            <option value="<?= $year ?>" <?php if ($year == date('Y')) echo ' selected="selected"' ?>><?= $year ?></option>
        <?php endforeach ?>
    </select>
</form>

<div class="row-fluid row">
    <div class="span2 offset10 col-md-2 col-md-offset-10">
        <button class="btn btn-primary" id="importAll">Import All</button>
    </div>
</div>

<?php foreach ($this->imports as $key => $import): ?>
    <div class="row-fluid row paddedTop" id="row-<?= $key ?>">
        <div class="span2 col-md-2">
            <h4><?= $import['label'] ?></h4>
        </div>

        <div class="span8 col-md-8">
            <div class="progress" style="margin-top:7px">
                <div class="bar" style="width: 0%;"></div>
            </div>

            <div class="progressInfo">

            </div>
        </div>

        <div class="span2 col-md-2">
            <button class="btn import-button btn-default" id="import-<?= $key
            ?>">Import</button>

            <span class="progressComplete">

            <span>
        </div>


    </div>
<?php endforeach ?>
