<?php $this->headScript()->appendFile(
'/js/import.js') ?>

<h2>Imports</h2>

<p>Import data from previous studies.</p>



<div class="row-fluid">
    <div class="span2 offset10">
        <button class="btn btn-primary" id="importAll">Import All</button>
    </div>
</div>

<?php foreach ($this->imports as $key => $import): ?>
    <div class="row-fluid paddedTop" id="row-<?= $key ?>">
        <div class="span2">
            <h4><?= $import['label'] ?></h4>
        </div>

        <div class="span8">
            <div class="progress" style="margin-top:7px">
                <div class="bar" style="width: 0%;"></div>
            </div>

            <div class="progressInfo">

            </div>
        </div>

        <div class="span2">
            <button class="btn import-button" id="import-<?= $key
            ?>">Import</button>

            <span class="progressComplete">

            <span>
        </div>


    </div>
<?php endforeach ?>
