Welcome to <?= $this->currentStudy()->getDescription() ?>!

Your user account was created when your institution subscribed to the project. In order to activate your account, please click the link below and then set your password:

<?php echo $this->serverUrl($this->url('zfcuser/resetpassword', array('userId' => $this->record->getUserId(), 'token' => $this->record->getRequestKey()))); ?>


Sincerely,

The staff of the National Higher Education Benchmarking Institute
