Dear <?= $fullName ?>,<br>
<br>
Thank you very much for your participation in the <?= $year ?> <a href="<?= $studyUrl ?>"><?= $studyName ?></a>. Your username for the AAUP Faculty Compensation Survey is your email address. Anytime you need a new password you can reset simply by following the link here: <a href="<?= $resetUrl ?>"><?= $resetUrl ?></a><br>
<br>
If you are interested in purchasing peer compensation reports, complete datasets, or obtaining full access to the Faculty Compensation Survey Results Portal, please contact aaupfcs@aaup.org.<br>
<br>
Should you have any questions, comments, or concerns, please do not hesitate to contact me at jbarnshaw@aaup.org or at 202.737.5900 x3627.<br>
<br>
Regards,<br>
<br>
John<br>
<br>
John Barnshaw, Ph.D.<br>
Senior Program Officer<br>
Senior Higher Education Researcher<br>
American Association of University Professors<br>
1133 19th Street Northwest – Suite 221<br>
Washington, DC, USA 20036<br>
202.737.5900 x3627<br>
jbarnshaw@aaup.org
