Hello <?= $fullName ?>,<br>
<br>
Thank you so much for your membership in the <?= $year ?> <a href="<?= $studyUrl ?>"><?= $studyName ?></a>. Your user name for this project is your email address. Anytime you need a new password you can reset it here: <a href="<?= $resetUrl ?>"><?= $resetUrl ?></a><br>
<br>
If you indicated that you would like us to send you an invoice, please note that it will come by e-mail.<br>
<br>
We appreciate your interest in our projects and hope you will spread the word about the Benchmarking Institute's work. And don't forget our National Benchmarking Conference, where you will learn best practices for using the data from the project, is on April 24-26, 2018, here at the Benchmarking Institute, JCCC, Overland Park, Kansas.<br>
<br>
If you need any assistance, please <a href="<?= $contactUrl ?>">contact us</a>.<br>
<br>
Sincerely,<br>
<br>
<br>
Lou A. Guthrie, PhD<br>
Director | National Higher Education Benchmarking Institute<br>
913-469-8500 Ext. 4019<br>
louguthrie@jccc.edu<br>
<br>
Michelle Taylor<br>
Senior Research Analyst | National Higher Education Benchmarking Institute<br>
913-469-8500 Ext. 3831<br>
michelletaylor@jccc.edu<br>
