We’re very excited to welcome you to the govBenchmark family! By signing up, you are joining a community of members across North America looking to improve their government’s performance through the use of advanced benchmarking software.

Your username to log into govBenchmark will be your email address. To sign in, please first click on the below link to set up your password.

<a href="<?= $resetUrl ?>">Set up my password</a>

Once you have set up your password, don’t forget to also bookmark the login page:
https://app.benchmark.envisio.com/user/login

Questions? Please reach out to our govBenchmark team by sending an email to govbenchmark@envisio.com, or check out our FAQ page here.
