Hello <?= $fullName ?>,<br>
<br>
Thank you so much for your membership in the <?= $year ?> <a href="<?= $studyUrl ?>"><?= $studyName ?></a>. Your user name for this project is your email address. Anytime you need a new password you can reset it here: <a href="<?= $resetUrl ?>"><?= $resetUrl ?></a><br>
<br>
If you need any assistance, please <a href="<?= $contactUrl ?>">contact us</a>.<br>
Hello <?= $fullName ?>,<br>
<br>
Thank you so much for your membership in the <?= $year ?> <a href="<?= $studyUrl ?>"><?= $studyName ?></a>. Your user name for this project is your email address. Anytime you need a new password you can reset it here: <a href="<?= $resetUrl ?>"><?= $resetUrl ?></a><br>
<br>
If you need any assistance, please <a href="<?= $contactUrl ?>">contact us</a>.<br>
