<?php /** @var \Mrss\Entity\Subscription[] $subscriptions */ ?>

<script>
    $(function() {
        setUpCheckboxes();
    });

    function setUpCheckboxes()
    {
        // Trigger it for clicking the checkbox
        $('.paidCheckbox').click(function() {
            var id = $(this).attr('id').split('_');
            var subscriptionId = id.pop();

            auditUpdate(subscriptionId);
        })

        // And changing the notes
        $('.paidNotes').change(function() {
            var id = $(this).attr('id').split('_');
            var subscriptionId = id.pop();

            auditUpdate(subscriptionId);
        })
    }

    function auditUpdate(subscriptionId)
    {
        var checked = $('#paid_' + subscriptionId)[0].checked;

        if (checked) {
            checked = '1';
        } else {
            checked = '0';
        }
        var note = $('#note_' + subscriptionId).val();

        var url = '/tools/audit-update';
        var data = {
            subscriptionId: subscriptionId,
            paid: checked,
            note: note
        };

        $.post(url, data, function(data) {
            if (data != 'ok') {
                alert('Error saving payment checkbox and notes.')
            }
        })
    }
</script>



<h1>Membership Payment Audit</h1>


<ul class="nav nav-pills report-nav">
    <?php foreach ($years as $subYear): ?>
        <li<? if ($subYear == $year) echo ' class="active"' ?>>
            <a href="<?= $this->url('tools/audit', array('year' => $subYear)) ?>"><?= $subYear ?></a>
        </li>
    <?php endforeach ?>
</ul>

<p>
    Memberships: <?= $totalCount ?><br>
    Memberships paid: <?= $paidCount ?>
</p>


<p>Changes are saved automatically.</p>

<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>Institution</th>
            <th>Payment Method</th>
            <th>Payment Amount</th>
            <th>Join Date</th>
            <th>Paid</th>
            <th>Notes</th>
        </tr>
    </thead>
    <tbody>

    <?php foreach ($subscriptions as $subscription): ?>

        <tr>
            <td>
                <a href="<?= $this->url('colleges/view', array('id' => $subscription->getCollege()->getId())) ?>">
                    <?= $subscription->getCollege()->getNameAndState() ?>
                </a>
            </td>

            <td>
                <?= $subscription->getPaymentMethodForDisplay() ?>
            </td>

            <td>
                $<?= number_format($subscription->getPaymentAmount(), 0) ?>
            </td>

            <td>
                <?= $subscription->getCreated()->format('m/d/Y') ?>
            </td>

            <td>
                <input type="checkbox" name="paid[<?= $subscription->getId() ?>]" class="paidCheckbox" id="paid_<?= $subscription->getId() ?>" <?php if ($subscription->getPaid()) echo ' checked="checked"' ?>>
            </td>

            <td>
                <textarea name="paidNotes[<?= $subscription->getId() ?>]" cols="14" rows="3" id="note_<?= $subscription->getId() ?>" class="paidNotes"><?= $subscription->getPaidNotes() ?></textarea>

            </td>
        </tr>

    <?php endforeach ?>

    </tbody>
</table>
