<h2>Tools</h2>

<ul>
    <li>
        <a href="/export">Exports</a> - Various exports
    </li>
    <li>
        <a href="/import">Import</a> - Import from NCCBP
    </li>
    <li>
        <a href="<?= $this->url(
            'tools/exceldiff'
        ) ?>">Process Excel File for Email Blast</a> - Upload an Excel file and get a download of the
        file with column C containing all emails from column A that are not in column
        B. Used for email blasts.
    </li>

    <li>
        <a href="<?= $this->url(
            'users/exportLoginLinks'
        ) ?>">Export One-time Login Links</a> - Download an Excel file of users who belong to the current
        study but have never logged in. Created for NCCBP migration.
    </li>

    <li>
        <a href="<?= $this->url(
            'tools/geocode'
        ) ?>">Geocode Colleges</a> - Use Google Maps API to look up and save latitude and longitude
        based on each college's address.
    </li>

    <li>
        <a href="<?= $this->url(
            'tools/nccbpAudit'
        ) ?>">Audit NCCBP Report Migration</a> - Does the new one match the old one?
    </li>
</ul>

<h2>Status</h2>

<dl>
    <dt>Session Lifetime (GC)</dt>
    <dd><?= round($gc_lifetime / 60 / 60 / 24, 2) ?> days</dd>

</dl>
