<h2>Tools</h2>

<ul>
    <li>
        <a href="/export">Exports</a> - Various exports
    </li>
    <li>
        <a href="/import">Import</a> - Import from NCCBP
    </li>
    <li>
        <a href="<?= $this->url(
            'tools/exceldiff'
        ) ?>">Process Excel File for Email Blast</a> - Upload an Excel file and get a download of the
        file with column C containing all emails from column A that are not in column
        B. Used for email blasts.
    </li>

    <li>
        <a href="<?= $this->url(
            'users/exportLoginLinks'
        ) ?>">Export One-time Login Links</a> - Download an Excel file of users who belong to the current
        study but have never logged in. Created for NCCBP migration.
    </li>

    <li>
        <a href="<?= $this->url(
            'tools/geocode'
        ) ?>">Geocode Colleges</a> - Use Google Maps API to look up and save latitude and longitude
        based on each college's address.
    </li>

    <li>
        <a href="<?= $this->url(
            'tools/calc-completion'
        ) ?>">Calculate Subscription Completion %</a> - All of them.
    </li>

    <!--li>
        <a href="<?= $this->url(
            'tools/nccbpAudit'
        ) ?>">Audit NCCBP Report Migration</a> - Does the new one match the old one?
    </li-->

    <li>
        <a href="<?= $this->url(
            'reports/executive-list'
        ) ?>">List of Executive Reports</a> - One for each college. Paste this list into Automator to print all reports to PDF
    </li>

    <li>
        <a href="<?= $this->url(
            'tools/exec-addresses'
        ) ?>">Download Executive Address List</a> - Excel file
    </li>

    <li>
        <a href="<?= $this->url(
            'tools/best'
        ) ?>">Benchmarks for Strengths/Weaknesses</a> - A list of the benchmarks included in the strengths/weakness report and the best performers report
    </li>
</ul>

<h2>Status</h2>

<dl>
    <dt>Session Lifetime (GC)</dt>
    <dd><?= round($gc_lifetime / 60 / 60 / 24, 2) ?> days</dd>

    <dt>Cookie Lifetime</dt>
    <dd><?= round($cookie_lifetime / 60 / 60 / 24, 2) ?> days</dd>

    <dt>Baseline load time</dt>
    <dd><?= $baseTime ?> seconds</dd>

</dl>

<?php if ($collegesWithNoExec): ?>
    <h3>Colleges With No Executive</h3>
    <ul>
        <?php foreach ($collegesWithNoExec as $college): ?>
            <li>
                <a href="<?= $this->url('colleges/edit', array('id' => $college->getId())) ?>">
                    <?= $college->getName() ?>
                </a>
            </li>
        <?php endforeach ?>
    </ul>

<?php endif ?>
