<h2>Tools</h2>

<ul>
    <li>
        <a href="/tools/audit">Membership Payment Audit</a> - Record which memberships have been invoiced and paid.
    </li>

    <li>
        <a href="/export">Exports</a> - Various exports
    </li>

    <li>
        <a href="<?= $this->url('colleges/import') ?>">Import institutions</a> - Take institutions from an Excel file and insert them into the database.
    </li>

    <li>
        <a href="<?= $this->url('users/import') ?>">Import users</a> - Take users from an Excel file and insert them into the database.
    </li>

    <li>
        <a href="<?= $this->url(
            'tools/exceldiff'
        ) ?>">Process Excel File for Email Blast</a> - Upload an Excel file and get a download of the
        file with column C containing all emails from column A that are not in column
        B. Used for email blasts.
    </li>

    <li>
        <a href="<?= $this->url(
            'users/exportLoginLinks'
        ) ?>">Export One-time Login Links</a> - Download an Excel file of users who belong to the current
        study but have never logged in. Generates password reset links.
    </li>

    <li>
        <a href="<?= $this->url(
            'tools/geocode'
        ) ?>">Geocode Institutions</a> - Use Google Maps API to look up and save latitude and longitude
        based on each institution's address.
    </li>

    <li>
        <a href="<?= $this->url(
            'tools/calc-completion'
        ) ?>">Calculate Subscription Completion %</a> - All of them.
    </li>

    <!--li>
        <a href="<?= $this->url(
            'tools/nccbpAudit'
        ) ?>">Audit NCCBP Report Migration</a> - Does the new one match the old one?
    </li-->

    <li>
        <a href="<?= $this->url(
            'reports/executive-list'
        ) ?>">List of Executive Reports</a> - One for each institution. Paste this list into Automator to print all reports to PDF
    </li>

    <li>
        <a href="<?= $this->url(
            'tools/offsets'
        ) ?>">Manage yearOffset for benchmarks</a>
    </li>

    <li>
        <a href="<?= $this->url(
            'tools/zeros'
        ) ?>">Zeros</a> - When users don't have data, they should leave a field blank. Find the people who are entering 0 instead.
    </li>

    <li>
        <a href="<?= $this->url(
            'tools/exec-addresses'
        ) ?>">Download Executive Address List</a> - Excel file
    </li>

    <li>
        <a href="<?= $this->url(
            'tools/best'
        ) ?>">Benchmarks for Strengths/Weaknesses</a> - A list of the benchmarks included in the strengths/weakness report and the best performers report
    </li>

    <li>
        <a href="<?= $this->url(
            'tools/repair-sequences'
        ) ?>">Repair Benchmark Sequences</a> - Fixes duplicate sequence numbers that cause some benchmarks to disappear from the list.
    </li>
    <li>
        <a href="<?= $this->url(
            'tools/repair-report-sequences'
        ) ?>">Repair Benchmark Report Sequences</a> - Fixes duplicate sequence numbers that cause some benchmarks to disappear from the report.
    </li>
    <li>
        <a href="<?= $this->url(
            'tools/lapsed'
        ) ?>">Download Lapsed Institutions</a> - An Excel file with each institution which was a member in the last two years, but has not joined this year.
    </li>

    <li>
        <a href="<?= $this->url(
            'tools/suppressions'
        ) ?>">Suppression List</a> - A list of the institutions with suppressed forms.
    </li>

    <li>
        <a href="<?= $this->url(
            'tools/analyze-equation'
        ) ?>">Analyze Equation</a> - Calculate one computed benchmark for one institution to troubleshoot the equation.
    </li>
</ul>

<h2>Status</h2>

<dl>
    <dt>Session Save Path </dt>
    <dd><?= $session_save_path ?></dd>

    <dt>Session Lifetime (GC)</dt>
    <dd><?= round($gc_lifetime / 60 / 60 / 24, 2) ?> days</dd>

    <dt>Cookie Lifetime</dt>
    <dd><?= round($cookie_lifetime / 60 / 60 / 24, 2) ?> days</dd>

    <dt>Baseline load time</dt>
    <dd><?= $baseTime ?> seconds</dd>

    <dt>Server load average (1, 5, 15 minutes)</dt>
    <dd><?= $loadAverage ?></dd>

</dl>

<?php if ($collegesWithNoExec): ?>
    <h3>Institutions With No Executive</h3>
    <ul>
        <?php foreach ($collegesWithNoExec as $college): ?>
            <li>
                <a href="<?= $this->url('colleges/edit', array('id' => $college->getId())) ?>">
                    <?= $college->getName() ?>
                </a>
            </li>
        <?php endforeach ?>
    </ul>

<?php endif ?>
