<?php
// Data Tables
$this->headScript()->appendFile(
    '/js/jquery.dataTables.min.js',
    'text/javascript'
);
$this->headLink()->appendStylesheet('/css/jquery.dataTables.min.css');
?>

<script>
    $(document).ready(function() {
        // Data table
        var dataTable = $('#zeros').dataTable({
            order: [[2, 'desc']],
            "aLengthMenu": [[25, 50, 100, -1], [25, 50, 100, "All"]],
            'iDisplayLength': 25

        });
    })
</script>

<ul class="nav nav-pills report-nav">
    <?php foreach ($years as $navYear): ?>
        <li<? if ($year == $navYear) echo ' class="active"' ?>>
            <a href="<?= $this->url('tools/zeros', array('year' => $navYear)) ?>"><?= $navYear ?></a>
        </li>
    <?php endforeach ?>
</ul>

<h1>Zeros in the Data</h1>


<table class="table table-striped" id="zeros">
    <thead>
        <tr>
            <th>College</th>
            <th>Emails</th>
            <th>Zeros</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($report as $row): ?>
            <tr>
                <td><?= $row['college'] ?></td>
                <td><?= $row['emails'] ?></td>
                <td><?= $row['zeros'] ?></td>
            </tr>
        <?php endforeach ?>
    </tbody>
</table>
