<div class="page-header">
    <h2>Glossary of Terms</h2>

</div>

<div style="margin: 20px">
    <div class="row">
        <div class="span3">
            <strong>Term</strong>
        </div>
        <div class="span8">
            <strong>Definition</strong>
        </div>
    </div>
    <hr class="hr-themed">
    <br>
    <div class="row small">
        <div class="span3">
            <strong>Client Satisfaction</strong>
        </div>
        <div class="span8">
            Annual contract training client overall satisfaction rates with training courses/programs for the most recent completed fiscal year. Use the percentage of Very Satisfied &amp; Satisfied on a 5-point scale ranging from Very Satisfied to Very Dissatisfied.        </div>
    </div>
    <br>
    <hr class="hr-themed">
    <br>
    <div class="row small">
        <div class="span3">
            <strong>Credit Enrollment</strong>
        </div>
        <div class="span8">
            Fall unduplicated credit enrollment.        </div>
    </div>
    <br>
    <hr class="hr-themed">
    <br>
    <div class="row small">
        <div class="span3">
            <strong>Duplicated Enrollment</strong>
        </div>
        <div class="span8">
            Duplicated non-credit workforce training participant headcount for the most recent completed fiscal year.        </div>
    </div>
    <br>
    <hr class="hr-themed">
    <br>
    <div class="row small">
        <div class="span3">
            <strong>Number of Industry Recognized Credentials Awarded</strong>
        </div>
        <div class="span8">
            Number of state, national, or industry recognized credentials earned by non-credit workforce training students in the most recent completed fiscal year.        </div>
    </div>
    <br>
    <hr class="hr-themed">
    <br>
    <div class="row small">
        <div class="span3">
            <strong>Number of Organizations Served</strong>
        </div>
        <div class="span8">
            Unduplicated number of organizations for which workforce training was provided. (on- or off-campus, online, as distance learning or on the organization's site for the most recent completed fiscal year).        </div>
    </div>
    <br>
    <hr class="hr-themed">
    <br>
    <div class="row small">
        <div class="span3">
            <strong>Number of Returning Organizations</strong>
        </div>
        <div class="span8">
            An organization that receives workforce training in the current fiscal year and at least once previously.        </div>
    </div>
    <br>
    <hr class="hr-themed">
    <br>
    <div class="row small">
        <div class="span3">
            <strong>Number of Returning Students</strong>
        </div>
        <div class="span8">
            An individual who receives workforce training in the current fiscal year and at least once previously.        </div>
    </div>
    <br>
    <hr class="hr-themed">
    <br>
    <div class="row small">
        <div class="span3">
            <strong>Number of Training Contracts</strong>
        </div>
        <div class="span8">
            Number of workforce training contracts executed in the most recent completed fiscal year.        </div>
    </div>
    <br>
    <hr class="hr-themed">
    <br>
    <div class="row small">
        <div class="span3">
            <strong>Percentage of Workforce Training Students who Transitioned to Credit Course Work</strong>
        </div>
        <div class="span8">
            Percentage of non-credit workforce training students that transitioned to one or more credit courses within one year of completing a non-credit course.        </div>
    </div>
    <br>
    <hr class="hr-themed">
    <br>
    <div class="row small">
        <div class="span3">
            <strong>Return on Investment</strong>
        </div>
        <div class="span8">
            ROI: ((Revenue - Expenditures) / Expenditures).        </div>
    </div>
    <br>
    <hr class="hr-themed">
    <br>
    <div class="row small">
        <div class="span3">
            <strong>Service Area Total Companies</strong>
        </div>
        <div class="span8">
            Use the U.S. Economic Census, County Business Patterns to obtain these data.        </div>
    </div>
    <br>
    <hr class="hr-themed">
    <br>
    <div class="row small">
        <div class="span3">
            <strong>Service Area Total Population</strong>
        </div>
        <div class="span8">
            Should reflect the state definition of your institution's service area's most recent U.S. Census estimates.        </div>
    </div>
    <br>
    <hr class="hr-themed">
    <br>
    <div class="row small">
        <div class="span3">
            <strong>Student Satisfaction</strong>
        </div>
        <div class="span8">
            Student overall and course satisfaction rates in non-credit workforce training courses for a given fiscal year. Use the percentage of Very Satisfied &amp; Satisfied on a 5-point scale ranging from Very Satisfied to Very Dissatisfied.        </div>
    </div>
    <br>
    <hr class="hr-themed">
    <br>
    <div class="row small">
        <div class="span3">
            <strong>Total Gross Revenue</strong>
        </div>
        <div class="span8">
            Revenue in support of all non-credit workforce training - include all public, grant, and earned revenue for the most recent completed fiscal year.        </div>
    </div>
    <br>
    <hr class="hr-themed">
    <br>
    <div class="row small">
        <div class="span3">
            <strong>Unduplicated Enrollment</strong>
        </div>
        <div class="span8">
            Unduplicated non-credit workforce training participant headcount for the most recent completed fiscal year.        </div>
    </div>
    <br>
    <hr class="hr-themed">
    <br>
    <div class="row small">
        <div class="span3">
            <strong>Unrestricted Institutional Operating Revenue</strong>
        </div>
        <div class="span8">
            Is defined by the National Association of College and University Business Officers (NACUBO) as "resources received that have no limitations or stipulations placed on them by external agencies or donors."        </div>
    </div>
    <br>
    <hr class="hr-themed">
    <br>
</div>
