<?php /** @var \Mrss\Entity\System[] $systems */ ?>



<div class="slider-container" style="height: 350px">
    <div class="slider-container-overlay">&nbsp;</div>

    <!--<div class="carousel"><img src="http://design.app.benchmark.envisio.com/images/chart.jpg" /></div-->
</div>

<?php foreach ($systems as $system): ?>
<div class="network-wrap">
    <h1><?= $system->getName() ?></h1>

    <div class="col-sm-3 network-progress">
        <div class="row">

            <?php $completion =  round($system->getDataEntryStructure()->getCompletionPercentageForObservation($observation)); ?>

            <?php
                $gauge = array(
                    'chart' => array(
                        'type' => 'solidgauge',
                        'backgroundColor' => '#F7F7F7',
                        'height' => 150
                    ),
                    'title' => '',
                    'id' => 'systemCompletion' . $system->getId(),
                    'series' => array(
                        array(
                            'type' => 'solidgauge',
                            'name' => '',
                            'data' => array($completion),
                            'dataLabels' => array(
                                'format' =>  '<div style="text-align:center"><span style="font-size:25px;color: black">{y}%</span><br/>'
                            )
                        )
                    ),
                    'pane' => array(
                        'startAngle' => -90,
                        'endAngle' => 90,
                        'center' => array(
                            '50%',
                            '90%'
                        ),
                        'size' => '180%',
                        'background' => array(
                            'innerRadius' => '60%',
                            'outerRadius' => '100%',
                            'shape' => 'arc'
                        )
                    ),
                    'tooltip' => array(
                        'enabled' => false
                    ),
                    'yAxis' => array(
                        'min' => 0,
                        'max' => 100,
                        'minorTickInterval' => null,
                        'tickAmount' => 2,
                        'labels' => array(
                            'y' => 16
                        ),
                        'stops' => array(
                            array(0.0, '#cc181e'),
                            array(0.4999999, '#cc181e'),
                            array(0.5, '#fbb41e'),
                            array(0.7499999, '#fbb41e'),
                            array(0.75, '#5fa80b'),
                            array(1, '#5fa80b'),
                        )
                    ),
                    'credits' => array(
                        'enabled' => false
                    ),
                    'plotOptions' => array(
                        'solidgauge' => array(
                            'dataLabels' => array(
                                'y' => 20,
                                'borderWidth' => 0
                            )
                        )
                    ),
                    'exporting' => array(
                        'enabled' => false
                    )
                );

                echo $this->chart($gauge);

            ?>

            <span>Data Entry Progress <?= $yearRange ?></span></div>
    </div>

    <div class="col-sm-6 network-dataentry">
        <ul>
    <li><strong>Service Area <?= $yearRange ?></strong></li>

            <?php foreach ($system->getDataEntryStructure()->getPages() as $benchmarkGroup): ?>
                <?php $bgCompletion = round($benchmarkGroup->getCompletionPercentageForObservation($observation)); ?>
                <?php
                $completionColor = '#cc181e'; // Red
                if ($bgCompletion > 75) {
                    $completionColor = '#5fa80b'; // Green
                } else if ($bgCompletion > 50) {
                    $completionColor = '#fbb41e'; // Yellow
                }

                ?>

            <li>
                <a href="/network-switch/<?= $system->getId() . '?redirect=' . urlencode('/data-entry/' . $benchmarkGroup->getUrl()) ?>">
                <span class="service-area-type"><?= $benchmarkGroup->getLabel() ?></span>
                <div class="service-area-type-progress"><strong style="color:<?= $completionColor ?>"><?= $bgCompletion ?>%</strong>
                    <div class="data-entry-progress-bar">
                        <div class="data-entry-progress" style="background:<?= $completionColor ?>; width: <?= $bgCompletion ?>%;">&nbsp;</div>
                    </div>
                </div>
                </a>
            </li>
            <?php endforeach ?>
        </ul>
        <a class="data-entry-readmore">Show All [+]</a></div>

    <div class="col-sm-3 network-contributor"><strong class="big-number"><?= count($system->getColleges()) ?> <span>Cities</span></strong>

        <div class="newest-contributors"><strong>Newest Members</strong>

            <ul>
                <?php foreach ($system->getRecentMemberships($year) as $systemMembership): ?>
                <li><?= $systemMembership->getCollege()->getName() ?></li>
                <?php endforeach ?>
            </ul>
        </div>
    </div>

    <div class="clear">&nbsp;</div>
</div>
<?php endforeach ?>


<script>
    $( ".network-wrap .network-dataentry ul" ).each(function( index ) {
        $(this).children('li').each(function( index ) {
            if (index > 5) {
                $(this).css('display', 'none');
            }
        });
    });

    $( ".data-entry-readmore" ).each(function( index ) {
        var showAll = false;
        $(this).click(function(){
            if (showAll == false) {
                $(this).text('Show Less [-]');
                $(this).prev('.network-wrap .network-dataentry ul').children('li').css('display', 'block');
                showAll = true;
            } else {
                $(this).text('Show All [+]');
                $(this).prev('.network-wrap .network-dataentry ul').children('li').each(function( index ) {
                    if (index > 5) {
                        $(this).css('display', 'none');
                    }
                    showAll = false;
                });
            }
        });
    });
</script>

