<?php /** @var \Mrss\Entity\System[] $systems */ ?>

<style>
    .homepage > div {
        padding: 30px;
    }
    .homepage div h2, .homepage div h1 {
        text-align: center;
    }
    .homepage div h1 {
        font-weight: normal;
        font-size: 175%;
    }
    .homepage div h2 {
        font-weight: normal;
        font-size: 260%;
    }
    .chatWrapper {
        margin-top: 47px;
    }
</style>


<div class="row homepage">
<div class="col-md-4">
    <h2>Network Membership</h2>

<?php foreach ($systems as $system): ?>
    <?php $yearRange = 'FY ' . $system->getCurrentYear(); ?>
    <?php $observation = $observationModel->findOne($college->getId(), $system->getCurrentYear()); ?>
    <?php if ($_SERVER['REMOTE_ADDR'] == '216.185.233.188') {
        //pr($college->getId()); pr($system->getCurrentYear()); pr($system->getId());

    } ?>
    <div class="network-wrap">
        <h1><?= $system->getName() ?> (<?= count($system->getColleges()) ?> Cities)</h1>


                <?php $completion =  round($system->getDataEntryStructure()->getCompletionPercentageForObservation($observation)); ?>

                <?php
                $chart = new \Mrss\Service\Report\Chart\Gauge($system->getId(), $completion);

                echo $this->chart($chart->getConfig());

                ?>

                <!--<span>Data Entry Progress <?= $yearRange ?></span>-->


        <div class="clear">&nbsp;</div>
    </div>
<?php endforeach ?>

</div>

    <div class="col-md-4">
        <a href="/community"><h2>Community</h2></a>

        <div class="chatWrapper">
            <a class="muut" href="https://muut.com/i/govbenchmark">govbenchmark</a> <script src="//cdn.muut.com/1/moot.min.js"></script>
        </div>
    </div>

    <div class="col-md-4">
        <h2>govBenchmark News</h2>

        <?php if ($news) echo $news->getContent() ?>
    </div>


</div>



<script>
    $( ".network-wrap .network-dataentry ul" ).each(function( index ) {
        $(this).children('li').each(function( index ) {
            if (index > 5) {
                $(this).css('display', 'none');
            }
        });
    });

    $( ".data-entry-readmore" ).each(function( index ) {
        var showAll = false;
        $(this).click(function(){
            if (showAll == false) {
                $(this).text('Show Less [-]');
                $(this).prev('.network-wrap .network-dataentry ul').children('li').css('display', 'block');
                showAll = true;
            } else {
                $(this).text('Show All [+]');
                $(this).prev('.network-wrap .network-dataentry ul').children('li').each(function( index ) {
                    if (index > 5) {
                        $(this).css('display', 'none');
                    }
                    showAll = false;
                });
            }
        });
    });
</script>

