<?php namespace Mrss\Entity;

use Doctrine\ORM\Mapping as ORM;
use Mrss\Entity\Exception;

/**
 * Observation entity class generated by ObservationGenerator
 *
 *
 *
 * @ORM\Entity
 * @ORM\Table(name="observations")
 */
class Observation extends ObservationBase
{

    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * @ORM\Column(type="integer")
     */
    protected $year;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $migrated;

    /**
     * @ORM\ManyToOne(targetEntity="College", inversedBy="observations")
     * @ORM\JoinColumn(name="college_id", referencedColumnName="id", onDelete="CASCADE")
     */
    protected $college;

    /**
     * @ORM\OneToMany(targetEntity="SubObservation", mappedBy="observation")
     * @ORM\OrderBy({"id" = "ASC"})
     * @var SubObservation[]
     */
    protected $subObservations;

    /**
     * @ORM\OneToMany(targetEntity="Subscription", mappedBy="observation")
     * @var Subscription[]
     */
    protected $subscriptions;
}
