<?php $this->headTitle()->prepend('Contact'); ?>
<script type="text/javascript">
    $(function() {
        setTimeout(function() {
            // Add an enlarge link
            //alert('test')
            $('#recaptcha_table tbody').after(
                '<tr><td>' +
                    '<a href="#" id="enlarge">Enlarge image</a>' +
                    '<a href="#" id="shrink">Restore image</a>' +
                    '</td></tr>'
            )
            $('#shrink').hide()
            $('#enlarge').parent().css('text-align', 'center')


            $('#enlarge').click(function() {
                $('#control-group-captcha').css('margin-top', '120px')
                $('#recaptcha_image img')
                    .css('position', 'absolute')
                    .css('bottom', '60px')
                    .css('left', '200px')
                    .css('transform', 'scale(2.5)')
                    .zIndex(99)
                $('#shrink').show()
                $('#enlarge').hide()

                return false
            })


            $('#shrink').click(function() {
                $('#control-group-captcha').css('margin-top', '15px')
                $('#recaptcha_image img')
                    .css('position', 'relative')
                    .css('bottom', '0px')
                    .css('left', '0px')
                    .css('transform', 'scale(1)')
                    .zIndex(99)
                $('#shrink').hide()
                $('#enlarge').show()

                return false
            })

        }, 500)
    })
</script>

<section class="contact">
    <div class="page-header">
        <h2>Contact Us</h2>
    </div>


    <?php if ($this->currentStudy()->getId() == 3): ?>
    <p class="page-intro">
        Contact us about benchmarks, data collection and reporting, subscription, peer comparison, or to simply comment on the Workforce&nbsp;Project
        ?>.
    </p>
    <p>
        You can also reach us by phone: Dr. Lou Guthrie, Director, 913-469-8500 x4019 or Michelle Taylor, Senior Research & Data Analyst, 913-469-8500 x3648.
    </p>
    <?php endif ?>

    <?php if ($this->currentStudy()->getId() == 2): ?>
        <p class="page-intro">
            Contact us about benchmarks, data collection and reporting, subscription, peer comparison, or to simply comment on Maximizing Resources for Student&nbsp;Success.
        </p>
        <p>
        You can also reach us by phone: Dr. Lou Guthrie, Director, 913-469-8500 x4019 or Michelle Taylor, Senior Research & Data Analyst, 913-469-8500 x3648.
        </p>
    <?php endif ?>

    <p>
        Privacy Note: Your contact message will contain a return e-mail address. If you include other identifying information, we may use that information when we respond. Email may not be secure, so send only information that is necessary to respond to your request.
    </p>

    <?php if ($this->error): ?>
        <p class="error">
            There were one or more issues with your submission. Please correct them as
            indicated below.
        </p>
    <?php endif ?>

    <?php
    $form = $this->form;
    $form->prepare();
    $form->setAttribute('action', $this->url('contact/process'));
    $form->setAttribute('method', 'post');
    $form->setAttribute('class', 'form-horizontal');

    // Use the Bootstrap btn class
    $form->get('Send')->setAttribute('class', 'btn btn-primary');

    // Make the body a little taller
    $form->get('body')->setAttribute('rows', 8)->setLabel('Message');
    $form->get('from')->setLabel('Your Email');
    $form->get('subject')->setLabel('Subject');
    ?>

    <?= $this->ztbForm($form) ?>
</section>
