<?php $this->headTitle()->prepend('Contact'); ?>
<section class="contact">
    <h2>Contact Us</h2>

    <p>
        Contact us about benchmarks, data collection and reporting, subscription, peer comparison, or to simply comment on <?= $this->currentStudy()->getDescription()
?>.
    </p>
    <p>

    <?php if ($this->currentStudy()->getId() == 3): ?>
        You can also reach us by phone: Dr. Lou Guthrie, Director, 913-469-8500 x4019 or Michelle Taylor, Senior Research & Data Analyst, 913-469-8500 x3648.
    <?php endif ?>

    <?php if ($this->currentStudy()->getId() == 2): ?>
        You can also reach us by phone: Dr. Lou Guthrie, Director, 913-469-8500 x4019 or Victoria Douglas, Research & Data Analyst, 913-469-8500 x7635.
    <?php endif ?>

    </p>

    <p>
        Privacy Note: Your contact message will contain a return e-mail address. If you include other identifying information, we may use that information when we respond. Also, e-mail may not be secure, so send only information that is necessary to respond to your request.
    </p>

    <?php if ($this->error): ?>
        <p class="error">
            There were one or more issues with your submission. Please correct them as
            indicated below.
        </p>
    <?php endif ?>

    <?php
    $form = $this->form;
    $form->prepare();
    $form->setAttribute('action', $this->url('contact/process'));
    $form->setAttribute('method', 'post');
    $form->setAttribute('class', 'form-horizontal');

    // Use the Bootstrap btn class
    $form->get('Send')->setAttribute('class', 'btn btn-primary');

    // Make the body a little taller
    $form->get('body')->setAttribute('rows', 5)->setLabel('Message');
    $form->get('from')->setLabel('Your Email');
    $form->get('subject')->setLabel('Subject');
    ?>

    <?= $this->ztbForm($form) ?>
</section>
