<?php $this->headTitle()->prepend('Contact'); ?>
<script type="text/javascript">
    $(function() {
        backgroundVerification()

        /* Deprecated along with old reCaptcha
        setTimeout(function() {
            // Add an enlarge link
            //alert('test')
            $('#recaptcha_table tbody').after(
                '<tr><td>' +
                    '<a href="#" id="enlarge">Enlarge image</a>' +
                    '<a href="#" id="shrink">Restore image</a>' +
                    '</td></tr>'
            )
            $('#shrink').hide()
            $('#enlarge').parent().css('text-align', 'center')


            $('#enlarge').click(function() {
                $('#control-group-captcha').css('margin-top', '120px')
                $('#recaptcha_image img')
                    .css('position', 'absolute')
                    .css('bottom', '60px')
                    .css('left', '200px')
                    .css('transform', 'scale(2.5)')
                    .zIndex(99)
                $('#shrink').show()
                $('#enlarge').hide()

                return false
            })


            $('#shrink').click(function() {
                $('#control-group-captcha').css('margin-top', '15px')
                $('#recaptcha_image img')
                    .css('position', 'relative')
                    .css('bottom', '0px')
                    .css('left', '0px')
                    .css('transform', 'scale(1)')
                    .zIndex(99)
                $('#shrink').hide()
                $('#enlarge').show()

                return false
            })

        }, 500)*/
    })

    function backgroundVerification()
    {
        var captchaControls = $('#control-group-captcha');

        // Are we using the default captcha (reverse word)?
        if (captchaControls.html().search('backwards')) {
            var word = captchaControls.find('strong').html();
            var reversed = reverse(word);

            // Fill in the input
            captchaControls.find('input[type=text]').val(reversed)

            // Now hide the whole controls
            captchaControls.hide()
        }
    }

    function reverse(s) {
        return s.split('').reverse().join('');
    }
</script>

<style>
    /*#control-group-captcha {
        display: none;
    }*/
</style>

<section class="contact">
    <div class="page-header">
        <h2>Contact Us</h2>
    </div>

    <?php if ($text = $this->currentStudy(false)->getConfig()->contact_instructions): ?>
        <p class="page-intro">
            <?= $text ?>
        </p>
    <?php endif ?>

    <?php if ($this->error): ?>
        <p class="error">
            There were one or more issues with your submission. Please correct them as
            indicated below.
        </p>
    <?php endif ?>

    <?php
    $form = $this->form;
    $form->prepare();
    $form->setAttribute('action', $this->url('contact/process'));
    $form->setAttribute('method', 'post');
    $form->setAttribute('class', 'form-horizontal');

    // Use the Bootstrap btn class
    $form->get('Send')->setAttribute('class', 'btn btn-primary');

    // Make the body a little taller
    $form->get('body')->setAttribute('rows', 8)->setLabel('Message');
    $form->get('from')->setLabel('Your Email');
    $form->get('subject')->setLabel('Subject');


    // Add some titles for accessibility
    $form->get('from')->setAttribute('title', 'Your email address.');
    $form->get('subject')->setAttribute('title', 'Subject');
    $form->get('body')->setAttribute('title', 'Message body');
    $form->get('captcha')->setAttribute('title', 'Captcha');

    $formOutput = $this->ztbForm($form);

    // Replace <b> with <strong> for WCAG
    $formOutput = str_replace(
        array('<b>', '</b>'),
        array('<strong>', '</strong>'),
        $formOutput
    );
    ?>

    <?= $formOutput ?>

    <p>
        Privacy Note: Your contact message will contain a return e-mail address. If you include other identifying information, we may use that information when we respond. Email may not be secure, so send only information that is necessary to respond to your request.
    </p>

</section>
