<!DOCTYPE html>
<html>
<head>
    <title>Maximizing Resources for Student Success</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Styles -->
    <link href="/css/bootstrap.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="/css/theme.css">
    <link rel="stylesheet" type="text/css" href="/css/content.css">
    <link rel="stylesheet" href="/css/index.css" type="text/css" media="screen" />

    <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,900,300italic,400italic,700italic,900italic' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="/css/lib/animate.css" media="screen, projection">

    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Scripts -->
    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <script src="http://code.jquery.com/ui/jquery-ui-git.js"></script>
    <script src="/js/bootstrap.min.js"></script>
    <script src="/js/theme.js"></script>

    <script type="text/javascript" src="/js/index-slider.js"></script>

    <?php echo $this->headScript() ?>
</head>
<body class="pull_top">
<div id="wrapper">
<div class="navbar <?php /*transparent*/ ?> navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <a class="brand" href="/">
                <img src="/img/mrss-logo.png" alt="Maximizing Resources for
                Student Success" />
            </a>
            <div class="nav-collapse collapse">
                <?php //$menuOptions = array('ulClass' => 'nav pull-right') ?>
                <?php $partial = array('mrss/menu/navigation.phtml', 'default') ?>
                <?php //$this->navigation('navigation')->menu()
                    //->setPartial($partial) ?>
                <?= $this->navigation()->menu('navigation')->setPartial
                    ($partial)
                    ->render(); ?>
            </div>
        </div>
    </div>
</div>

<? if (false): ?>

    <?= $this->flashMessenger()->render('error'); ?>
    <?= $this->flashMessenger()->render('info'); ?>
    <?= $this->flashMessenger()->render('success'); ?>
    <?= $this->flashMessenger()->render('default'); ?>

<? elseif (true): ?>
    <?php foreach ($this->flashMessages(true) as $namespace => $messages) : ?>
        <?php if (count($messages)) : ?>
            <?php foreach ($messages as $message) : ?>
                <div class="alert alert-<?=$namespace?>">
                    <?php echo $message; ?>
                </div>
            <?php endforeach; ?>
        <?php endif; ?>
    <?php endforeach; ?>
<? else: ?>
    <?= $this->ztbFlashMessenger()->render(); ?>

<? endif ?>


<?php if (empty($this->noWrapper)): ?>
    <div id="content">
        <div class="container-fluid container">
            <div class="row-fluid">

                <?php if ($this->isAllowed('adminMenu', 'view')): ?>
                <div class="span2 adminNavigation">
                    <h3>Admin</h3>

                    <?php $partial = array('mrss/menu/navigation.phtml',
                        'default') ?>
                    <?php //$this->navigation('navigation')->menu()
                        //->setPartial($partial) ?>
                    <?= $this->navigation('admin_navigation')
                        ->menu()
                        //->setPartial($partial)
                        //->setContainer('admin')
                        ->render(); ?>
                </div>
                <?php endif ?>

                <div class="span10">
                    <?php echo $this->content; ?>
                </div>
            </div>

        </div>
    </div>

<?php else: ?>
    <?php echo $this->content; ?>

<?php endif ?>

</div>
<!-- end wrapper -->

<!-- starts footer -->
<footer id="footer">
    <div class="container">
        <?php /*<div class="row sections">
            <div class="span4 recent_posts">
                <h3 class="footer_header">
                    Recent Posts
                </h3>
                <div class="post">
                    <a href="blogpost.html">
                        <img src="img/recent_post1.png" class="img-circle" />
                    </a>
                    <div class="date">
                        Wed, 12 Dec
                    </div>
                    <a href="blogpost.html" class="title">
                        Randomised words which don't look embarrasing hidden.
                    </a>
                </div>
                <div class="post">
                    <a href="blogpost.html">
                        <img src="img/recent_post2.png" class="img-circle" />
                    </a>
                    <div class="date">
                        Mon, 12 Dec
                    </div>
                    <a href="blogpost.html" class="title">
                        Randomised words which don't look embarrasing hidden.
                    </a>
                </div>
            </div>
            <div class="span4 testimonials">
                <h3 class="footer_header">
                    Testimonials
                </h3>
                <div class="wrapper">
                    <div class="quote">
                        <span>“</span>
                        There are many variations of passages of randomised words which don't look even slightly believable. You need to be sure there isn't anything embarrassing of text.
                        <span></span>
                    </div>
                    <div class="author">
                        <img src="img/user-display.png" />
                        <div class="name">Alejandra Galvan Castillo</div>
                        <div class="info">
                            Details Canvas
                        </div>
                    </div>
                </div>
            </div>
            <div class="span4 contact">
                <h3 class="footer_header">
                    Contact
                </h3>
                <form action="#" method="post">
                    <input type="text" placeholder="Your name" />
                    <input type="text" placeholder="Your email" />
                    <textarea rows="3" placeholder="Message"></textarea>
                    <input type="submit" value="Send" />
                </form>
            </div>
        </div> */ ?>
        <div class="row credits">
            <div class="span12">
                <?php /*<div class="row social">
                    <div class="span12">
                        <a href="#" class="facebook">
                            <span class="socialicons ico1"></span>
                            <span class="socialicons_h ico1h"></span>
                        </a>
                        <a href="#" class="twitter">
                            <span class="socialicons ico2"></span>
                            <span class="socialicons_h ico2h"></span>
                        </a>
                        <a href="#" class="gplus">
                            <span class="socialicons ico3"></span>
                            <span class="socialicons_h ico3h"></span>
                        </a>
                        <a href="#" class="flickr">
                            <span class="socialicons ico4"></span>
                            <span class="socialicons_h ico4h"></span>
                        </a>
                        <a href="#" class="pinterest">
                            <span class="socialicons ico5"></span>
                            <span class="socialicons_h ico5h"></span>
                        </a>
                        <a href="#" class="dribble">
                            <span class="socialicons ico6"></span>
                            <span class="socialicons_h ico6h"></span>
                        </a>
                        <a href="#" class="behance">
                            <span class="socialicons ico7"></span>
                            <span class="socialicons_h ico7h"></span>
                        </a>
                    </div>
                </div>
                */ ?>

                <div class="row copyright">
                    <div class="span12">
                        © 2013 National Higher Education Benchmark Institute. All
                        rights reserved. Theme by Detail Canvas.
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>


</body>
</html>
