
<!DOCTYPE html>
<html lang="en" moznomarginboxes="1" mozdisallowselectionprint="1">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <?= $this->headTitle() ?>

    <link rel="stylesheet" type="text/css" href="/css/app.css?v=11">
    <link rel="stylesheet" type="text/css" href="/css/content.css">
    <link rel="stylesheet" type="text/css" href="/css/tooltipster.css">

    <!-- Bootstrap & Style Sheets -->
    <link href="/css/bootstrap3.css?v=3" rel="stylesheet">
    <link href="/css/bootstrap3-theme.css?v=3" rel="stylesheet">
    <link href="/css/content.css" rel="stylesheet" type="text/css" />

    <?php if ($cssFile = $this->currentStudy(false)->getConfig()->css): ?>
        <link rel="stylesheet" type="text/css" href="/css/<?= $cssFile ?>?v=23">
    <?php endif ?>

    <?php if ($cssPrintFile = $this->currentStudy(false)->getConfig()->css_print): ?>
        <link rel="stylesheet" type="text/css" href="/css/<?= $cssPrintFile ?>?v=1" media="print">
    <?php endif ?>

    <!-- Google Fonts -->
    <? //<link href='http://fonts.googleapis.com/css?family=Fira+Sans:500,700,300italic|Cabin:400,400italic,500,700' rel='stylesheet' type='text/css'> ?>
    <link href='https://code.cdn.mozilla.net/fonts/fira.css' rel='stylesheet' type='text/css'>

    <link rel="stylesheet" href="/fancybox/source/jquery.fancybox.css?v=2.1.5" type="text/css" media="screen" />


    <!-- jQuery -->
    <script src="/js/jquery.js"></script>


    <?php if ($favicon = $this->currentStudy(false)->getConfig()->favicon): ?>
        <link rel="icon" href="<?= $favicon ?>" type="image/x-icon">
        <link rel="shortcut icon" href="<?= $favicon ?>" type="image/x-icon">
    <?php endif ?>

    <?php echo $this->headLink() ?>



</head>
<body>

<?php $headerTitle = $this->currentStudy(false)->getConfig()->header_title; ?>
<?php if ($headerTitle) {
    $logoCols = 3;
    $loginCols = 8;
} else {
    $logoCols = 5;
    $loginCols = 6;
}
?>

<!-- BEGIN HEADER -->
<header>
    <div class="container">
        <div class="row">
            <div class="col-xs-<?= $logoCols ?> logo">
                <?php $logoUrl = $this->currentStudy(false)->getConfig()->head_logo_url ?>
                <a href="<?= $logoUrl ?>"><img class="img-responsive" alt="<?= $this->currentStudy()->getDescription() ?>" src="<?= $this->currentStudy()->getLogo() ?>" title="<?= $this->currentStudy()->getDescription() ?>" /></a>
            </div>

            <div class="col-xs-1 header-title">
			    <?php if ($headerTitle = $this->currentStudy(false)->getConfig()->header_title): ?>
	                <h1><?= $headerTitle ?></h1>
			    <?php endif ?>
            </div>


            <div class="col-xs-<?= $loginCols ?> headerLogin">
                <?php $webinar = false //time() > strtotime('2015-04-01') ?>

                <?php if(!$this->zfcUserIdentity()): ?>
                    <div id="headerButtons">
                        <a href="#" class="btn login-btn" role="button" id="loginButton">SIGN IN</a>

                        <?php if (!$this->zfcUserIdentity()): ?>
                            <?php if ($headerButton = $this->currentStudy(false)->getConfig()->logged_out_header_button): ?>
                                <?= $headerButton ?>
                            <?php endif ?>

                        <?php endif ?>

                        <?php if ($webinar): ?>
                        <a href="/webinar" class="btn schedule-btn" role="button" id="schedule-demo">FREE WEBINAR</a>
                        <?php endif ?>

                        </div>

                    <div id="headerLoginForm">
                        <? $form = $this->plugin('zfcUserLoginWidget')->getLoginForm();
                        $form->get('identity')->setAttribute('placeHolder', 'Email');
                        $form->get('identity')->setAttribute('title', 'Email');
                        $form->get('credential')->setAttribute('placeHolder', 'Password');
                        $form->get('credential')->setAttribute('title', 'Password');
                        ?>
                        <?= $this->zfcUserLoginWidget() ?>
                    </div>
                <?php else: ?>
                <div id="headerButtons">
                    <?php if ($webinar): ?>
                        <a href="/webinar" class="btn schedule-btn" role="button" id="schedule-demo">FREE WEBINAR</a>
                    <?php endif ?>
                        <a href="https://benchmarkinginstitute.org/benchmarking-conference/overview" class="btn schedule-btn" role="button" id="schedule-demo">2017 BENCHMARKING CONFERENCE</a>
                    </div>
                <?php endif ?>


                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>

            </div>
        </div>

        <?php if(!$this->zfcUserIdentity()): ?>
        <div class="row" id="actionItems">
            <?php if ($webinar): ?>
                <div class="col-xs-4">
                    <a href="/webinar" class="btn schedule-btn" role="button">FREE WEBINAR</a>
                </div>
                <div class="col-xs-5">
                    <a href="/schedule-demo" class="btn schedule-btn" role="button">SCHEDULE DEMO</a>
                </div>

                <div class="col-xs-3">
                    <a href="/user/login" class="btn login-btn" role="button">SIGN IN</a>
                </div>
            <?php else: ?>
                <div class="col-xs-6">
                    <a href="/schedule-demo" class="btn schedule-btn" role="button">SCHEDULE DEMO</a>
                </div>

                <div class="col-xs-6">
                    <a href="/user/login" class="btn login-btn" role="button">SIGN IN</a>
                </div>

            <?php endif ?>

        </div>
        <?php endif ?>

        <div class="col-xs-12">

            <nav class="navbar navbar-default" role="navigation">
                <div class="container-fluid">
                    <!-- Brand and toggle get grouped for better mobile display -->


                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="navbar-collapse collapse" id="bs-example-navbar-collapse-1">
                        <?php //$menuOptions = array('ulClass' => 'nav pull-right') ?>
                        <?php $partial = array('mrss/menu/nccbp-navigation.phtml', 'default') ?>
                        <?php $navigation = $this->currentStudy(false)->getConfig()->navigation ?>
                        <?= $this->navigation()->menu($navigation)->setPartial
                            ($partial)
                            ->render(); ?>
                    </div>

                </div><!-- /.container-fluid -->
            </nav>

        </div>
    </div>
</header>
<!-- END HEADER -->

<!-- BEGIN BODY -->
<?php foreach ($this->flashMessages(true) as $namespace => $messages) : ?>
    <?php if (count($messages)) : ?>
        <?php if ($namespace == 'error') $namespace = 'danger' ?>
        <?php foreach ($messages as $message) : ?>
            <div class="alert alert-<?=$namespace?>">
                <?php echo $message; ?>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>
<?php endforeach; ?>

<?php if ($this->zfcUserImpersonatorDisplayName()): ?>
    <div class="impersonation">
        <span><a title="Unimpersonate" href="<?= $this->url('users/unimpersonate') ?>">
                <?= $this->zfcUserImpersonatorDisplayName() ?></a> is impersonating
        </span>

        <?= $this->zfcUserDisplayName() ?>
        (<?= $this->zfcUserIdentity()->getCollege()->getName() ?>)
    </div>
<?php endif ?>

<?= $this->systemAdmin($this->isAllowed('systemSwitch', 'view')) ?>

<?php if (empty($this->noWrapper)): ?>
    <div id="content">

        <div class="container-fluid container">
            <div class="row-fluid row">



                <div class="span12 col-xs-12">

                    <?php echo $this->content; ?>
                </div>
            </div>

        </div>
    </div>

<?php else: ?>
    <?php echo $this->content; ?>

<?php endif ?>


<!-- END BODY -->
<!-- BEGIN FOOTER -->
<div class="footer">
    <div class="container">
        <div class="row">
            <div class="col-xs-2 footer-logo">
                <?= $this->currentStudy(false)->getConfig()->footerLogo ?>
            </div>
            <div class="col-xs-10">
                <div class="nav-collapse footer-nav">
                    <?php //$menuOptions = array('ulClass' => 'nav pull-right') ?>
                    <?php $partial = array('mrss/menu/navigation.phtml', 'aaup') ?>
                    <?php $navigation = $this->currentStudy(false)->getConfig()->navigation ?>
                    <?php //$navigation = 'Zend\Navigation\Default'; ?>
                    <?= $this->navigation()->menu($navigation)
                        ->setPartial($partial)
                        ->render(); ?>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-6 socialButtons">
                <?= $this->currentStudy(false)->getConfig()->footerSocial ?>
            </div>
            <div class="col-xs-6">
                <p>© <?= $this->currentStudy(false)->getConfig()->copyright ?></p>
            </div>
        </div>
    </div>
</div>
<!-- END FOOTER -->


<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="/js/bootstrap3.min.js?v=3"></script>

<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<?php /* <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script> */ ?>
<![endif]-->

<script type="text/javascript" src="/js/jquery-ui.js"></script>
<script type="text/javascript" src="/js/jquery.tooltipster.min.js"></script>
<script type="text/javascript" src="/js/jquery.fixwidows.js"></script>

<!-- App-specific -->
<script type="text/javascript" src="/js/app.js?v=2"></script>
<script type="text/javascript" src="/js/theme.js"></script>
<script type="text/javascript" src="/js/nccbp.js?v=2"></script>

<!-- Add fancyBox -->

<script type="text/javascript" src="/fancybox/source/jquery.fancybox.pack.js?v=2.1.5"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $(".fancybox").fancybox();
    });
</script>

<?php echo $this->headScript() ?>

<?php if ($googleAnalyticsKey = $this->currentStudy()->getGoogleAnalyticsKey()): ?>
    <script type="text/javascript">

        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', '<?= $googleAnalyticsKey ?>']);
        _gaq.push(['_trackPageview']);

        (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'stats.g.doubleclick.net/dc.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();

    </script>

    <script type="text/javascript">
        if (typeof jQuery != 'undefined') {
            jQuery(document).ready(function($) {
                var filetypes = /\.(zip|exe|dmg|pdf|doc.*|xls.*|ppt.*|mp3|txt|rar|wma|mov|avi|wmv|flv|wav)$/i;
                var baseHref = '';
                if (jQuery('base').attr('href') != undefined) baseHref = jQuery('base').attr('href');

                jQuery('a').on('click', function(event) {
                    var el = jQuery(this);
                    var track = true;
                    var href = (typeof(el.attr('href')) != 'undefined' ) ? el.attr('href') :"";
                    var isThisDomain = href.match(document.domain.split('.').reverse()[1] + '.' + document.domain.split('.').reverse()[0]);
                    if (!href.match(/^javascript:/i)) {
                        var elEv = []; elEv.value=0, elEv.non_i=false;
                        if (href.match(/^mailto\:/i)) {
                            elEv.category = "email";
                            elEv.action = "click";
                            elEv.label = href.replace(/^mailto\:/i, '');
                            elEv.loc = href;
                        }
                        else if (href.match(filetypes)) {
                            var extension = (/[.]/.exec(href)) ? /[^.]+$/.exec(href) : undefined;
                            elEv.category = "download";
                            elEv.action = "click-" + extension[0];
                            elEv.label = href.replace(/ /g,"-");
                            elEv.loc = baseHref + href;
                        }
                        else if (href.match(/^https?\:/i) && !isThisDomain) {
                            elEv.category = "external";
                            elEv.action = "click";
                            elEv.label = href.replace(/^https?\:\/\//i, '');
                            elEv.non_i = true;
                            elEv.loc = href;
                        }
                        else if (href.match(/^tel\:/i)) {
                            elEv.category = "telephone";
                            elEv.action = "click";
                            elEv.label = href.replace(/^tel\:/i, '');
                            elEv.loc = href;
                        }
                        else track = false;

                        if (track) {
                            _gaq.push(['_trackEvent', elEv.category.toLowerCase(), elEv.action.toLowerCase(), elEv.label.toLowerCase(), elEv.value, elEv.non_i]);
                            if ( el.attr('target') == undefined || el.attr('target').toLowerCase() != '_blank') {
                                setTimeout(function() { location.href = elEv.loc; }, 400);
                                return false;
                            }
                        }
                    }
                });
            });
        }
    </script>
<?php endif ?>

</body>
</html>

