
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <?= $this->headTitle() ?>
    <link rel="stylesheet" type="text/css" href="/css/content.css">
    <link rel="stylesheet" type="text/css" href="/css/tooltipster.css">

    <!-- Bootstrap & Style Sheets -->
    <link href="/css/bootstrap3.css" rel="stylesheet">
    <link href="/css/bootstrap3-theme.css" rel="stylesheet">
    <link href="/css/content.css" rel="stylesheet" type="text/css" />
    <link href="/css/nccbp.css?v=<?= 4 ?>" rel="stylesheet" type="text/css" />

    <!-- Google Fonts -->
    <? //<link href='http://fonts.googleapis.com/css?family=Fira+Sans:500,700,300italic|Cabin:400,400italic,500,700' rel='stylesheet' type='text/css'> ?>
    <link href='http://code.cdn.mozilla.net/fonts/fira.css' rel='stylesheet' type='text/css'>

    <link rel="icon" href="/images/nccbp-favicon.ico" type="image/x-icon">
    <link rel="shortcut icon" href="/nccbp-favicon.ico" type="image/x-icon">

    <?php echo $this->headLink() ?>


    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="/js/bootstrap3.min.js"></script>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <script type="text/javascript" src="/js/jquery-ui.js"></script>
    <script type="text/javascript" src="/js/jquery.tooltipster.min.js"></script>

    <!-- App-specific -->
    <script type="text/javascript" src="/js/theme.js"></script>
    <script type="text/javascript" src="/js/nccbp.js?v=1"></script>

    <!-- Add fancyBox -->
    <link rel="stylesheet" href="/fancybox/source/jquery.fancybox.css?v=2.1.5" type="text/css" media="screen" />
    <script type="text/javascript" src="/fancybox/source/jquery.fancybox.pack.js?v=2.1.5"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $(".fancybox").fancybox();
        });
    </script>

    <?php echo $this->headScript() ?>
</head>
<body>

<!-- BEGIN HEADER -->
<header>
    <div class="container">
        <div class="row">
            <div class="col-xs-4 logo">
                <a href="/"><img class="img-responsive" src="/images/nccbp-logo.jpg" /></a>
            </div>


            <div class="col-xs-8 headerLogin">

                <?php if(!$this->zfcUserIdentity()): ?>
                    <div id="headerButtons">
                        <a href="#" class="btn login-btn" role="button" id="loginButton">SIGN IN</a>

                        <?php if(!$this->zfcUserIdentity()): ?>
                            <a href="/schedule-demo" class="btn schedule-btn" role="button" id="schedule-demo">SCHEDULE DEMO</a>
                        <?php endif ?>

                        </div>

                    <div id="headerLoginForm">
                        <? $form = $this->plugin('zfcUserLoginWidget')->getLoginForm();
                        $form->get('identity')->setAttribute('placeHolder', 'Email');
                        $form->get('credential')->setAttribute('placeHolder', 'Password');
                        ?>
                        <?= $this->zfcUserLoginWidget() ?>
                    </div>
                <?php endif ?>


                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>

            </div>
        </div>

        <?php if(!$this->zfcUserIdentity()): ?>
        <div class="row" id="actionItems">
            <div class="col-xs-6">
                <a href="/schedule-demo" class="btn schedule-btn" role="button">SCHEDULE DEMO</a>
            </div>

            <div class="col-xs-6">
                <a href="/user/login" class="btn login-btn" role="button">SIGN IN</a>
            </div>
        </div>
        <?php endif ?>

        <div class="col-xs-12">

            <nav class="navbar navbar-default" role="navigation">
                <div class="container-fluid">
                    <!-- Brand and toggle get grouped for better mobile display -->


                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="navbar-collapse collapse" id="bs-example-navbar-collapse-1">
                        <?php //$menuOptions = array('ulClass' => 'nav pull-right') ?>
                        <?php $partial = array('mrss/menu/nccbp-navigation.phtml', 'default') ?>
                        <?php $navigation = 'navigation' ?>
                        <?php if ($this->currentStudy()->getId() == 1) {
                            $navigation = 'nccbp_navigation';
                        } ?>
                        <?= $this->navigation()->menu($navigation)->setPartial
                            ($partial)
                            ->render(); ?>
                    </div>

                </div><!-- /.container-fluid -->
            </nav>

        </div>
    </div>
</header>
<!-- END HEADER -->

<!-- BEGIN BODY -->
<?php foreach ($this->flashMessages(true) as $namespace => $messages) : ?>
    <?php if (count($messages)) : ?>
        <?php if ($namespace == 'error') $namespace = 'danger' ?>
        <?php foreach ($messages as $message) : ?>
            <div class="alert alert-<?=$namespace?>">
                <?php echo $message; ?>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>
<?php endforeach; ?>

<?php if (empty($this->noWrapper)): ?>
    <?php if ($this->zfcUserImpersonatorDisplayName()): ?>
        <div class="impersonation">
            <span><a title="Unimpersonate" href="<?= $this->url('zfcuserimpersonate/unimpersonate') ?>">
                    <?= $this->zfcUserImpersonatorDisplayName() ?></a> is impersonating
            </span>

            <?= $this->zfcUserDisplayName() ?>
            (<?= $this->zfcUserIdentity()->getCollege()->getName() ?>)
        </div>
    <?php endif ?>
<?php endif ?>

<?php if (empty($this->noWrapper)): ?>
    <div id="content">

        <div class="container-fluid container">
            <div class="row-fluid row">



                <div class="span12 col-xs-12">

                    <?php echo $this->content; ?>
                </div>
            </div>

        </div>
    </div>

<?php else: ?>
    <?php echo $this->content; ?>

<?php endif ?>


<!-- END BODY -->
<!-- BEGIN FOOTER -->
<div class="footer">
    <div class="container">
        <div class="row">
            <div class="col-xs-2">
                <a href="/benchmarking-institute"><img src="/images/benchmark_logo.png" /></a>
            </div>
            <div class="col-xs-10">
                <div class="nav-collapse footer-nav">
                    <?php //$menuOptions = array('ulClass' => 'nav pull-right') ?>
                    <?php $partial = array('mrss/menu/navigation.phtml', 'nccbp') ?>
                    <?= $this->navigation()->menu('nccbp_navigation')
                        ->setPartial($partial)
                        ->render(); ?>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-6 socialButtons">
                <a href="http://twitter.com/EdBenchmark" title="Follow us on Twitter" target="_blank">
                    <img src="/images/48x48_twitter.png" alt="Follow us on Twitter" />
                </a>
                <a href="https://www.linkedin.com/groups/National-Higher-Education-Benchmarking-Institute-2022361" title="Join our LinkedIn Group" target="_blank">
                    <img src="/images/48x48_linkedin.png" alt="Join our LinkedIn Group" />
                </a>
            </div>
            <div class="col-xs-6">
                <p>© 2004 - <?= date('Y') ?> Johnson County Community College</p>
            </div>
        </div>
    </div>
</div>
<!-- END FOOTER -->

<?php if ($googleAnalyticsKey = $this->currentStudy()->getGoogleAnalyticsKey()): ?>
    <script type="text/javascript">

        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', '<?= $googleAnalyticsKey ?>']);
        _gaq.push(['_trackPageview']);

        (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'stats.g.doubleclick.net/dc.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();

    </script>
<?php endif ?>

</body>
</html>
