
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?= $this->currentStudy()->getDescription() ?></title>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="/js/bootstrap3.min.js"></script>


    <link rel="stylesheet" type="text/css" href="/css/content.css">
    <link rel="stylesheet" type="text/css" href="/css/tooltipster.css">

    <!-- Bootstrap & Style Sheets -->
    <link href="/css/bootstrap3.css" rel="stylesheet">
    <link href="/css/bootstrap3-theme.css" rel="stylesheet">
    <link href="/css/nccbp.css" rel="stylesheet" type="text/css" />

    <!-- Google Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Fira+Sans:500,700,300italic|Cabin:400,400italic,500,700' rel='stylesheet' type='text/css'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <link rel="icon" href="/images/nccbp-favicon.ico" type="image/x-icon">
    <link rel="shortcut icon" href="/nccbp-favicon.ico" type="image/x-icon">

    <script type="text/javascript" src="/js/jquery-ui.js"></script>
    <script type="text/javascript" src="/js/jquery.tooltipster.min.js"></script>
    <script type="text/javascript" src="/js/theme.js"></script>
    <script type="text/javascript" src="/js/nccbp.js"></script>

    <?php echo $this->headLink() ?>
    <?php echo $this->headScript() ?>
</head>
<body>

<!-- BEGIN HEADER -->
<header>
    <div class="container">
        <div class="row">
            <div class="col-xs-4">
                <?php if(!$this->zfcUserIdentity()): ?>
                <a href="/schedule-demo" class="btn schedule-btn" role="button">SCHEDULE DEMO</a>
                <?php endif ?>
            </div>

            <div class="col-xs-4 logo"><a href="/"><img class="img-responsive" src="/images/nccbp-logo.jpg" /></a></div>
            <div class="col-xs-4">

                <?php if(!$this->zfcUserIdentity()): ?>
                    <a href="#" class="btn login-btn" role="button" id="loginButton">SIGN IN</a>
                    <div id="headerLoginForm">
                        <? $form = $this->plugin('zfcUserLoginWidget')->getLoginForm();
                        $form->get('identity')->setAttribute('placeHolder', 'Email');
                        $form->get('credential')->setAttribute('placeHolder', 'Password');
                        ?>
                        <?= $this->zfcUserLoginWidget() ?>
                    </div>
                <?php endif ?>

            </div>
        </div>
        <div class="col-xs-12">

            <nav class="navbar navbar-default" role="navigation">
                <div class="container-fluid">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>

                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="navbar-collapse collapse" id="bs-example-navbar-collapse-1">
                        <?php //$menuOptions = array('ulClass' => 'nav pull-right') ?>
                        <?php $partial = array('mrss/menu/nccbp-navigation.phtml', 'default') ?>
                        <?php $navigation = 'navigation' ?>
                        <?php if ($this->currentStudy()->getId() == 1) {
                            $navigation = 'nccbp_navigation';
                        } ?>
                        <?= $this->navigation()->menu($navigation)->setPartial
                            ($partial)
                            ->render(); ?>
                    </div>

                </div><!-- /.container-fluid -->
            </nav>

        </div>
    </div>
</header>
<!-- END HEADER -->

<!-- BEGIN BODY -->
<?php foreach ($this->flashMessages(true) as $namespace => $messages) : ?>
    <?php if (count($messages)) : ?>
        <?php foreach ($messages as $message) : ?>
            <div class="alert alert-<?=$namespace?>">
                <?php echo $message; ?>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>
<?php endforeach; ?>

<?php if (empty($this->noWrapper)): ?>
    <?php if ($this->zfcUserImpersonatorDisplayName()): ?>
        <div class="impersonation">
            <span><a title="Unimpersonate" href="<?= $this->url('zfcuserimpersonate/unimpersonate') ?>">
                    <?= $this->zfcUserImpersonatorDisplayName() ?></a> is impersonating
            </span>

            <?= $this->zfcUserDisplayName() ?>
            (<?= $this->zfcUserIdentity()->getCollege()->getName() ?>)
        </div>
    <?php endif ?>
<?php endif ?>

<?php if ($this->isAllowed('adminMenu', 'view')): ?>
    <div class="adminNavigation">
        <h3>Admin</h3>

        <?php $partial = array('mrss/menu/navigation.phtml',
            'default') ?>
        <?= $this->navigation('admin_navigation')
            ->menu()
            ->render(); ?>
        <div class="clearfix"></div>
    </div>
<?php endif ?>

<?php if (empty($this->noWrapper)): ?>
    <div id="content">

        <div class="container-fluid container">
            <div class="row-fluid row">



                <div class="span12 col-xs-12">
                    <?php echo $this->content; ?>
                </div>
            </div>

        </div>
    </div>

<?php else: ?>
    <?php echo $this->content; ?>

<?php endif ?>


<!-- END BODY -->
<!-- BEGIN FOOTER -->
<div class="footer">
    <div class="container">
        <div class="col-xs-2">
            <a href="#"><img src="/images/nccbp/benchmark_logo.png" /></a>
        </div>
        <div class="col-xs-10">
            <ul class="footer-nav">
                <li><a href="#">NCCBP</a></li>
                <li><a href="#">Who We Help</a></li>
                <li><a href="#">Reports</a></li>
                <li><a href="#">Join Now</a></li>
                <li><a href="#">About Us</a></li>
                <li><a href="#">Contact Us</a></li>
                <li><a href="#">Confidentiality</a></li>
            </ul>
            <p>© 2004 - <?= date('Y') ?> Johnson County Community College</p>
        </div>
    </div>
</div>
<!-- END FOOTER -->
</body>
</html>
