<?php

// Data Tables
$this->headScript()->appendFile(
    '/js/jquery.dataTables.min.js',
    'text/javascript'
);
$this->headLink()->appendStylesheet('/css/jquery.dataTables.min.css');
?>

<script>
    $(document).ready(function() {
        $('#colleges').dataTable({
            "order": [[1, "asc"]],
            // show X entries options
            "aLengthMenu": [[25, 50, 100, -1], [25, 50, 100, "All"]],
            'iDisplayLength': 25
        });

        $('.heatMapYear, .heatmapTd').css('width', '20px')

        //$('.heatmapCell').tooltip()
    });
</script>


<h1>Colleges</h1>

<table class="style1 table heatmap" id="colleges">
    <thead>
    <tr>
        <th>IPEDS</th>
        <th>College</th>
        <?php foreach ($years as $year): ?>
            <th class="heatMapYear"><?= $year ?></th>
        <?php endforeach ?>
        <th>City</th>
        <th>State</th>
    </tr>
    </thead>

    <tbody>
    <?php foreach ($this->colleges as $college): ?>

        <tr>
            <td><?= $college->getIpeds() ?></td>
            <td>
                <a href="<?= $this->url(
                    'colleges/view',
                    array(
                        'id' => $college->getId()
                    )
                ); ?>">
                    <?= $college->getName() ?>
                </a>
            </td>
            <?php $subs = $college->getSubscriptionsForStudy($this->currentStudy()) ?>
            <?php foreach ($years as $year): ?>

                <?php if (!empty($subs[$year]) && $sub = $subs[$year]): ?>
                    <?php $percentage = $sub->getCompletion(); ?>
                    <td class="heatmapTd heatmapCell heatmapCellBlue" style="opacity: <?= $percentage / 100 ?>">
                        <div data-toggle=tooltip" data-placement="bottom" title="<?= $year ?>">
                            <?= round($percentage) ?>%
                        </div>

                    </td>
                <?php else: ?>
                    <td></td>
                <?php endif ?>

            <?php endforeach ?>

            <td><?= $college->getCity() ?></td>
            <td><?= $college->getState() ?></td>
        </tr>

    <?php endforeach ?>
    </tbody>
</table>
