<?php

// Data Tables
$this->headScript()->appendFile(
    '/js/jquery.dataTables.min.js',
    'text/javascript'
);
$this->headLink()->appendStylesheet('/css/jquery.dataTables.min.css');
?>

<script>
    <?php $this->headScript()->captureStart() ?>
    $(document).ready(function() {
        $('#colleges').dataTable({
            "order": [[2, "asc"]],
            // show X entries options
            "aLengthMenu": [[25, 50, 100, -1], [25, 50, 100, "All"]],
            'iDisplayLength': 25
        });

        $('.heatMapYear, .heatmapTd').css('width', '20px')


    });
    <?php $this->headScript()->captureEnd() ?>
</script>

<div class="btn-group heading-btns">
    <a class="btn btn-default" href="<?= $this->url('colleges/download') ?>">
        <i class="glyphicon glyphicon-circle-arrow-down"></i>
        Download</a>
    </a>

    <a class="btn btn-default" href="<?= $this->url('colleges/add') ?>">
        <i class="glyphicon glyphicon-plus"></i>
        Add <?= ucwords($this->studyConfig()->institution_label) ?></a>
    </a>
</div>


<h1><?= ucwords($this->studyConfig()->institutions_label) ?></h1>

<table class="style1 table heatmap" id="colleges">
    <thead>
    <tr>
        <th>IPEDS Id</th>
        <th>OPE Id</th>
        <th><?= ucwords($this->studyConfig()->institution_label) ?></th>
        <?php foreach ($years as $year): ?>
            <th class="heatMapYear"><?= $year ?></th>
        <?php endforeach ?>
        <th>Users</th>
        <th>State</th>
        <th><?= ucwords($this->studyConfig()->system_label) ?></th>
    </tr>
    </thead>

    <tbody>
    <?php foreach ($this->colleges as $college): ?>

        <tr>
            <td><?= $college->getIpeds() ?></td>
            <td><?= $college->getOpeId() ?></td>
            <td>
                <a href="<?= $this->url(
                    'colleges/view',
                    array(
                        'id' => $college->getId()
                    )
                ); ?>">
                    <?= $college->getName() ?>
                </a>
            </td>
            <?php $subs = $college->getSubscriptionsForStudy($this->currentStudy()) ?>
            <?php foreach ($years as $year): ?>

                <?php if (!empty($subs[$year]) && $sub = $subs[$year]): ?>
                    <?php $percentage = $sub->getCompletion(); ?>
                    <td class="heatmapTd heatmapCell <?= $sub->getHeatmapClass() ?>" style="opacity: <?= ($percentage / 120) + 0.2 ?>">
                        <div data-toggle=tooltip" data-placement="bottom" title="<?= $year ?>">
                            <?= round($percentage) ?>%
                        </div>

                    </td>
                <?php else: ?>
                    <td></td>
                <?php endif ?>

            <?php endforeach  ?>

            <td style="font-size:80%">
                <?php foreach ($college->getUsers() as $user): ?>
                    <a href="<?= $this->url(
                        'users/edit',
                        array('id' => $user->getId())
                    ) ?>">
                        <?= $user->getFullName() ?>
                    </a><br>
                <?php endforeach ?>
            </td>
            <td><?= $college->getState() ?></td>
            <td>
                <?php if ($systemNames = $college->getSystemNames()): ?>
                    <?= implode(', ', $systemNames) ?>
                <?php endif ?>
            </td>
        </tr>

    <?php endforeach ?>
    </tbody>
</table>


<?php if ($this->currentStudy()->hasSections()): ?>
    <h3>Legend</h3>

    <?php $allSectionNames = $allSectionIds = array(); ?>
    <?php foreach ($this->currentStudy()->getSections() as $section): ?>

        <span class="heatmapLegend heatmapCell <?= $sub->getHeatmapClass(array($section->getId())) ?>">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
        <?= $section->getName() ?>
        <br>
        <?php $allSectionIds[] = $section->getId() ?>
        <?php $allSectionNames[] = $section->getName() ?>
    <?php endforeach ?>


    <span class="heatmapLegend heatmapCell <?= $sub->getHeatmapClass($allSectionIds) ?>">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
    <?= implode(', ', $allSectionNames) ?>
<?php endif ?>
