
<script type='text/javascript' src='https://www.google.com/jsapi'></script>
<script type='text/javascript'>
    google.load('visualization', '1', {'packages': ['geomap']});
    google.setOnLoadCallback(drawMap);

    function drawMap() {
        var data = google.visualization.arrayToDataTable([
            ['City', 'Popularity'],
            <? $i = 0 ?>
            <?php foreach ($this->colleges as $college): ?>
                <? $city = addslashes($college->getCity()); ?>
                <? $state = $college->getState() ?>
                <?= "['$city, $state', 1],\n" ?>

                <? if ($i++ > 50) break; ?>
            <?php endforeach ?>

            /*['New York', 200],
            ['Boston', 300],
            ['Miami', 400],
            ['Chicago', 500],
            ['Los Angeles', 600],
            ['Houston', 700]*/
        ]);

        var options = {};
        options['region'] = 'US';
        options['colors'] = [0xFF8747, 0xFFB581, 0xc06000]; //orange colors
        options['dataMode'] = 'markers';

        var container = document.getElementById('map_canvas');
        var geomap = new google.visualization.GeoMap(container);
        geomap.draw(data, options);
    };

</script>

<div id='map_canvas'></div>