<?php
/** @var \Mrss\Entity\College[] $colleges */

$this->headScript()->appendFile(
    '/map/jquery-jvectormap-1.2.2.min.js',
    'text/javascript'
);
$this->headScript()->appendFile(
    '/map/jquery-jvectormap-us-aea-en.js',
    'text/javascript'
);
$this->headLink()->appendStylesheet('/map/jquery-jvectormap-1.2.2.css');

// Data Tables
$this->headScript()->appendFile(
    '/js/jquery.dataTables.min.js',
    'text/javascript'
);
$this->headLink()->appendStylesheet('/css/jquery.dataTables.min.css');
?>

<style type="text/css">
    #subscriptions_wrapper {
        margin-top: 30px;
    }

    .dataTables_filter input {
        display: inline-block !important;
    }

    #allStates {
        display: none;
        /*margin-left: 15px;*/
    }

    .whowehelp-content {
        clear: both;
        margin-top: 30px;
    }
    .jvectormap-zoomin, .jvectormap-zoomout {
        width: 13px;
        height: 13px;
        padding: 1px;
    }
</style>

<script>
    var map
    // Highlight states with systems
    var systemColor = '#CFF270'
    var systemColors = {
        'US-WY': systemColor,
        'US-TN': systemColor,
        'US-NY': systemColor,
        'US-SC': systemColor,
        'US-PA': systemColor,
        'US-MO': systemColor,
        'US-KY': systemColor,
        'US-HI': systemColor,
        'US-CO': systemColor,
        'US-AZ': systemColor,
        'US-TX': systemColor,
        'US-IN': systemColor
    }
    $(document).ready(function() {
        // Data table
        var dataTable = $('#subscriptions').dataTable({
            // show X entries options
            "aLengthMenu": [[25, 50, 100, -1], [25, 50, 100, "All"]],
            'iDisplayLength': 25
        });


        // Map
        var width = $('#peer-map').parent().width();
        var height = width * 0.5
        $('#peer-map').css('width', width + 'px')
        $('#peer-map').css('height', height + 'px')

        map = new jvm.WorldMap({
            map: 'us_aea_en',
            container: $('#peer-map'),
            zoomOnScroll: false,
            markerStyle: {
                initial: {
                    fill: '#336699'
                },
                hover: {
                    fill: '#8BAF42'
                }
            },
            regionsSelectable: true,
            regionsSelectableOne: true,
            regionStyle: {
                initial: {
                    fill: '#FFFFFF',
                    stroke: '#7bc6f6',
                    "stroke-width": 1,
                    "stroke-opacity": 1
                },
                selected: {
                    fill: '#c3dcec'
                },
                hover: {
                    fill: '#d3ecfc'
                }
            },
            series: {
                regions: [{
                    values: systemColors
                }]
            },
            markers: <?= $markers ?>,
            onRegionClick: function(event, code) {
                code = code.replace('US-', '')
                dataTable.fnFilter(code, 1)
                $('#allStates').show()
            }
        });



        $('#allStates').click(function() {
            map.clearSelectedRegions()
            dataTable.fnFilter('', 1)
            $('#allStates').hide()
            return false
        })
    });
</script>


<div class="container">
    <div class="row">
        <div class="col-xs-12 sec-header">
            <h1>Peer Institutions</h1>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12">
            <p class="lead sec-intro">Since 2004, over 400 two-year institutions have participated in the National Community College Benchmark Project (NCCBP) including the state systems of New York (SUNY), Indiana (Ivy Tech), Missouri, Pennsylvania, Wyoming, Hawaii, South Carolina and other systems including Maricopa County and Dallas County Community College District.<br>

                <span style="font-size: 70%">The states with system members are highlighted in green.  To see a list of member colleges, click on each state. The blue dots represent colleges that have participated in the NCCBP for at least one year between 2007 and 2014.</span></p>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12 sec-image">
            <div id="past-participants"><div id='peer-map' style='width: 940px; height: 430px'></div>
        </div>

    </div>

    <div class="row">

        <div class="col-md-12 whowehelp-content">
            <p id="allStates">
                <a href="#">Show participants from all states</a>
            </p>

            <table class="table table-striped" id="subscriptions">
                <thead>
                <tr>
                    <th>Institution</th>
                    <th>State</th>
                    <th>System</th>
                    <?php foreach ($sections as $section): ?>
                        <th><?= $section->getName() ?></th>

                    <?php endforeach ?>
                </tr>
                </thead>
                <tbody>

                <?php foreach ($colleges as $college): ?>

                    <tr>
                        <td><?= $college->getName() ?></td>
                        <td><?= $college->getState() ?></td>
                        <td>
                            <?php if ($system = $college->getSystem()): ?>
                                <?= $system->getName() ?>
                            <?php endif ?>
                        </td>
                        <?php foreach ($sections as $section): ?>
                            <td style="text-align: center">
                                <?php if (in_array($section->getId(), $college->getSectionIds())): ?>
                                    <span class="glyphicon glyphicon-ok"></span>
                                <?php endif ?>
                            </td>

                        <?php endforeach ?>

                    </tr>
                <?php endforeach ?>

                </tbody>
            </table>
        </div>
    </div>
</div>
