<? /** @var \Mrss\Entity\College $college */ ?>

<h1><?= $college->getName() ?></h1>

<table class="style1">
    <tr>
        <td>
            IPEDS:
        </td>
        <td>
            <?= $college->getIpeds() ?>
        </td>
    </tr>
    <tr>
        <td>
            Address:
        </td>
        <td>
            <?= $college->getFullAddress() ?>
        </td>
    </tr>
    <tr>
        <td>
            Executive:
        </td>
        <td>
            <?= $college->getExecTitle() ?><br>
            <?= $college->getExecFullName() ?><br>
            <?= $college->getExecEmail() ?>
        </td>
    </tr>
    <tr>
        <td>
            Subscriptions:
        </td>
        <td>
            <ul>
                <?php foreach ($college->getSubscriptions() as $subscription): ?>
                    <li>
                        <?php if ($observation = $subscription->getObservation()): ?>
                        <a href="<?= $this->url(
                            'observation',
                            array('id' => $subscription->getObservation()->getId())
                        ) ?>">
                            <?= $subscription->getYear() ?>
                            <?= $subscription->getStudy()->getName() ?>
                        </a>
                        (<?= $subscription->getStudy()->getCompletionPercentage(
                            $subscription->getObservation()
                        ) ?>%)
                        <?php else: ?>
                            No observation for <?= $subscription->getYear() ?>
                            <?= $subscription->getStudy()->getName() ?>
                        <?php endif ?>
                    </li>
                <?php endforeach ?>
            </ul>
        </td>
    </tr>
    <tr>
        <td>
            Users:
        </td>
        <td>
            <ul>
                <?php foreach ($college->getUsers() as $user): ?>
                    <li>
                        <a title="Impersonate this user"
                           href="/admin/user/impersonate/<?= $user->getId() ?>">
                            <i class="icon icon-fire"></i></a>
                        <a href="<?= $this->url(
                            'users/edit',
                            array('id' => $user->getId())
                        ) ?>">
                            <?= $user->getFullName() ?>
                        </a>
                    </li>
                <?php endforeach ?>
            </ul>

            <a href="<?= $this->url('users/edit', array('id' => 'add', 'college' => $college->getId())) ?>" class="btn btn-default">
                <i class="glyphicon glyphicon-plus icon icon-plus"></i>
                Add User
            </a>
        </td>
    </tr>
</table>
