<h3>Import Complete</h3>

<a href="<?= $this->url(
    'studies/import',
    array('id' => $this->currentStudy()->getId())
) ?>" onclick="return confirm(
        'This will make permanent changes to the data. Are you sure you want to do this?')
        ">
    <span class="icon-upload"></span>
    Import again
</a>

<?php if (!empty($messages)): ?>

    <div class="well">
        <pre>
            <?= $messages ?>
        </pre>
    </div>
<?php endif ?>
