<h2>Studies</h2>

<table class="table table-striped">
    <tbody>
    <?php foreach ($this->studies as $study): ?>
        <tr>
            <td>
                <?php echo $study->getName() ?>
            </td>
            <!--td>
                <a href="<?= $this->url(
                    'studies/completion',
                    array('id' => $study->getId())
                ) ?>">
                    Completion
                </a>
            </td-->
            <td>
                <a href="<?= $this->url('benchmark', array('study' => $study->getId())) ?>">
                    Benchmark Setup
                </a>
            </td>
            <td>
                <a href="<?= $this->url(
                    'offercodes',
                    array('study' => $study->getId())
                ) ?>">Offer Codes (<?= count($study->getOfferCodes()) ?>)</a>
            </td>
            <td>
                <a href="<?= $this->url(
                    'studies/edit',
                    array('id' => $study->getId())
                ) ?>">Settings</a>
            </td>

            <? /*<td>
                <a href="<?= $this->url(
                    'studies/import',
                    array('id' => $study->getId())
                ) ?>">
                    Import Benchmark Setup from CSV
                </a>
            </td>*/ ?>

        </tr>
    <?php endforeach ?>

    </tbody>
</table>
