<h2>Studies</h2>

<ul>
    <?php foreach ($this->studies as $study): ?>
        <li>
            <a href="<?= $this->url('studies/view', array('id' => $study->getId())) ?>">
                <?php echo $study->getName() ?>
            </a>
            (<a href="<?= $this->url(
                'studies/edit',
                array('id' => $study->getId())
            ) ?>">Edit</a>)
        </li>
    <?php endforeach ?>
</ul>
