<h2><?= $study->getName() ?></h2>

<ul>
    <li>
        <a href="<?= $this->url(
            'benchmark',
            array('study' => $study->getId())
        ) ?>">
            Benchmark Groups
        </a>
    </li>

    <li>
        <a href="<?= $this->url(
            'studies/completion',
            array('id' => $study->getId())
        ) ?>">
            Completion
        </a>
    </li>

    <li>
        <a href="<?= $this->url(
            'studies/import',
            array('id' => $study->getId())
        ) ?>">
            Import Benchmark Setup from CSV
        </a>
    </li>
</ul>
